### ISSUE TITLE
Fragment切换后，ViewModel中的LiveData数据改变但是不能更新界面。

### ISSUE THREAD

**Issue by zhuzichu520** [Tencent/QMUI_Android#1022]
### 运行环境 ###

- [x] 小米10
- [x] android10
- [x] 6.7.0
- [x] 2.0.0-alpha10

### 具体问题描述 ###
QMUIFragment切换后，ViewModel中的LiveData数据改变但是不能更新界面。首次进入Fragment是没问题，但是跳转到另一个Fragment，然后返回后LiveData就失效，里面数据是改变了，视图不更新

**Comment by zhuzichu520** [comment]
好吧，已经解决～～！切换后调用了onDestroyView，把ViewDataBinding对象释放了

**Comment by 5jzztsqs** [comment]
> 好吧，已经解决～～！切换后调用了onDestroyView，把ViewDataBinding对象释放了

咋解决的
