### ISSUE TITLE
QMUI_Android 配置QMUI.Compat.NoActionBar无法正常隐藏ActionBar

### ISSUE THREAD

**Issue by lumotime** [Tencent/QMUI_Android#1037]
### 运行环境 ###

- [x] 设备型号：如：`MI 9`
- [x] 设备系统版本：如 `Android 10.0`
- [x] Gradle 版本：如 `6.1.1`
- [x] QMUI Android 版本：`2.0.0-alpha10`
- [x] AndroidX AppCompat 版本: `1.2.0` 

### 具体问题描述 ###
QMUI_Android 配置QMUI.Compat.NoActionBar无法正常隐藏ActionBar
但使用AppCompat下的 Theme.AppCompat.NoActionBar 时就可以正常隐藏ActionBar.
![未修复前的样子](https://j3dream-1303029773.cos.ap-guangzhou.myqcloud.com/blog/image_1606442627929.png)

### 解决方案 ###
![Theme.AppCompat.NoActionBar](https://j3dream-1303029773.cos.ap-guangzhou.myqcloud.com/blog/image_1606442676879.png)
![QMUI.NoActionBar](https://j3dream-1303029773.cos.ap-guangzhou.myqcloud.com/blog/image_1606442714193.png)

根据两个截图可以观察到 QMUI.NoActionBar 和 Theme.AppCompat.NoActionBar 并无任何区别. 

几经尝试之下, 我做出了如下改变解决了该问题。

![image.png](https://j3dream-1303029773.cos.ap-guangzhou.myqcloud.com/blog/image_1606442903645.png)

仅仅因为两个属性的命名空间不同嘛? 有多少人遇到这种情况? 
[link](https://blog.j3dream.top/archives/qmuiandroidnoactionbarnotactive)

**Comment by tangyaogang** [comment]
没有用

**Comment by fyvcoder** [comment]
没有用
