### ISSUE TITLE
QMUIRoundButton 设置背景颜色不起作用

### ISSUE THREAD

**Issue by zhangjw-ECHO** [Tencent/QMUI_Android#1081]
### 运行环境 ###

- [x] 设备型号：红米note8 pro
- [x] 设备系统版本：Android 11
- [x] Gradle 版本：6.5
- [x] QMUI Android 版本：2.0.0-alpha 11

### 具体问题描述 ###
<com.qmuiteam.qmui.widget.roundwidget.QMUIRoundButton
                    android:id="@+id/btn_get_verify_code"
                    android:padding="5dp"
                    android:layout_marginBottom="5dp"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="end|center_vertical"
                    android:text="@string/txt_btn_get_verfiy_code"
                    android:textColor="@color/app_color_blue"
                    android:textSize="14sp"
                    app:qmui_backgroundColor="@color/s_btn_blue"
                    app:qmui_borderColor="@color/app_color_blue"
                    app:qmui_borderWidth="1.5dp"
                    app:qmui_radius="5dp" />
qmui_backgroundColor 无论怎么改变，还是默认的颜色

**Comment by zhangjw-ECHO** [comment]
使用问题，非框架bug，不好意思

**Comment by ckrgithub** [comment]
@zhangjw-ECHO 你好，我也遇到这个问题。你是怎么解决的
