### ISSUE TITLE
怎么编译不过去呀

### ISSUE THREAD

**Issue by XingSpace** [Tencent/QMUI_Android#1138]
### 运行环境 ###
Android Studio Bumblebee | 2021.1.1 Patch 1

### 具体问题描述 ###

A problem occurred configuring root project 'QMUI-Android'.
> =============================== Gradle Doctor Prescriptions ============================================
  | Gradle is not using JAVA_HOME.
                                                                      |
  | JAVA_HOME is C:\Program Files\Java\jre1.8.0_121
                                                     |
  | Gradle is using D:\Android\Android Studio\jre
                                                       |
  | This can slow down your build significantly when switching from Android Studio to the terminal.
     |
  | To fix: Project Structure -> JDK Location.
                                                          |
  | Set this to your JAVA_HOME.

**Comment by XingSpace** [comment]
设置JAVA_HOME也没什么用

**Comment by XingSpace** [comment]
plugins {
    id("qmui-dep")
//    id("com.osacky.doctor") version "0.8.0"
}
解决了，注释掉com.osacky.doctor就行了

**Comment by Ag-gu** [comment]
赞

**Comment by yykedward** [comment]
赞
