### ISSUE TITLE
关于setCheckedIndex 不应该在 setOnSheetItemClickListener调用后获取position 然后setCheckedIndex（position）的吗？

### ISSUE THREAD

**Issue by kinghom** [Tencent/QMUI_Android#1145]
![image](https://user-images.githubusercontent.com/23691629/177946992-c3040653-8500-4fe1-a2c7-18e076d900c7.png)

**Comment by kinghom** [comment]
在外面 我怎么获取被选的position位置呀？

**Comment by Theoneee** [comment]
`setCheckedIndex（position）` 是创建时你直接指定的选中位置，点击后被选中的位置如你图所示：`position`

**Comment by kinghom** [comment]
已经收到你的飞鸽传书啦....
