### ISSUE TITLE
TopBar如何实现类似QQ的渐变色

### ISSUE THREAD

**Issue by li-lance** [Tencent/QMUI_Android#163]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
如题。

**Comment by cgspine** [comment]
TopBar 也是一个 View，你可以给它设置一个渐变的背景啊

**Comment by theoneee** [comment]
QQ在白色主题的时候是直接把状态栏颜色改成那个颜色了吧。为了兼容其他的Android手机。毕竟只有Flyme和MIUI可以有黑色的状态栏图标和时间。
