### ISSUE TITLE
希望可以列表添加上拉加载更多地的功能 列表Empty的状态

### ISSUE THREAD

**Issue by autotrans** [Tencent/QMUI_Android#21]

**Comment by cgspine** [comment]
我们目前没有上拉加载的方式，后续可能会考虑。目前列表的加载更多功能，一般是放一个 Item 在列表的最后，可以方便地做到自动触发 loadMore 或点击时 loadMore 两种方式。

至于列表 Empty 的状态下，一般做法是判断数据为空时，隐藏 ListView、显示一个 QMUIEmptyView 出来。

**Comment by oxsource** [comment]
希望可以列表添加上拉加载更多地的功能 列表Empty的状态

**Comment by Theoneee** [comment]
足够了吧，加载更多都是封装在了适配器里面。
