### ISSUE TITLE
startFragment使用replace fragment时，侧滑返回出现空白。

### ISSUE THREAD

**Issue by caoshen** [Tencent/QMUI_Android#241]
### 运行环境 ###

- [x] 设备型号：如：`MI 5`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.0.6`

### 具体问题描述 ###
startFragment使用replace fragment时，侧滑返回出现空白。
从HomeFragment的viewpager里的子fragment启动新的fragment时，侧滑过程中viewpager所在位置为空白，bottombar显示正常，侧滑结束后恢复正常。

**Comment by cgspine** [comment]
0.0.4 版本修复了这个问题
