### ISSUE TITLE
demo里“沉浸式”状态栏好坑啊，项目里这样设置背景分分钟过度绘制

### ISSUE THREAD

**Issue by ToGallop** [Tencent/QMUI_Android#302]
### 具体问题描述 ###
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              **android:background="@color/app_color_theme_4"**
              android:fitsSystemWindows="true"
              android:orientation="vertical">

    <com.qmuiteam.qmui.widget.QMUITopBar
        android:id="@+id/topbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/qmui_topbar_height"/>

    <TextView
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
       **android:background="@color/qmui_config_color_white"**
        android:gravity="center"
        android:padding="30dp"
        android:text="@string/statusBarHelper_translucentActivity_desc"/>

</LinearLayout>

**Comment by cgspine** [comment]
用 QMUITopBarLayout，QDAboutFragment 中的使用方式，可以避免一层背景绘制。

**Comment by lijunguan** [comment]
@cgspine  在单Activity 多Fragment 架构中（例如常见的首页多Tab），很不好处理。  每个Fragment本质是一个View，添加第一个Fragment的时候，就会消费了SystemWindowInsets，看了系统源码递归遍历的只会消费一次，后续add 的Fragment布局就不会再有机会消费了，导致布局没有正确添加到Padding，后来即使让Fragment container容器使用QMUIWindowInsetLayout，看了源码 虽然他可以把SystemWindowInsets 分发给每个子View 消费，也不能很好解决，因为我的Fragment不是一开始就添加到容器的，懒加载的。已经理解了这一套的原理，有一些解决方案，但是觉得都不是很优雅。  而且我们的topbar 是渐变色背景 真的不想采用Demo的粗暴方案，多层绘制严重， 想问问QQ 之前采用渐变色背景的时候 是如何处理的，得到一些启迪。

**Comment by cgspine** [comment]
我觉得像 QMUIWindowInsetLayout 一样写一个自定义的容器去分发 SystemWindowInsets 是比较可行的方案，渐变背景设置在 QMUITopBarLayout 上，懒加载也没关系吧，只要 fragment 触发 requestApplyInsets 就能解决吧。 （并不知道 QQ 的实现方式）

**Comment by lijunguan** [comment]
@cgspine 我现在就是这样的，遇到Activity 多Fragment的情况，使用QMUIWindowInsetLayout做容器， 每次添加新的Fragment 会 手动去触发requestApplyInsets() 。本来想设计一个比较通用底层的UI来完成状态栏着色，减少业务使用上的感知，但是现在写业务的人还是需要比较清楚这套逻辑，小心的使用。   非常感谢你的回答，接下来会再思考一下有没有更好的解决方案，页会持续关注的，希望可以从你这学习到更好的方案。          顺便提一下，现在master 分支上的demo 也有这个问题，没有requestApplyInsets ，ViewPage切换到第三页的时候，就会有这个问题。

**Comment by cgspine** [comment]
谢谢指出，android 的 fitSystemWindow 机制确实有点坑，已经很小心封装了，但是业务上还是容易踩坑。
