### ISSUE TITLE
我的初建项目时，compile 'com.qmuiteam:qmui:1.1.3'， qmui的这个包一直下不下来，是因为被墙了吗，还是怎么回事？？？

### ISSUE THREAD

**Issue by Changqing980518** [Tencent/QMUI_Android#319]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by javakam** [comment]
试试1.1.5

**Comment by evan-cai** [comment]
我也是

**Comment by evan-cai** [comment]
搞了一个上午，还是无法用gradle把包下下来，请问怎么解决呀

**Comment by evan-cai** [comment]
解决了，将`compileSdkVersion`设置为`27`，`targetSdkVersion`设置为`27`，
然后dependencies里相关的版本改成27.1.1
```
implementation 'com.android.support:appcompat-v7:27.1.1'

implementation 'com.android.support:design:27.1.1'

implementation 'com.android.support:support-vector-drawable:27.1.1'

implementation 'com.qmuiteam:qmui:1.1.5'
```

**Comment by arvinsen** [comment]
jcente()可能被墙了，你换个源试试，我自己改了一下gradle源，用的阿里的源，下好了之后再改回来就是了，问题不大
