### ISSUE TITLE
QMUICollapsingTopBarLayout

### ISSUE THREAD

**Issue by 271845221** [Tencent/QMUI_Android#327]
### 运行环境 ###

- [x] 设备型号：小米3（其他手机均可）
- [x] 设备系统版本：Android 6.0
- [x] Gradle 版本：3.1.0
- [x] QMUI Android 版本：1.1.3

### 具体问题描述 ###
QMUI_Android项目（QMUI库提供的Demo工程）中的
com.qmuiteam.qmuidemo.fragment.components.QDCollapsingTopBarLayoutFragment类中的protected View onCreateView() {}方法最后一行添加如下代码：

       final Button button = mTopBar.addRightTextButton("订阅", R.id.right_button_id);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                button.setSelected(!button.isSelected());
                button.setText(button.isSelected() ? "取消订阅" : "订阅");
            }
        });

当QMUICollapsingTopBarLayout收缩到顶部时，点击“订阅”或“取消订阅”时，顶部横向居中的标题不见了。

**Comment by leeyun** [comment]
重复绘制的坑，简单粗暴的解决方案是在添加相关view前 ```
topBar.removeAllRightViews();
    topBar.removeAllLeftViews();
```
或者让topBar的添加操作只创建一次
