### ISSUE TITLE
QMUITabSegment的Indicator的长度问题

### ISSUE THREAD

**Issue by zichen-jiao** [Tencent/QMUI_Android#340]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###

怎样固定的设置Indicator的长度。不平分也不跟随内容的长度。

**Comment by chanthuang** [comment]
现在不支持对 indicator 本身设置宽度。
提供一个替代方案：你可以用一个自定义 Drawable 作为 Indicator，然后在其内部自己绘制需要的图形。
