### ISSUE TITLE
对话框弹出的时候状态栏字体颜色发生变化

### ISSUE THREAD

**Issue by wjianchen13** [Tencent/QMUI_Android#341]
当把状态栏字体设置成深色字体时，点击对话框弹出会恢复的白色，关闭对话框又会恢复到黑色，怎样使对话框弹出的时候不改变状态栏原本是深色的字体，或者设置成我想要的模式（深色字体或白色字体），这种情况在部分机型会出现，比如华为PLK-TL01H，有些机型不会出现这个问题。

**Comment by chanthuang** [comment]
系统层级行为
