### ISSUE TITLE
  Caused by: android.view.InflateException: Binary XML file line #103: Error inflating class com.jpardogo.listbuddies.lib.views.ListBuddiesLayout

### ISSUE THREAD

**Issue by RolaCoding** [Tencent/QMUI_Android#344]
有冲突报错
引用了 ListBuddiesLayout不能用
建议大家之后不要用了2014年出的控件
现在与Android7.0应该不支持冲突了
I can not use it,there is a corrupt with version more than Android 7.0

**Comment by cgspine** [comment]
ListBuddiesLayout 的问题？

**Comment by RolaCoding** [comment]
对的，只要加入这个组件就运行不起来，gradle版本4.4
