### ISSUE TITLE
CustomDialogBuilder  setLayout(layoutResId) 创建的Dialog 控件外观变化很大

### ISSUE THREAD

**Issue by MAIMIHO** [Tencent/QMUI_Android#349]
### 运行环境 ###

- [x] 设备型号：非特定型号
- [x] 设备系统版本：非特定版本
- [x] Gradle 版本：非特定版本
- [x] QMUI Android 版本：`1.1.5`

### 具体问题描述 ###
QMUIDialog.CustomDialogBuilder  setLayout(layoutResId) 创建的Dialog外观变化很大, 如下图. 

请教一下大佬, 现在需要在使用CustomDialogBuilder的情况下, 控件保持Material这种外观
这个需要怎么配置呢? 

谢谢!
#### 问题截图 ####

![image](https://user-images.githubusercontent.com/18633356/43260530-614b70b0-910c-11e8-93c5-40f4310f7421.png)

**Comment by MAIMIHO** [comment]
@zinc357 还没有, 暂时先放着了.

**Comment by cgspine** [comment]
CustomDialogBuilder 需要自己覆盖系统样式吧
