### ISSUE TITLE
QMUIDialog.MultiCheckableDialogBuilder 对话框 多选条目大于40个。第31个就默认选择了

### ISSUE THREAD

**Issue by BigBigDeBoy** [Tencent/QMUI_Android#366]
### 运行环境 ###

- 小米6
- Android 8.0
- Gradle 版本：3.0.1
- QMUI Android 版本：1.1.6

#### 问题截图 ####

![wechatimg660](https://user-images.githubusercontent.com/16618853/44190196-37ca5100-a158-11e8-87dc-56dd03d471a5.jpeg)

**Comment by cgspine** [comment]
恩，确实没有考虑到个数超过 int 位的情况。这种场景，应该用 ListView 去实现恰当一点

**Comment by hais1992** [comment]
> 恩，确实没有考虑到个数超过 int 位的情况。这种场景，应该用 ListView 去实现恰当一点

想问下这个现在要如何解决？

**Comment by chanthuang** [comment]
Please avoid adding too many items. 4665354
