### ISSUE TITLE
旧版本代码兼容问题！

### ISSUE THREAD

**Issue by YuShanMuGong** [Tencent/QMUI_Android#372]
如题，我是从旧版本升级上来的，但是其中API变动比较大！

![image](https://user-images.githubusercontent.com/13248312/44376397-f4425f00-a52a-11e8-8791-b894c72e7d09.png)
如图，现在的 QMUIDialog.EditTextDialogBuilder 的 mEditText 是在 onCreateContent 中实例化的，这个方法，在Dialog create的时候才会执行！ 但是以前的版本！

![image](https://user-images.githubusercontent.com/13248312/44376569-b85bc980-a52b-11e8-9e83-218c61de58f9.png)
以前版本是在构造方法中实例化的！

这就导致了我之前的代码，放到现在就出问题了：
![image](https://user-images.githubusercontent.com/13248312/44376670-11c3f880-a52c-11e8-86bf-d859632038e6.png)
发生空指针异常

**Comment by cgspine** [comment]
这里原本是解决构造方法初始化时theme错误的bug，没有留意到 `getEditText` 这个方法的存在。不过这个方法也不应该存在于 builder 之中。

期望的使用方式是：
`setPlaceholder(int resId) ` 设置 placeHolder
`setDefaultText(CharSequence defaultText)` 设置默认文案
点击 Button 时通过 `dialog.findViewById(R.id.qmui_dialog_edit_input)` 获取 EditText。

后期会 deprecated 掉`getEditText` 这个方法，补充使用注释
