### ISSUE TITLE
关于windowDrawsSystemBarBackgrounds属性的使用和虚拟导航栏的强制显示问题

### ISSUE THREAD

**Issue by XQ233** [Tencent/QMUI_Android#377]
### 运行环境 ###

- [x] 设备型号：如：`三星Note8`

### 具体问题描述 ###
  首先感谢一波大大的奉献精神~ @cgspine 
1.在引用QMUI主题后windowDrawsSystemBarBackgrounds强制设置为true以完成状态栏着色，但是底部虚拟导航栏颜色就无法自适应成Holo.Light主题下的白底黑按钮了，请问如何进行兼容呢
2.请问微信中底部虚拟导航栏是如何进行强制显示的呢，在window和phoneWindow中并没有找到一个类似setNeedsMenuKey的方法或者相关属性来进行反射操作

**Comment by cgspine** [comment]
1. `getWindow().setNavigationBarColor(); ` 可以设置导航栏背景色，不过 微信读书也没有做过任何设置，默认就是黑底白字，是否是手机原因？
2. 微信读书没有做过状态栏强制显示的设置，微信我就不清楚了。一般有没有虚拟导航栏都是系统控制的，全面屏在手机设置里有选项，app 是没办法控制的。

**Comment by XQ233** [comment]
在note8中主流应用都是白底黑按钮，尝试直接继承Light主题就是这种效果，但是继承QMUI后会由于windowDrawsSystemBarBackgrounds属性的设置变成黑底白按钮，如果仅仅想要状态栏透明而不需要改变状态栏颜色是否不需要设置windowDrawsSystemBarBackgrounds为true呢，感觉可以优化一波note8的体验，不知道是不是全面屏的个例

**Comment by cgspine** [comment]
主要是 FLAG_TRANSLUCENT_STATUS 这个标志位并不好用，在android 6以后的机器，系统还是会给个半透明背景，无法真正做到状态栏透明。

因此建议根据app特性使用`setNavigationBarColor()`设置导航栏颜色

**Comment by XQ233** [comment]
但是NavgationBar按钮颜色好像必须要Light主题配合windowDrawsSystemBarBackgrounds才行呢，但是还是谢谢大大了~

**Comment by cgspine** [comment]
也不一定要 Light 主题，SystemUiVisibility 中有一个 View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR。
这个在 android 6 以上生效。
