### ISSUE TITLE
滑动返回有好的解决方案么

### ISSUE THREAD

**Issue by fuhaodev** [Tencent/QMUI_Android#39]
如题，开源社区的解决方案如SwipeBackLayout、and_swipeback等或多或少都存在一些问题，不知道有没有更好的方案

**Comment by MoLice** [comment]
可能需要你更清楚地表达你的需求，例如：
1. 你对滑动返回这个功能有什么需求？
2. 怎么定义“好的解决方案”？
3. 你试用过的那些开源控件对你来说都存在什么问题？

**Comment by cgspine** [comment]
可以使用 arch 库了

**Comment by fuhaodev** [comment]
好的，多谢
