### ISSUE TITLE
QDMainActivity 中的  R.id.qmuidemo  在哪个layout文件?找了半天都没找到.

### ISSUE THREAD

**Issue by AOWOAO** [Tencent/QMUI_Android#408]
![default](https://user-images.githubusercontent.com/25810208/47255783-a1444400-d4a8-11e8-9138-41272d98fab2.png)

**Comment by lydlovezjr** [comment]
不是layout文件,参见ids.xml!!!

**Comment by cgspine** [comment]
可以看其父类 `QMUIFragmentActivity`。没有用 layout 文件，直接 java 代码 new 了一个 FrameLayout， 这里是给它补一个 id.
