### ISSUE TITLE
QMUIDialog 多选框

### ISSUE THREAD

**Issue by hais1992** [Tencent/QMUI_Android#435]
### 运行环境 ###

- [x] 设备型号：如：`ZUK Z2`
- [x] 设备系统版本：如 `Android 6.0`
- [x] Gradle 版本：如 `3.2.1`
- [x] QMUI Android 版本：`1.1.7`

### 具体问题描述 ###
val arr = arrayOf("1","2".........,"39","40")
QMUIDialog.MultiCheckableDialogBuilder(activity).addItems(arr).show()
会默认选择第32个，无论数据是什么都会默认选第32个

#### 问题截图 ####
![截图](https://i.loli.net/2018/11/15/5becf21b7931b.png)

**Comment by cgspine** [comment]
#366 建议用 ListView/RecyclerView 实现这么多 item 的多选以提升性能

**Comment by chanthuang** [comment]
Please use ListView/RecyclerView to avoid adding too many items. 4665354
