### ISSUE TITLE
QMUITabSegment 搭配ViewPager+fragment ， 动态更改fragment数量问题。

### ISSUE THREAD

**Issue by Koterwong** [Tencent/QMUI_Android#446]
### 具体问题描述 ###
具体操作在gif。
如果当前选中第四个标签，然后编辑的删除第四个标签，就会引起崩溃。
![default](https://user-images.githubusercontent.com/16436547/48929070-1d0a3400-ef20-11e8-8f76-1f024a4cff29.png)
![default](https://user-images.githubusercontent.com/16436547/48929076-28f5f600-ef20-11e8-94f8-a19e7a18b27f.png)
不知道是不是mSelectedIndex 在reset的时候没重置引起的。
#### 问题截图 ####

![default](https://user-images.githubusercontent.com/16436547/48928923-bcc6c280-ef1e-11e8-9878-8551dd729c3f.png)

![ezgif-6-dad276879b20](https://user-images.githubusercontent.com/16436547/48928883-5e99df80-ef1e-11e8-8240-fbe567a0b030.gif)

望大神们解答一下。

**Comment by cgspine** [comment]
恩，应该是 selectIndex 引起的，我这边修改下

**Comment by cgspine** [comment]
可升级到 1.1.10

**Comment by Koterwong** [comment]
好的，我试下。

**Comment by ShadeTeam** [comment]
@cgspine 您好，新手，不了解QMUITabSegment应该如何实现横向滑动的Tab，望指教一下.

**Comment by cgspine** [comment]
参考 QMUIDemo `QDTabSegmentScrollableModeFragment`

**Comment by Evatruy** [comment]
楼主问题解决了吗

**Comment by Koterwong** [comment]
@Evatruy 新版本已解决

**Comment by Evatruy** [comment]
感谢楼主回复，比心
