### ISSUE TITLE
侧滑返回的时候QMUICollapsingTopBarLayout标题丢失

### ISSUE THREAD

**Issue by xtsxx** [Tencent/QMUI_Android#451]
### 运行环境 ###

- [x] 设备型号：小米6、三星S7
- [x] 设备系统版本：Android8.1、Android6.0.1
- [x] Gradle 版本：3.2.1
- [x] QMUI Android 版本：`1.1.9`

### 具体问题描述 ###
侧滑返回的时候QMUICollapsingTopBarLayout标题丢失，如果QMUICollapsingTopBarLayout在滑动中途，则会出现错位
#### 问题截图 ####

![screenshot_20181130-163739](https://user-images.githubusercontent.com/16847201/49429721-2fb81f00-f7e4-11e8-96d2-48e8f45d3129.png)
![screenshot_20181130-163730](https://user-images.githubusercontent.com/16847201/49429725-321a7900-f7e4-11e8-9b2e-2c7de92e6203.png)

**Comment by xtsxx** [comment]
经过研究 在QMUIAppBarLayout中设置属性android:fitsSystemWindows="true"的时候会出现这个问题

**Comment by xtsxx** [comment]
目前通过设置QMUIAppBarLayout的paddingTop来规避此问题，暂不清楚为啥设置fitsSystemWindows="true"的时候会出现这个问题

**Comment by cgspine** [comment]
神奇，我这边不会出现，你那里必现吗？

**Comment by xtsxx** [comment]
> 神奇，我这边不会出现，你那里必现吗？

是的，在Demo里面就可以复现了，我用多台测试机都是可以复现的

**Comment by jingquanxie** [comment]
我也踩到这个坑了，请问还有其他办法处理一下么？

**Comment by cgspine** [comment]
可升级到 1.1.11
