### ISSUE TITLE
xml中自定义的属性不会在Androidstudio中智能提示

### ISSUE THREAD

**Issue by glmsb** [Tencent/QMUI_Android#452]

**Comment by chanthuang** [comment]
在 `qmui_attrs.xml` 中，如果在 name 属性为某个 class 名的 `declare-styleable` 标签中中，声明了 attr 属性，就能在 layout xml 文件中写该 class 名的时候弹出这些 attr 代码提示，如 `qmui_attrs.xml` 中定义如下：
```
<declare-styleable name="QMUITabSegment">
    <attr name="qmui_tab_indicator_height" format="dimension"/>
    ......
</declare-styleable>
```
就可以在写 `<com.qmuiteam.qmui.widget.QMUITabSegment>` 标签的时候弹出提示 `app:qmui_tab_indicator_height` 属性。

但如果 name 属性的不是某个 class 名，就无法自动提示，如 `qmui_attrs.xml` 中定义了
```
<declare-styleable name="QMUILayout">
    <!-- 各种 attrs -->
</declare-styleable>
```
但无法在 layout xml 文件中，写 `<com.qmuiteam.qmui.layout.QMUIRelativeLayout>` 时弹出提示。

我们应尽量避免 declare-styleable 的 name 和类名不一致的情况，方便开发者。
@cgspine
