### ISSUE TITLE
RoundButton文字换行问题

### ISSUE THREAD

**Issue by AlwaysGemini** [Tencent/QMUI_Android#456]
使用RoundButton，通过.setText("a\na");并不能实现换行，而是直接显示aa

**Comment by chanthuang** [comment]
因为 QMUI 默认样式对 QMUIButtonStyle 指定了 `singleLine="true"`，见 qmui_themes_compat.xml 中的 `<item name="QMUIButtonStyle">@style/QMUI.RoundButton</item>`。你可以自己对 Button 设置 `singleLine="fales"` 即可。

**Comment by AlwaysGemini** [comment]
> 因为 QMUI 默认样式对 QMUIButtonStyle 指定了 `singleLine="true"`，见 qmui_themes_compat.xml 中的 `<item name="QMUIButtonStyle">@style/QMUI.RoundButton</item>`。你可以自己对 Button 设置 `singleLine="fales"` 即可。

啊，解决了，感谢！
