### ISSUE TITLE
使用MessageDialogBuilder的时候无法显示确定取消按钮

### ISSUE THREAD

**Issue by tx123456** [Tencent/QMUI_Android#460]
### 运行环境 ###

- [x] 设备型号：如：`mi mix2s`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `3.2.0`
- [x] QMUI Android 版本：`1.1.7`

### 具体问题描述 ###
使用MessageDialogBuilder创建对话框的时候无法出现取消确定按钮

#### 问题截图 ####

![image](https://user-images.githubusercontent.com/14331075/49955755-981ea300-ff3e-11e8-9c49-fdfe2788d59f.png)

![image](https://user-images.githubusercontent.com/14331075/49955792-ac62a000-ff3e-11e8-8bac-3a341d619e73.png)

**Comment by cgspine** [comment]
看样子是字体颜色为白色了， 用 Layout Inspector 检查下？然后检查下R.style.QMUI_Dialog 的 qmui_dialog_action_style
