### ISSUE TITLE
滑动返回，滑动到一定程度（概率性），松开会闪退

### ISSUE THREAD

**Issue by kakarrot** [Tencent/QMUI_Android#461]
### 下载最新 1.1.7 apk 运行 ###

- [x] 设备型号：：`360 N6 Pro`
- [x] 设备系统版本： `Android 8.0`

**Comment by qfxl** [comment]
> 最新的 1.1.7 apk 是有这个问题， 后来新版本好像是修复了，试试新版本

运行代码之后没有发现，看提交记录应该是修复了。
