### ISSUE TITLE
 android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.qmuiteam.qmui.widget.dialog.QMUIDialogView     Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.qmuiteam.qmui.widget.dialog.QMUIDialogView     Caused by: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by 985211yygg** [Tencent/QMUI_Android#465]
### 运行环境 ###

- [x] 设备型号：如：`pixel  xl`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `3.2.0`
- [x] QMUI Android 版本：`1.1.3`

### 具体问题描述 ###
   android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class com.qmuiteam.qmui.widget.dialog.QMUIDialogView
    Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.qmuiteam.qmui.widget.dialog.QMUIDialogView
    Caused by: java.lang.reflect.InvocationTargetException

**Comment by Evatruy** [comment]
同样遇到此问题，低版本不会出现。有解决方法共享下，谢谢

**Comment by cgspine** [comment]
检查下 Activity 的 theme? 这种错误只可能是 theme 错误。

**Comment by CrazeLZQ** [comment]
遇到这种问题我已知的情况有两种，1、一种就是主题没有使用他们的QMUI.Compat.* 2、还有一种就是弹窗dialog的context有问题。建议调试一下context用的是不是application的
