### ISSUE TITLE
RWidgetHelper了解一下

### ISSUE THREAD

**Issue by RuffianZhong** [Tencent/QMUI_Android#467]
我也一直在致力于搞一个：Android UI 快速开发，专治原生控件各种不服  的开源项目

[RWidgetHelper](https://github.com/RuffianZhong/RWidgetHelper)

全网搜索了一下，原来大厂也在搞这个，搞不过，只能来这里打一下广告这样子，哈哈哈

**Comment by Theoneee** [comment]
没有什么搞得过搞不过，只有哪个更好用，能把QMUI拥有太多的功能，但是又不是每个都是最好的，合力把它做好，少一点集成不是更好吗。

**Comment by RuffianZhong** [comment]
@Theoneee 
我是说流量搞不过，所以特来打一下广告，给有需要的人
![Uploading image.png…]()

**Comment by chanthuang** [comment]
都是为了方便 Android UI 开发，一起交流，欢迎贡献。
