### ISSUE TITLE
官网上的“当前版本”能否与时俱进？

### ISSUE THREAD

**Issue by XinwenCheng** [Tencent/QMUI_Android#469]
官网上的“当前版本”总是更新得比较迟缓，真正的当前版本需要在官网给出的版本号上自行往上加，加到同步失败的时候为止（有时候Gradle会提示最新版本）。

比如，当前已经发布到V1.1.10了，而官网上还是V1.1.7。之前明明已经发布到了V1.1.7，而官网上还是V1.1.4。

如下：
![image](https://user-images.githubusercontent.com/795334/50260549-68dacb00-0443-11e9-8b01-3ca4b2570cd8.png)
![image](https://user-images.githubusercontent.com/795334/50260564-7a23d780-0443-11e9-86f8-2d5b5c14deb2.png)

**Comment by chanthuang** [comment]
感谢反馈。
官网确实有更新迟缓的问题，我们会改进，及时更新官网。另外，也可以在 Github 的 [release](https://github.com/Tencent/QMUI_Android/releases) 中看到当前的最新可用版本。

**Comment by XinwenCheng** [comment]
> 感谢反馈。
> 官网确实有更新迟缓的问题，我们会改进，及时更新官网。另外，也可以在 Github 的 [release](https://github.com/Tencent/QMUI_Android/releases) 中看到当前的最新可用版本。

哦对，release也可以看到。不过还是建议直接更新官网版本号。谢谢！
