### ISSUE TITLE
QDQQFaceView 添加QMUITouchableSpan 换行显示，换行后的部分点击不能回调onSpanClick

### ISSUE THREAD

**Issue by Ramblerchris** [Tencent/QMUI_Android#473]
### 运行环境 ###

- [x] 设备型号：如：`Pixel XL`
- [x] 设备系统版本：如 `Android 8.1`
- [x] Gradle 版本：如 `4.6.0`
- [x] QMUI Android 版本：`1.1.10`

### 具体问题描述 ###
QDQQFaceView 添加QMUITouchableSpan 换行显示，换行后的部分点击不能回调onSpanClick
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/10184291/50548591-83564500-0c8a-11e9-9cf7-096d2f42dc91.png)

**Comment by cgspine** [comment]
请升级到 1.1.10

**Comment by Ramblerchris** [comment]
完美解决，给力！[Smirk]
