### ISSUE TITLE
QMUIFragment的onSaveInstanceState执行后crash

### ISSUE THREAD

**Issue by szhangbiao** [Tencent/QMUI_Android#474]
### 运行环境 ###

- [x] 设备型号：如：`Samsung(SM-G960U)`
- [x] 设备系统版本：如 `Android 8.0.0`
- [x] Gradle 版本：如 `3.2.1`
- [x] QMUI Android 版本：`1.1.10` 

### 具体问题描述 ###
线上报的这个bug比较多arch版本是0.2.2
#### 异常日志（堆栈） ####
ArrayList.java:437java.util.ArrayList.get	
ViewGroup.java:7029android.view.ViewGroup.clearDisappearingChildren	
ViewGroup.java:3880android.view.ViewGroup.dispatchDetachedFromWindow	
ViewGroup.java:3878android.view.ViewGroup.dispatchDetachedFromWindow	
ViewGroup.java:3878android.view.ViewGroup.dispatchDetachedFromWindow	
ViewGroup.java:3878android.view.ViewGroup.dispatchDetachedFromWindow	
ViewGroup.java:7142android.view.ViewGroup.endViewTransition	
SourceFile:588com.qmuiteam.qmui.arch.SwipeBackLayout.clearAnimation	
SourceFile:2655android.support.v4.app.FragmentManagerImpl.endAnimatingAwayFragments	
SourceFile:2913android.support.v4.app.FragmentManagerImpl.saveAllState	
SourceFile:128android.support.v4.app.FragmentController.saveAllState	
SourceFile:566android.support.v4.app.FragmentActivity.onSaveInstanceState	
SourceFile:509android.support.v7.app.AppCompatActivity.onSaveInstanceState	
SourceFile:53com.qmuiteam.qmui.arch.QMUIFragmentActivity.onSaveInstanceState	
Activity.java:1555android.app.Activity.performSaveInstanceState	
Instrumentation.java:1392android.app.Instrumentation.callActivityOnSaveInstanceState	
ActivityThread.java:4941android.app.ActivityThread.callCallActivityOnSaveInstanceState	
ActivityThread.java:4229android.app.ActivityThread.performStopActivityInner	
ActivityThread.java:4288android.app.ActivityThread.handleStopActivity	
Unknownandroid.app.ActivityThread.-wrap25	
ActivityThread.java:1730android.app.ActivityThread$H.handleMessage	
Handler.java:105android.os.Handler.dispatchMessage	
Looper.java:164android.os.Looper.loop	
ActivityThread.java:6938android.app.ActivityThread.main	
Method.java:-2java.lang.reflect.Method.invoke	
Zygote.java:327com.android.internal.os.Zygote$MethodAndArgsCaller.run	
ZygoteInit.java:1374com.android.internal.os.ZygoteInit.main

**Comment by cgspine** [comment]
可升级到 0.3.0。 这个bug应该算是 fragmentManager 框架的内部bug，之前采取的 hack 方式来修复，但是效果不理想，现在 support library 28 已经修复了这个bug，因此 arch 去掉了之前的hack, 所以使用者需要升级 support library 到 28 或 使用 androidx.
