### ISSUE TITLE
下拉刷新的时候 刷新头header 可否向下偏移一定距离？

### ISSUE THREAD

**Issue by mrme2014** [Tencent/QMUI_Android#476]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
setTargetRefreshOffset ? 或者 setRefreshOffsetCalculator 自定义 refreshView 的位置？

**Comment by mrme2014** [comment]
addRefreshView 方法既然为 private，又暴露出接口 有何意义呢？
------------------------------------------------------------------
发件人：cgspine <notifications@github.com>
发送时间：2019年1月2日(星期三) 20:14
收件人：Tencent/QMUI_Android <QMUI_Android@noreply.github.com>
抄　送：宋余保(体面) <yubao.syb@alibaba-inc.com>; Author <author@noreply.github.com>
主　题：Re: [Tencent/QMUI_Android] 下拉刷新的时候 刷新头header 可否向下偏移一定距离？ (#476)

setTargetRefreshOffset ? 或者 setRefreshOffsetCalculator 自定义 refreshView 的位置？

**Comment by mrme2014** [comment]
> 有给子类暴露 createRefreshView 方法的

恩。。。这个好解决。。。，配合recyclerview 下拉，正在刷新，手指继续向下滑动一点距离不抬起，当刷新完成调用finishRefresh()后，会再次自动下滑出刷新头
