### ISSUE TITLE
你们有遇到QMUISegment+ViewPager滑动后图片显示延迟吗

### ISSUE THREAD

**Issue by Theoneee** [Tencent/QMUI_Android#479]
### 运行环境 ###

- [x] 设备型号：如：`Meizu 16th`
- [x] 设备系统版本：如 `Android 8.1`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.1.10`

### 具体问题描述 ###

滑动过后，文字颜色已经变了，但是图片要过一会才变成选中图片。。

**Comment by cgspine** [comment]
如果选中态是换图片，而不是采用tintColor，图片是滚动完成后瞬间切换的，随意相对文字，感觉会有点延迟。

**Comment by zqd123** [comment]
我的是努比亚手机，确实也有延迟现象

**Comment by dxpbloom** [comment]
解决了没有？@cgspine

**Comment by cgspine** [comment]
图片切换时瞬时完成的，所以会感觉卡，1.x不会更改这个；目前主干已经重构了这个组件，但是现在还有未完成的工作，所以还没发布2.0
