### ISSUE TITLE
fragment嵌套fragment白屏

### ISSUE THREAD

**Issue by jiachengliu** [Tencent/QMUI_Android#480]
### 运行环境 ###

- [x] 设备型号：如：`小米note3`
- [x] 设备系统版本：如 `Android 6.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.1.11`

### 具体问题描述 ###
fragment长时间在后台，然后再切换到前台，之前打开的fragment会是白屏（demo里QDFitSystemWindowViewPagerFragment页面可以重现这个问题）若想快速重现，可在手机的 “设置” - “开发者选项” - 打开”不保留活动”。这样就不需要长时间在后台了。

#### 问题截图 ####
![1981546943233_ pic_hd](https://user-images.githubusercontent.com/12412647/50825165-50d7d680-1373-11e9-9745-d12ba4e86dd4.jpg)

**Comment by jiachengliu** [comment]
QMUIPagerAdapter 里面方法populate()，有个makeFragmentName(container.getId(), position); 我把几个子fragment的布局改为不同的(之前是用同一个xml)就不会有这个问题了。但是长时间在后台，无论之前在第几个页面，再切回来后还是第一个页面了，像是重新打开的APP。demo里QDFitSystemWindowViewPagerFragment也是这样的。难道是QMUIPagerAdapter的问题吗

**Comment by cgspine** [comment]
restore 时 hydrate 和 populate 使用的不是同一个 fragment 导致的

**Comment by szhangbiao** [comment]
我也遇到了这个bug，请问怎么解决呢

**Comment by cgspine** [comment]
可以看看 982b80f 这个提交
