### ISSUE TITLE
QMUIRoundButton 

### ISSUE THREAD

**Issue by Theoneee** [Tencent/QMUI_Android#492]
app:qmui_backgroundColor="@color/qmui_config_color_red"

    这里属性在Java代码里就没法再改了，有办法动态的修改吗。

我想实现圆形的TextView,动态的设置背景颜色，中间就显示个文字。

**Comment by Theoneee** [comment]
`   <com.qmuiteam.qmui.widget.roundwidget.QMUIRoundButton
        android:id="@+id/tv_name"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:textColor="@color/qmui_config_color_white"
        app:qmui_backgroundColor="@color/qmui_config_color_red"
        android:textSize="@dimen/sp_16"
        app:qmui_borderWidth="0dp"
        android:text="事"/>
`

我xml里这样写了就能实现，可是没办法改变背景颜色。

**Comment by chanthuang** [comment]
`
QMUIRoundButton button = (QMUIRoundButton) findViewById(R.id.tv_name);
QMUIRoundButtonDrawable bg = (QMUIRoundButtonDrawable) button.getBackground();
bg.setColor(YourNewColor);
`

**Comment by Theoneee** [comment]
非常感谢~
