### ISSUE TITLE
tab滑动切换的时候白屏

### ISSUE THREAD

**Issue by zhangxinars** [Tencent/QMUI_Android#494]
### 运行环境 ###

- [x] 设备型号：如：`Honor 7X`
- [x] 设备系统版本：如 `Android 8.0.0`
- [x] Gradle 版本：如 `4.10.1`
- [x] QMUI Android 版本：`1.1.7`

### 具体问题描述 ###
HomeFragment的两个tab，在滑动切换的时候，如果先向下滑，再右滑，就会出现左侧白屏并闪退

**Comment by cgspine** [comment]
往右滑？有使用 arch 吗？ 感觉像触发了手势返回。arch 非最新版没有做好保护，需要手动将HomeFragment  的 canDragBack 设为 false

**Comment by zhangxinars** [comment]
![image](https://user-images.githubusercontent.com/14805008/51523273-47b43280-1e66-11e9-80c0-241cc4ab909f.png)
是这样设置吗，已设置但没有效果

**Comment by zhangxinars** [comment]
已解决，多谢，由于我HomeFragmet中hydrate返回的是new Fragment()，在该Fragment中 canDragBack 设为 false就行了。
