### ISSUE TITLE
QMUIGroupListView.Section 中 没有示例代码中的mLeftIconWidth 和 mLeftIconHeight属性，无法控制图片大小

### ISSUE THREAD

**Issue by nobita0522** [Tencent/QMUI_Android#496]
示例代码：
 public static class Section {
        private Context mContext;
        private QMUIGroupListSectionHeaderFooterView mTitleView;
        private QMUIGroupListSectionHeaderFooterView mDescriptionView;
        private SparseArray<QMUICommonListItemView> mItemViews;
        private boolean mUseDefaultTitleIfNone;
        private boolean mUseTitleViewForSectionSpace = true;

        private int mSeparatorDrawableForSingle = 0;
        private int mSeparatorDrawableForTop = 0;
        private int mSeparatorDrawableForBottom = 0;
        private int mSeparatorDrawableForMiddle = 0;
        private int mLeftIconWidth = ViewGroup.LayoutParams.WRAP_CONTENT;
        private int mLeftIconHeight = ViewGroup.LayoutParams.WRAP_CONTENT;

        public Section(Context context) {
            mContext = context;
            mItemViews = new SparseArray<>();
        }

引用包内代码：
  public static class Section {
        private Context mContext;
        private QMUIGroupListSectionHeaderFooterView mTitleView;
        private QMUIGroupListSectionHeaderFooterView mDescriptionView;
        private SparseArray<QMUICommonListItemView> mItemViews;
        private boolean mUseDefaultTitleIfNone;
        private boolean mUseTitleViewForSectionSpace = true;

        private int mSeparatorDrawableForSingle = 0;
        private int mSeparatorDrawableForTop = 0;
        private int mSeparatorDrawableForBottom = 0;
        private int mSeparatorDrawableForMiddle = 0;

        public Section(Context context) {
            mContext = context;
            mItemViews = new SparseArray<>();
        }

**Comment by cgspine** [comment]
引用包 qmui 版本不够高？

**Comment by nobita0522** [comment]
> 引用包 qmui 版本不够高？

1.1.3不是最新的？

**Comment by nobita0522** [comment]
> 引用包 qmui 版本不够高？

在Demo内的QMUIGroupListView 里面有一个如果左侧设置图片，然后可以设置图片大小的方法，也存在 private int mLeftIconWidth = ViewGroup.LayoutParams.WRAP_CONTENT;
    private int mLeftIconHeight = ViewGroup.LayoutParams.WRAP_CONTENT; 但是在引用的包内就没有了

**Comment by nobita0522** [comment]
> 引用包 qmui 版本不够高？

刚刚更新到了1.1.12，没这个问题了.
