### ISSUE TITLE
为什么不弄个夜间模式的样式呢？

### ISSUE THREAD

**Issue by zhouzhuo810** [Tencent/QMUI_Android#501]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by MoLice** [comment]
QMUI 不参与设计环节，具体的设计效果应该由项目自身决定。

**Comment by zhouzhuo810** [comment]
我现在用QMUIGroupListView想实现夜间模式；可是我自定义各种属性好像都无法改变QMUICommonListItemView的背景；请问应该如何处理？

**Comment by zhouzhuo810** [comment]
好的谢谢
