### ISSUE TITLE
下载后工程跑不起来

### ISSUE THREAD

**Issue by Jetgege** [Tencent/QMUI_Android#502]
### 具体问题描述 ###
下载后工程跑不起来
#### 问题截图 ####

![image](https://user-images.githubusercontent.com/19191893/52044891-2e099e00-257e-11e9-8232-a64bf3a08a05.png)

**Comment by chanthuang** [comment]
见 [wiki Q&A](https://github.com/Tencent/QMUI_Android/wiki/QMUI-Q-&-A)
