### ISSUE TITLE
QMUIDialogAction

### ISSUE THREAD

**Issue by haonan1** [Tencent/QMUI_Android#503]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.1.12`

### 具体问题描述 ###

QMUIDialog 在构建的时候，创建多个Action，需要对没一个Action背景做设置，是否支持

**Comment by chanthuang** [comment]
见 `QMUIDialogBuilder#addAction(QMUIDialogAction)` 方法，以及 `QMUIDialogAction#generateActionButton(Context, Charsequence, int)` 方法。你可以继承 QMUIDialogAction 实现自己的 Action，并 override generateActionButton 方法，对 View 添加额外的样式。

**Comment by haonan1** [comment]
QMUIDialogAction 里面的generateActionButton 是一个私有的方法

**Comment by haonan1** [comment]
还有一个使用中的问题，QMUIGroupListView 在使用中如何自定义Head头部布局

**Comment by chanthuang** [comment]
应该是 override buildActionView 方法。另一种自定义 Action 背景的方法是定义自己的 DialogStyle，参考 QMUIDemo 中的 styles.xml：
```
<style name="DialogTheme2" parent="QMUI.Dialog">
        <!-- something else -->
        <item name="qmui_dialog_action_style">@style/DialogTheme2ActionStyle</item>
        <!-- something else -->
</style>

<style name="DialogTheme2ActionStyle">
        <!-- something else -->
        <item name="android:background">@null</item>
        <!-- something else -->
</style>
```

**Comment by chanthuang** [comment]
QMUIGroupListView 实际上只是一个 LinearLayout，将其和 HeaderView 一起放在 ScrollView 中即可
