### ISSUE TITLE
QMUISegment

### ISSUE THREAD

**Issue by Theoneee** [Tencent/QMUI_Android#508]
### 运行环境 ###

- [x] 设备型号：MEIZU 16th
- [x] 设备系统版本：8.1
- [x] Gradle 版本：
- [x] QMUI Android 版本：1.1.12

### 具体问题描述 ###

左右滑动图片选中有延迟，以前是没有这个情况的。

#### 问题截图 ####
![8d5ac4ea-ea39-46e7-8a6e-5e8ffbf1b504](https://user-images.githubusercontent.com/32156330/52773160-45b04e80-3075-11e9-8560-bf77e0d4523e.gif)

**Comment by Theoneee** [comment]
就是从1.1.10版本开始的。

Refactored QMUITabSegment to handle operations such as reducing item.

**Comment by Theoneee** [comment]
QMUIFragmentA 包含 QMUISegment+ViewPager
ViewPager里的QMUIFragmentB也包含QMUISegment2+ViewPager2
ViewPager2里的Frgment里是一个Rc,点击Item以QMUIFragmentA跳转到QMUIFragmentC
关闭QMUIFragmentC后，QMUISegment2+ViewPager2滑动这俩都卡顿一下，卡一下之后又好了。

**Comment by Theoneee** [comment]
![9b90e384-a3ca-47f4-9d27-cbe63f512abf](https://user-images.githubusercontent.com/32156330/52774783-0edc3780-3079-11e9-92c0-c5801dd4816b.gif)

**Comment by Theoneee** [comment]
如果 QMUIFragmentA  QMUIFragmentC是Activity ,滑动返回也不会出现卡顿。

**Comment by cgspine** [comment]
左右滑动图片延迟是因为图片是瞬间修改的，以前是在滚动过程中就修改了，会存在问题，现在是非滚动时才修改，因此看上去比之前延迟了。下个版本会改为两张图片 alpha 变化来解决这个问题。

**Comment by cgspine** [comment]
卡顿的问题我查查看

**Comment by Theoneee** [comment]
@cgspine 如果QMUIFragmentB里没有进行滑动就直接跳转到QMUIFragmentC，滑动返回时不会卡顿的。QMUIFragmentC点击返回按钮也不会，只有滑动返回才会。

**Comment by dxpbloom** [comment]
卡顿的问题解决了吗？

**Comment by cgspine** [comment]
修复了，可更新arch版本到0.5.0
