### ISSUE TITLE
Fragment滑动返回动画异常

### ISSUE THREAD

**Issue by nobita0522** [Tencent/QMUI_Android#509]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 5`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `3.3.0`
- [x] QMUI Android 版本：`1.12.0`

### 具体问题描述 ###
fragment_1 调用 startFragment（fragment_2）之后，fragment_2 调用startFragmentAndDestroyCurrent(fragment_3) 在fragment_3 滑动返回fragment_1 时,左侧和右侧动画异常

#### 问题截图 ####
正常情况截图

![normal](https://user-images.githubusercontent.com/24804777/52835292-cf692600-3120-11e9-8799-ab4c4b6a46b0.gif)

异常情况截图
![unnormal](https://user-images.githubusercontent.com/24804777/52835307-de4fd880-3120-11e9-8f04-0ff9c5a11087.gif)

#### 异常日志（堆栈） ####
无异常日志

**Comment by cgspine** [comment]
你的手机上，QMUIDemo -> QMUIFragment ->startFragment ->  startFragmentAndDestroyCurrent 也会这样吗？

**Comment by nobita0522** [comment]
QMUIDemo项目不会这样，怎么回事呢

**Comment by nobita0522** [comment]
QMUIDemo项目，滑动返回时不会这样，但是在startFragmentAndDestroyCurrent(fragment_3)的时候，没有进入fragment_3的动画效果了。

**Comment by nobita0522** [comment]
其他的fragment 进行startFragmentAndDestroyCurrent后并不会出现异常，但图示的就会出现，可是图示那几个fragment并没有重写任何关于滑动返回以及动画定义的代码，均和正常的fragment一样，只存在逻辑代码。

**Comment by nobita0522** [comment]
问题原因已定位，当在controller内（以homeController为例）调用startFragment -> startFragmentAndDestroyCurrent -> 以及startFragment时,就会出现这样的问题。QMUIDemo也会有这样的问题,望尽快修复

异常截图：
![unnormal](https://user-images.githubusercontent.com/24804777/52896508-10863680-3204-11e9-872b-c1f3c387e7cb.gif)

**Comment by cgspine** [comment]
Demo 里无动画的问题修复了，可是手势返回的问题，我这边手机也不能复现，最新代码我加了点log，麻烦看看你的手机的表现？

这个表现应该是 mBackStackIndex 的错误，你上面在222 startFragmentAndDestroy，然后手势返回，mBackStackIndex 应当是下面这样：

![image](https://user-images.githubusercontent.com/7828876/52929020-7d710c00-337d-11e9-89f4-a0851e893e8e.png)

**Comment by nobita0522** [comment]
好像我没表达清楚，我重新表达一下啊。
首先说一下流程:按照QMUIdemo中，首先进入homeFragment，然后渲染pager中的3个视图，分别是home,helper,lab,这三个均是继承自QMUIWindowInsetLayout的controller，然后触发点击事件进入指定的fragment.再进行startFragment -> startFragmentAndDestroyCurrent 才会出现bug。我出现bug的流程是这样的,:
启动APP，进入homeFragment -> 点击homeController  -> 进入fragment1 -> fragment1.startFragment(new Fragement2())进入fragment2 -> fragment2.startFragmentAndDestroyCurrent(new Fragement3())进入fragment3.
此时从framgent3 拖动返回,就会出现截图的异常。
之前回答的截图中，我在topbar的右侧添加了文字按钮，为了方便标识是哪一个fragment。
我重新截图：

![unnormal](https://user-images.githubusercontent.com/24804777/52932498-e0b56b00-338a-11e9-8ca7-fe37fdefc686.gif)


首先进入了homeFragment ,只有pager 和 segment , 默认显示的是 “首页”这个controller，点击进入fragment1 -> fragment1.startFragment(new Fragement2())进入fragment2 -> fragment2.startFragmentAndDestroyCurrent(new Fragement3())进入fragment3.再从fragment3滑动返回fragment1即如图所示异常情况

**Comment by cgspine** [comment]
我理解没错， homeFragment mBackStackIndex = 0; 
startFragment 进入 fragment1， mBackStackIndex = 1；
fragment1.startFragment(new Fragement2())进入fragment2， mBackStackIndex = 2;
fragment2.startFragmentAndDestroyCurrent(new Fragement3())进入fragment3，mBackStackIndex = 2;
手势返回开始， mBackStackIndex = 1;
手势返回就结束，mBackStackIndex = 1;

可能与 Android 7 有关系，我找找 Android 7 的 nexus 手机看看

**Comment by nobita0522** [comment]
测试了下，如果只是单纯的fragment之间的切换，是不会出现这样的bug的.但fragment中嵌套了controller再切换fragment才会出现的这bug

**Comment by cgspine** [comment]
我测试了 自定义 View 的 controller， 和child fragment 的 controller， 都没出现，用 Nexus 5X Android 7 也不行， 神奇

**Comment by nobita0522** [comment]
这样做就可以重现：
在HomeController的initTopBar()中添加
        mTopBar.addRightImageButton(R.mipmap.icon_topbar_about, R.id.topbar_right_about_button).setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View view) {
//                QDAboutFragment fragment = new QDAboutFragment();
                TestFragment testFragment = new TestFragment();
                startFragment(testFragment);
            }
        });
TestFragment.java 和 QDAboutFragment.java 代码一模一样,只需要复制一个就可以了,为了区别，
在testFragment.java的initTopBar()方法中;
        mTopBar.addRightTextButton("这是fragment1",R.id.qmui_tab_segment_item_id).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startFragment(new Test2Fragment());
            }
        });
同理,Tes2Fragment.java 和 QDAboutFragment.java 代码一模一样,只需要复制一个就可以了,为了区别，
在testFragment.java的initTopBar()方法类;
        mTopBar.addRightTextButton("这是fragment12",R.id.qmui_tab_segment_item_id).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startFragmentAndDestroyCurrent(new Test2Fragment());
            }
        });
同理,Tes3Fragment.java 和 QDAboutFragment.java 代码一模一样,只需要复制一个就可以了,为了区别，
在testFragment.java的initTopBar()方法类;
        mTopBar.addRightTextButton("这是fragment12",R.id.qmui_tab_segment_item_id).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //do nothing
            }
        });
这样,在homeComponentscontroller 的右上角就会多一个 图标，点击即可进入testFragment，然后就可以重现一模一样的步骤了

**Comment by nobita0522** [comment]
这样做就可以重现：
在HomeController的initTopBar()中添加
mTopBar.addRightImageButton(R.mipmap.icon_topbar_about, R.id.topbar_right_about_button).setOnClickListener(new OnClickListener() {
@override
public void onClick(View view) {
// QDAboutFragment fragment = new QDAboutFragment();
TestFragment testFragment = new TestFragment();
startFragment(testFragment);
}
});

TestFragment.java 和 QDAboutFragment.java 代码一模一样,只需要复制一个就可以了,为了区别，在testFragment.java的initTopBar()方法中;
mTopBar.addRightTextButton("这是fragment1",R.id.qmui_tab_segment_item_id).setOnClickListener(new View.OnClickListener() {
@override
public void onClick(View v) {
startFragment(new Test2Fragment());
}
});

同理,Tes2Fragment.java 和 QDAboutFragment.java 代码一模一样,只需要复制一个就可以了,为了区别，
在testFragment.java的initTopBar()方法类;
mTopBar.addRightTextButton("这是fragment12",R.id.qmui_tab_segment_item_id).setOnClickListener(new View.OnClickListener() {
@override
public void onClick(View v) {
startFragmentAndDestroyCurrent(new Test2Fragment());
}
});

同理,Tes3Fragment.java 和 QDAboutFragment.java 代码一模一样,只需要复制一个就可以了,为了区别，
在testFragment.java的initTopBar()方法类;
mTopBar.addRightTextButton("这是fragment12",R.id.qmui_tab_segment_item_id).setOnClickListener(new View.OnClickListener() {
@override
public void onClick(View v) {
//do nothing
}
});

这样,在homeComponentscontroller 的右上角就会多一个 图标，点击即可进入testFragment，然后就可以重现一模一样的步骤了

**Comment by nobita0522** [comment]
这样做就可以重现：
在HomeController的initTopBar()中添加
mTopBar.addRightImageButton(R.mipmap.icon_topbar_about, R.id.topbar_right_about_button).setOnClickListener(new OnClickListener() {
@override
public void onClick(View view) {
// QDAboutFragment fragment = new QDAboutFragment();
TestFragment testFragment = new TestFragment();
startFragment(testFragment);
}
});

TestFragment.java 和 QDAboutFragment.java 代码一模一样,只需要复制一个就可以了,为了区别，在testFragment.java的initTopBar()方法中;
mTopBar.addRightTextButton("这是fragment1",R.id.qmui_tab_segment_item_id).setOnClickListener(new View.OnClickListener() {
@override
public void onClick(View v) {
startFragment(new Test2Fragment());
}
});

同理,Tes2Fragment.java 和 QDAboutFragment.java 代码一模一样,只需要复制一个就可以了,为了区别，
在testFragment.java的initTopBar()方法类;
mTopBar.addRightTextButton("这是fragment2",R.id.qmui_tab_segment_item_id).setOnClickListener(new View.OnClickListener() {
@override
public void onClick(View v) {
startFragmentAndDestroyCurrent(new Test2Fragment());
}
});

同理,Tes3Fragment.java 和 QDAboutFragment.java 代码一模一样,只需要复制一个就可以了,为了区别，
在testFragment.java的initTopBar()方法类;
mTopBar.addRightTextButton("这是fragment3",R.id.qmui_tab_segment_item_id).setOnClickListener(new View.OnClickListener() {
@override
public void onClick(View v) {
//do nothing
}
});

这样,在homeComponentscontroller 的右上角就会多一个 图标，点击即可进入testFragment，然后就可以重现一模一样的步骤了

**Comment by nobita0522** [comment]
估计是我踩到了什么鬼坑。。。。。。。。。。。

**Comment by cgspine** [comment]
startFragmentAndDestroyCurrent 传入的 Fragment 与前一个名字不相同才会出现这个现象，现在修复了，试试 arch 0.3.2

**Comment by nobita0522** [comment]
感谢，以修复。
