### ISSUE TITLE
QMUIFragment  懒加载支持不啊，大佬·~

### ISSUE THREAD

**Issue by Theoneee** [Tencent/QMUI_Android#512]
- -！  这个功能应该有必要，自己写太。。。

**Comment by cgspine** [comment]
https://juejin.im/post/5b149469f265da6e3423aefe

这种使用场景吗？应该就只有 ViewPager 下有应用场景吧

**Comment by Theoneee** [comment]
是啊，我现在的首页是像微信那种左右可以滑动的。用的就是ViewPager，第一个Fragment和第二个也是Tab+ViewPager,这种情况一下加载的就有点多了。。。

**Comment by Theoneee** [comment]
恩，你说的那个我也看了。只是觉得这个功能挺有用了。QMUIFrament有还是好一点。谢谢大佬回复~~

**Comment by cgspine** [comment]
发布了 0.4.0。 通过 `getLazyViewLifecycleOwner().getLifecycle()` 可以获取修改后的 lifecycle。 依赖了 `getViewLifecycleOwner`，因此只支持 support 28

**Comment by Theoneee** [comment]
28强制了 https ，刚遇到这个降低了。。。 @cgspine

**Comment by cgspine** [comment]
https://developer.android.com/training/articles/security-config

可以添加 security-config，用 cleartextTrafficPermitted 来使用 http 的

**Comment by Theoneee** [comment]
看了很久，不会用。。。。

**Comment by Theoneee** [comment]
@cgspine  - -！！！

**Comment by Theoneee** [comment]
` mLazyViewLifecycleOwner = new QMUIFragmentLazyLifecycleOwner(this);` 
 `  mLazyViewLifecycleOwner.setViewVisible(getUserVisibleHint());` 
 `  getViewLifecycleOwner().getLifecycle().addObserver(mLazyViewLifecycleOwner);` 


QMUIFragmentLazyLifecycleOwner这个里面的回调是一个 

    `@Override `
    ` public boolean isVisibleToUser() { `
        ` return getUserVisibleHint() && isParentVisibleToUser(); `
    `}`

**Comment by Theoneee** [comment]
@OnLifecycleEvent(Lifecycle.Event.ON_CREATE)
    void onCreate(LifecycleOwner owner) {
        mIsViewVisible = mCallback.isVisibleToUser();
        mViewState = Lifecycle.State.CREATED;
        handleLifecycleEvent(Lifecycle.Event.ON_CREATE);
    }

    @OnLifecycleEvent(Lifecycle.Event.ON_START)
    void onStart(LifecycleOwner owner) {
        mViewState = Lifecycle.State.STARTED;
        if (mIsViewVisible) {
            handleLifecycleEvent(Lifecycle.Event.ON_START);
        }
    }

    @OnLifecycleEvent(Lifecycle.Event.ON_RESUME)
    void onResume(LifecycleOwner owner) {
        mViewState = Lifecycle.State.RESUMED;
        if (mIsViewVisible && mLifecycleRegistry.getCurrentState() == Lifecycle.State.STARTED) {
            handleLifecycleEvent(Lifecycle.Event.ON_RESUME);
        }
    }

好像在直接就有了。。。

**Comment by Theoneee** [comment]
@Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        mLazyViewLifecycleOwner = new QMUIFragmentLazyLifecycleOwner(this);
        mLazyViewLifecycleOwner.setViewVisible(getUserVisibleHint());
        getViewLifecycleOwner().getLifecycle().addObserver(mLazyViewLifecycleOwner);
    }

这里不是已经new 了嘛。还是报Can't access the QMUIFragment View's LifecycleOwner when "
                    + "getView() is null i.e., before onViewCreated() or after onDestroyView()..
我点开 getViewLifecycleOwner 这个方法是红色的。

**Comment by cgspine** [comment]
在 `onActivityCreated` 里调用：
`getLazyViewLifecycleOwner().getLifecycle().addObserver(new QDLazyTestObserver("QDViewPager"));`

其行为只是更改了 Observer 的 onStart - onStop 的调用时机。  你应该实现自己的 Observer，可以参考 QDLazyTestObserver， onStart/onResume 才去请求数据

**Comment by Theoneee** [comment]
这样的写法比普通的那种写法（Fragmention里的懒加载都没看懂怎么做的。。。）有什么好处吗。。。这种不兼容低版本啊。。而且使用方法很麻烦，对新手不太好。不像Fragmention里直接重写一个方法就可以了。。。 = =

**Comment by Theoneee** [comment]
@cgspine

**Comment by cgspine** [comment]
我觉得这是趋势， lifecycle 必定会成为主流。一个方法虽然方便，但考虑这样一种情况：发出请求 -> 数据还没回来就切换到第二个 page -> 这个时候数据回来了要不要立刻渲染到 View 上？ 如果只有一个方法，那必定会渲染到 View 上吧， 因为 fragment 不可见，但依旧还没有 onStop。 这种场景一样会造成离屏渲染操作。

LiveData + lifecycle 是就能很好处理这种情况了， 数据回来了，LiveData 并不会立刻通知 view 更新，而是等到其再次 onResume 时更新到 view 上。我提供的这个方式就可以适配 LiveData 去使用。

如果期望只有一个方法，那可以在业务基类实现以下：
![image](https://user-images.githubusercontent.com/7828876/53617405-06136600-3c22-11e9-9461-753a47179058.png)

Fragmention 的实现在 fragmentation/helper/internal/VisibleDelegate.java，实现思路应该是一样的

**Comment by Theoneee** [comment]
Soga。 我要去好好学习这些知识点了。谢谢大佬的解释~~      
对了，对于您2018年的总结最后一点我深有感受。
没有什么感同身受，只有同病相怜罢了。
