### ISSUE TITLE
QMUICommonListItemView一点改进建议

### ISSUE THREAD

**Issue by nobita0522** [Tencent/QMUI_Android#514]
当QMUICommonListItemView ACCESSORY_TYPE 为 ACCESSORY_TYPE_SWITCH,通过addItemView（itemview，listener） 绑定的监听就会无效，其他类型都可以，目前实测ACCESSORY_TYPE_SWITCH类型的QMUICommonListItemView好像只能通过.getSwitch.setOnCheckedChangeListener 来添加状态switch改变的listener.
希望可以改成都是通过addItemView（itemview，listener）时添加listener。

**Comment by chanthuang** [comment]
这是因为当 accessory type 为 `ACCESSORY_TYPE_SWITCH` 时，item 的点击事件已被用来改变 switch 控件的状态（见 [addItemView 方法](https://github.com/Tencent/QMUI_Android/blob/master/qmui/src/main/java/com/qmuiteam/qmui/widget/grouplist/QMUIGroupListView.java#L261)）

请问在这种 switch 类型的 item 上，你是否确实还有需要额外地监听其点击事件去做其他事情？

**Comment by nobita0522** [comment]
实际应用如下：
目前该情况的操作
有些开关应用在打开和关闭的时候是需要联网操作的,我想的是实现如图那样的操作

![req](https://user-images.githubusercontent.com/24804777/53159827-9ab60c80-3601-11e9-8c1a-b46213f0e267.gif)


用户点击了“就诊提醒”，然后发送网络请求到达服务器,此时将ItemView 的 ACCESSORY_TYPE 改为自定义的loading状态,等待服务器回传结果,然后根据结果控制switich的状态,但是由于setOnCheckedChangeListener方法是状态已经改变过才调用的，意思就是用户只要点了,那么switch的状态一定必须改变成功,但这样肯定不行啊，真实业务逻辑的情况下，开启或者关闭操作失败是很正常的。

而且QMUICommonListItemView中可以获取switch，应当用统一规范，将switch的控制权应该归还给开发者。可以将additemview中的：
        if (itemView.getAccessoryType() == QMUICommonListItemView.ACCESSORY_TYPE_SWITCH) {
                itemView.setOnClickListener(new OnClickListener() {
                    @Override
                    public void onClick(View v) {
                        itemView.getSwitch().toggle();
                    }
                });
去掉。
当然不去掉也行哈，我只是发表下我这个业务场景下的情况。我可以重新继承重写即可。

**Comment by nobita0522** [comment]
试了下。。不行。section的属性全是private的,没有接口来操作。。。我现在只能copy一份QMUIGroupListView该下了。你们要是更新了就给记得说下啊~谢谢，就不用copy一下来改代码了

**Comment by nobita0522** [comment]
老铁推了新版本吗

**Comment by chanthuang** [comment]
没有。该修改会包含在下个版本。在此之前你可以使用 `ACCESSORY_TYPE_CUSTOM` 自定义 AccessoryView 实现你需要的效果。

**Comment by nobita0522** [comment]
好的，多谢
