### ISSUE TITLE
QMUIRoundButton如何实现背景匹配按压动作进行变化 

### ISSUE THREAD

**Issue by nobita0522** [Tencent/QMUI_Android#516]
### 具体问题描述 ###
发现QMUIRoundButton 只对文字颜色匹配了按压动作，但是背景并没有,我想实现的效果是如下(使用了style下的QDRadiusButton),注意观察“退出登录”按钮

![need](https://user-images.githubusercontent.com/24804777/53297108-ccbead00-3853-11e9-92d4-ed042ccb8142.gif)

该背景使用的selector

尝试着给QMUIRoundButton中的属性app:qmui_backgroundColor 使用同样的selector，但是表现却完全不一样了。

使用了同样的selector的QMUIRoundButton,注意观察“办理诊疗卡”这个按钮

![unexpected](https://user-images.githubusercontent.com/24804777/53297144-a2b9ba80-3854-11e9-9e34-55b287b469a0.gif)

**Comment by chanthuang** [comment]
1. `qmui_backgroundColor` 属性要求值是 `ColorStateList`，像 [qmui_s_transparent](https://github.com/Tencent/QMUI_Android/blob/master/qmui/src/main/res/color/qmui_s_transparent.xml) 这种 selector 形式的。
2. 要使 `QMUIRoundButton` 支持 pressed 态，只需要调用 [`setChangeAlphaWhenPress`](https://github.com/Tencent/QMUI_Android/blob/master/qmui/src/main/java/com/qmuiteam/qmui/alpha/QMUIAlphaButton.java#L66) (`QMUIRoundButton` 继承了 `QMUIAlphaButton` )，即可在 pressed 态下改变整个 View 的透明度。并且此时该 View 的 textColor 不需要指定为一个 selector，只需要指定为纯色。
3. QMUIDemo 中的 `@style/QDRadiusButton` 只是为了 Demo 展示方便而抽取的 style，并不属于 qmui 本身，后续可能会去掉。

感谢对 QMUI 的持续关注。

**Comment by nobita0522** [comment]
好的，谢谢，刚刚测试了，可以的。通过设置ColorStateList即可实现
