### ISSUE TITLE
一点小疑问???

### ISSUE THREAD

**Issue by lydlovezjr** [Tencent/QMUI_Android#519]
1.1.11版本中
Updated arch library to 0.3.0. Now developer must update support library to 28 or use androidx.
我的项目并没有升级到28或者x,但是可以正常运行!!!
求大佬指教!!!

**Comment by cgspine** [comment]
arch 0.3.0 以后有使用 lifecycle 相关的类， 如果你项目或者项目的依赖引入了相关的包，那就应该可以正常运行

**Comment by lydlovezjr** [comment]
arch是???
