### ISSUE TITLE
QMUIStickySectionLayout

### ISSUE THREAD

**Issue by Theoneee** [Tencent/QMUI_Android#520]
ArrayList<WarningHistoryItemSection> itemSections = new ArrayList<>();
            QMUISection<WarningHistoryHeadSection,WarningHistoryItemSection> section = new QMUISection<>(headSection, itemSections, i!=0);
            section.setExistBeforeDataToLoad(true);

这样直接放空的数据进去后，不会进入到 Callback的loadmore里面。

**Comment by Theoneee** [comment]
@Override
    public void onItemClick(QMUIStickySectionAdapter.ViewHolder holder, int position) {
        
    }

这个onItemClick怎么获取item上的数据啊。。

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/53490480-bd976380-3ace-11e9-8d95-2ca94fe32eaa.png)

这里又文档：https://github.com/Tencent/QMUI_Android/wiki/QMUIStickySectionLayout

**Comment by cgspine** [comment]
现在确实空 section 无法出 loadMore， 这个我改改

**Comment by Theoneee** [comment]
好的。知道了。。谢谢~~~  ……^ ^
