### ISSUE TITLE
关于状态栏沉浸式问题

### ISSUE THREAD

**Issue by haonan1** [Tencent/QMUI_Android#521]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.1.12`

### 具体问题描述 ###
单Activity多Fragment中 第一个fragment状态栏没有问题，以后的都有问题，已经在baseFragment的onActivityCreate中调用 QMUIViewHelper.requestApplyInsets 这个方法
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/4619300/53474693-bcebd680-3aa8-11e9-80ce-06fd5ec221bf.png)

#### Layout Inspector 文件([如何获取]#### 异常日志（堆栈） ####
com.baihesheng.shop_2019.02.27_15.53.li.zip

**Comment by haonan1** [comment]
[https://github.com/haonan1/blog/blob/master/com.baihesheng.shop_2019.02.27_15.53.li.zip](url)

**Comment by haonan1** [comment]
@cgspine 上面是layout inspector文件，麻烦看下

**Comment by Theoneee** [comment]
你布局写错了吧。我也是这样的布局，但是没问题。

**Comment by haonan1** [comment]
> 你布局写错了吧。我也是这样的布局，但是没问题。

就是简单的布局，我看着没问题，不知道咋回事，第一个fragment没问题，剩余的都往状态栏上上移

**Comment by cgspine** [comment]
出现这样的原因，一般是因为你的第一个 fragment view 层级中有元素 fitSystemWindows = true 了。 需要确保你的 view 层级中 fitSystemWindows = true 的 view 的所有 viewParent 是实现了 IWindowInsetLayout 的 View

**Comment by haonan1** [comment]
@cgspine 多谢，解决了 四个fragment 最外层应该是QMUIWindowInsetLayout 写成了FrameLayout
