### ISSUE TITLE
arch  库版本问题

### ISSUE THREAD

**Issue by windfone** [Tencent/QMUI_Android#522]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 异常日志（堆栈） ####

下载的最新版本的源码里面有QMUIFragmentPagerAdapter，添加arch  0.3.1之后，没用这个类是怎么回事啊

**Comment by cgspine** [comment]
arch 0.4.0 才添加了这个类的，可以升级下

**Comment by dxpbloom** [comment]
arch 这个最新版本是多少了

**Comment by cgspine** [comment]
0.5.0
