### ISSUE TITLE
QMUITopBarLayout如何设置透明

### ISSUE THREAD

**Issue by nobita0522** [Tencent/QMUI_Android#532]
尝试了很多种设置透明的方法，都未起效果。该如何设置QMUITopBarLayout透明呢

**Comment by fuhaodev** [comment]
代码调用QMUITopBarLayout的setBackgroundColor(UIUtils.getColor(android.R.color.transparent));

**Comment by nobita0522** [comment]
谢谢朋友，不过，没起作用呢。你的能起作用吗

 mTopBar.setBackgroundColor(getResources().getColor(android.R.color.transparent,null))

![normal](https://user-images.githubusercontent.com/24804777/54252675-abb1c800-4586-11e9-95db-d868388b8bb4.png)

**Comment by fuhaodev** [comment]
在style中覆盖一下qmui_topbar_bg的背景色为透明

**Comment by fuhaodev** [comment]
是否调用了setBackgroundDividerEnabled，这个方法会覆盖背景色，要放到setBackgroundColor之前调用

**Comment by nobita0522** [comment]
不行呢，试了下，都不行。看了下以前的issue，开发人员说暂时仅支持纯色背景。

**Comment by nobita0522** [comment]
朋友，你的能透明吗，能的话能否贴一下代码呢。

**Comment by fuhaodev** [comment]
> 朋友，你的能透明吗，能的话能否贴一下代码呢。

我这可以啊，你是不是用的版本太低了

**Comment by fuhaodev** [comment]
![1](https://user-images.githubusercontent.com/17568641/54260074-e0cc1380-45a2-11e9-8dda-4e61e83c3813.png)
![2](https://user-images.githubusercontent.com/17568641/54260079-e3c70400-45a2-11e9-842f-81bde8375c96.png)

**Comment by fuhaodev** [comment]
直接调用mTopbar.setBackgroundColor(UIUtils.getColor(android.R.color.transparent));下面是调用前和调用后的UI
![1](https://user-images.githubusercontent.com/17568641/54260249-5b952e80-45a3-11e9-9650-c09831776e74.png)![2](https://user-images.githubusercontent.com/17568641/54260262-64860000-45a3-11e9-9145-c22a4bd63244.png)

**Comment by nobita0522** [comment]
不知道怎么的，我的不行。哎。我改了style都不行。

**Comment by nobita0522** [comment]
兄弟，你这个项目在你的github上吗，想学习下。

**Comment by nobita0522** [comment]
朋友，你这个项目在你的github上吗，想学习下。

**Comment by fuhaodev** [comment]
> 朋友，你这个项目在你的github上吗，想学习下。

没有，公司项目

**Comment by nobita0522** [comment]
朋友能否贴一下你刚刚发的那一屏的xml，我也有发送验证码和接收验证码的界面，自己设计好丑啊

**Comment by fuhaodev** [comment]
不行的话你可以直接把源码copy出来，自己改改，实际上QMUITopBarLayout也只是对QMUITopBar做个一个包装，用QMUITopBarLayout包装的时候作者给的背景确实也是透明的，应该是你的style设置问题
<img width="848" alt="屏幕快照 2019-03-13 15 27 11" src="https://user-images.githubusercontent.com/17568641/54260663-85028a00-45a4-11e9-922a-c08fcf42b6f2.png">

**Comment by nobita0522** [comment]
实现了，谢谢。

**Comment by nobita0522** [comment]
![good](https://user-images.githubusercontent.com/24804777/54262624-9d28d800-45a9-11e9-88dd-bc9e1838597f.png)

朋友看，好多了~谢谢

**Comment by fuhaodev** [comment]
> ![good](https://user-images.githubusercontent.com/24804777/54262624-9d28d800-45a9-11e9-88dd-bc9e1838597f.png)
> 
> 朋友看，好多了~谢谢

嗯，不客气，项目还没上线UI不太好发出来，抱歉

**Comment by nobita0522** [comment]
嗯嗯，理解。我就想问下。你刚刚贴的图中，接收验证码的4个横线输入框是已经实现的组件吗。github上有吗？

**Comment by fuhaodev** [comment]
嗯，github搜OptView，是通过继承一个TextView自定义View实现的验证码控件

**Comment by nobita0522** [comment]
谢谢！

**Comment by nobita0522** [comment]
> 嗯，github搜OptView，是通过继承一个TextView自定义View实现的验证码控件

朋友，啥都没搜索到，这个是类名吧。。。那个github项目是什么呢。

**Comment by fuhaodev** [comment]
> > 嗯，github搜OptView，是通过继承一个TextView自定义View实现的验证码控件
> 
> 朋友，啥都没搜索到，这个是类名吧。。。那个github项目是什么呢。

android-otpview-pinview

**Comment by nobita0522** [comment]
好的，我真是麻烦，哈哈。谢谢了。

**Comment by nobita0522** [comment]
> > > 嗯，github搜OptView，是通过继承一个TextView自定义View实现的验证码控件
> > 
> > 
> > 朋友，啥都没搜索到，这个是类名吧。。。那个github项目是什么呢。
> 
> android-otpview-pinview

![6K$@~J6WHO%J)51%_BR_Q1R](https://user-images.githubusercontent.com/24804777/54333202-9313e180-465c-11e9-8cd5-ac98d6a8199b.png)

朋友看，哈哈。谢谢。
