### ISSUE TITLE
QMUICollapsingTopBarLayout

### ISSUE THREAD

**Issue by Theoneee** [Tencent/QMUI_Android#533]
想问一下，如果想在这里面添加下拉刷新怎么写。下拉层应该怎么放呢。
![QQ图片20190313160249](https://user-images.githubusercontent.com/32156330/54262584-7f5b7300-45a9-11e9-9f4d-37f5dc520885.png)

**Comment by cgspine** [comment]
目前这个控件还不能支持这种嵌套下拉刷新

**Comment by Theoneee** [comment]
好的。感谢~~
