### ISSUE TITLE
键盘升起后，全屏空白

### ISSUE THREAD

**Issue by nobita0522** [Tencent/QMUI_Android#535]
问题如图:

![UNnormal](https://user-images.githubusercontent.com/24804777/54409946-44ca1580-4724-11e9-87b0-789edf4de3f8.gif)

xml 如下:
<?xml version="1.0" encoding="utf-8"?>
<com.qmuiteam.qmui.widget.QMUIWindowInsetLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:focusable="true"
    android:focusableInTouchMode="true">

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <ImageView
            android:id="@+id/login_gif_imageview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="fitXY"
            android:src="@mipmap/bg_login_init2" />

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@color/app_black_overlay">

            <ImageView
                android:layout_width="@dimen/dp_72"
                android:layout_height="@dimen/dp_72"
                android:layout_alignTop="@id/cardview"
                android:layout_centerHorizontal="true"
                android:layout_marginTop="-116dp"
                android:src="@mipmap/ic_app_icon_round" />

            <TextView
                android:id="@+id/version_textView"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignTop="@id/cardview"
                android:layout_centerHorizontal="true"
                android:layout_marginTop="-42dp"
                android:text="2.1.0"
                android:textColor="@color/qmui_config_color_white"
                android:textSize="16sp" />

            <android.support.v7.widget.CardView
                android:id="@+id/cardview"
                android:layout_width="match_parent"
                android:layout_height="340dp"
                android:layout_centerInParent="true"
                android:layout_margin="32dp"
                app:cardCornerRadius="6dp"
                app:cardElevation="3dp"
                app:cardUseCompatPadding="true">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:background="@color/login_bg"
                    android:orientation="vertical">

                    <RelativeLayout
                        android:layout_width="match_parent"
                        android:layout_height="45dp"
                        android:layout_marginTop="10dp">

                        <View
                            android:layout_width="8dp"
                            android:layout_height="match_parent"
                            android:layout_alignParentStart="true"
                            android:background="@color/app_color_blue" />

                        <TextView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:layout_centerInParent="true"
                            android:layout_marginStart="50dp"
                            android:text="门诊服务系统"
                            android:textColor="@color/app_color_theme_4"
                            android:textSize="18sp"
                            android:textStyle="bold" />
                    </RelativeLayout>

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="50dp"
                        android:layout_marginTop="10dp"
                        android:orientation="horizontal"
                        android:paddingStart="50dp"
                        android:paddingEnd="30dp">

                        <android.support.design.widget.TextInputLayout
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:textColorHint="#c5c5c5"
                            app:hintTextAppearance="@style/app_edittext">

                            <EditText
                                android:id="@+id/user_mobile_edittext"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:background="@drawable/selector_bg_edit"
                                android:hint="手机号"
                                android:inputType="number"
                                android:maxLength="11"
                                android:paddingBottom="2dp"
                                android:textColor="@color/app_color_blue"
                                android:textCursorDrawable="@drawable/bg_input_cursor"
                                android:textSize="15sp" />
                        </android.support.design.widget.TextInputLayout>
                    </LinearLayout>

                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="50dp"
                        android:orientation="horizontal"
                        android:paddingStart="50dp"
                        android:paddingEnd="30dp">

                        <android.support.design.widget.TextInputLayout
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:textColorHint="#c5c5c5"
                            app:hintTextAppearance="@style/app_edittext">

                            <EditText
                                android:id="@+id/user_password_editText"
                                android:layout_width="match_parent"
                                android:layout_height="wrap_content"
                                android:background="@drawable/selector_bg_edit"
                                android:hint="密码"
                                android:inputType="textPassword"
                                android:maxLength="16"
                                android:paddingBottom="2dp"
                                android:textColor="@color/app_color_blue"
                                android:textCursorDrawable="@drawable/bg_input_cursor"
                                android:textSize="15sp" />
                        </android.support.design.widget.TextInputLayout>
                    </LinearLayout>

                    <RelativeLayout
                        android:layout_width="match_parent"
                        android:layout_height="60dp"
                        android:layout_marginTop="25dp"
                        android:gravity="center"
                        android:paddingStart="50dp"
                        android:paddingEnd="30dp">

                        <Button
                            android:id="@+id/login_button"
                            android:layout_width="match_parent"
                            android:layout_height="40dp"
                            android:background="@drawable/bt_shape"
                            android:stateListAnimator="@drawable/state_list_animator_z"
                            android:text="登            录"
                            android:textColor="@color/app_color_blue" />
                    </RelativeLayout>

                    <TextView
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center_horizontal"
                        android:layout_marginTop="9dp"
                        android:text="其他登录方式"
                        android:textColor="#9a9a9a"
                        android:textSize="12sp" />

                    
                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:orientation="horizontal">

                        <Space
                            android:layout_width="0dp"
                            android:layout_height="match_parent"
                            android:layout_weight="1" />

                        <ImageView
                            android:id="@+id/qq_login_imageview"
                            android:layout_width="@dimen/dp_36"
                            android:layout_height="@dimen/dp_36"
                            android:layout_gravity="center"
                            android:src="@mipmap/ic_qq_round" />

                        <Space
                            android:layout_width="0dp"
                            android:layout_height="match_parent"
                            android:layout_weight="1" />

                        <ImageView
                            android:id="@+id/wechat_login_imageview"
                            android:layout_width="@dimen/dp_36"
                            android:layout_height="@dimen/dp_36"
                            android:layout_gravity="center"
                            android:src="@mipmap/ic_wechat_round" />

                        <Space
                            android:layout_width="0dp"
                            android:layout_height="match_parent"
                            android:layout_weight="1" />

                        <ImageView
                            android:id="@+id/weibo_login_imageview"
                            android:layout_width="@dimen/dp_36"
                            android:layout_height="@dimen/dp_36"
                            android:layout_gravity="center"
                            android:src="@mipmap/ic_weibo_round" />

                        <Space
                            android:layout_width="0dp"
                            android:layout_height="match_parent"
                            android:layout_weight="1" />

                    </LinearLayout>
                </LinearLayout>
            </android.support.v7.widget.CardView>

            
            <TextView
                android:id="@+id/copyright_textView"
                style="@style/AppCopyrightTextViw"
                android:layout_alignParentBottom="true" />

            <android.support.design.widget.FloatingActionButton
                android:id="@+id/chioces_button"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignTop="@id/cardview"
                android:layout_alignEnd="@id/cardview"
                android:layout_marginTop="16dp"
                android:layout_marginEnd="-24dp"
                android:src="@mipmap/ic_plus"
                android:transitionName="loginFab"
                app:backgroundTint="@color/app_color_blue" />

            <com.github.glomadrian.grav.GravView
                android:id="@+id/grav"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_centerInParent="true"
                app:animationGenerators="@array/BubbleAnimations"
                app:array_colors="@array/bubble"
                app:ball_from_size="10dp"
                app:ball_to_size="20dp"
                app:colorGenerator="com.github.glomadrian.grav.generator.paint.ArrayColorGenerator"
                app:gravGenerator="com.github.glomadrian.grav.generator.grav.BallGenerator"
                app:pointGenerator="com.github.glomadrian.grav.generator.point.RegularPointGenerator"
                app:regular_cell_size="300"
                app:regular_variance="200"
                app:shake_direction="vertical"
                app:shake_max_duration="20000"
                app:shake_min_duration="10000"
                app:shake_variance="500dp"
                app:side_to_side_direction="leftToRight"
                app:side_to_side_max_duration="10000"
                app:side_to_side_min_duration="10000" />
        </RelativeLayout>
    </FrameLayout>
</com.qmuiteam.qmui.widget.QMUIWindowInsetLayout>

**Comment by nobita0522** [comment]
如果直接启动的时候，firstFragment就是这个fragment，就是正常的.如果是通过 startFragment（这个fragment） 进入，便会出现该异常

**Comment by cgspine** [comment]
可否发一份升起键盘后的 layout Inspector 文件？

**Comment by nobita0522** [comment]
[bug.zip](https://github.com/Tencent/QMUI_Android/files/2981160/bug.zip)

![bug](https://user-images.githubusercontent.com/24804777/54574833-d12e4e00-4a2c-11e9-9c25-ab4bcf3f6cf9.png)

**Comment by nobita0522** [comment]
android:windowSoftInputMode="adjustPan" 就好了。

但是弹起时白屏还是不知道原因。不过 android:windowSoftInputMode="adjustPan"可以满足需求
