### ISSUE TITLE
QMUIDialog

### ISSUE THREAD

**Issue by Theoneee** [Tencent/QMUI_Android#542]
普通的Dialog有一个setOnKeyListener这个监听，可以直接在这里设置点击 返回键不消失，希望QMUIDialog里并没有将这个方法曝露出来。

**Comment by Theoneee** [comment]
mMessage  能否支持  SpannableString 呢

**Comment by chanthuang** [comment]
- QMUIDialog 继承了 Dialog，setOnKeyListener 可直接使用，并没有做修改。
- [seMessage](https://github.com/Tencent/QMUI_Android/blob/master/qmui/src/main/java/com/qmuiteam/qmui/widget/dialog/QMUIDialog.java#L191) 方法传入的是 CharSequence，可以支持 SpannableString。

**Comment by Theoneee** [comment]
光看着Builder了。。show了之后返回来的是一个Dialog。已经解决了。感谢解答~

**Comment by chanthuang** [comment]
show 之前可以先 build，返回一个 dialog 并且不显示，然后就可以在显示之前为所欲为了。
