### ISSUE TITLE
QMUIStickySectionLayout

### ISSUE THREAD

**Issue by brucewuu520** [Tencent/QMUI_Android#548]
目前使用QMUIStickySectionLayout没法动态去删除其中一个item啊，只能重新设置adapter数据，这个性能，体验就不太好吧, notifyItemRemoved(int position) 无用武之地了

**Comment by cgspine** [comment]
内部用了 DiffUtil，重新设置 adapter 数据后，其实内部还是调用了 notifyItemRemoved 去更新 UI

**Comment by xiaowang119** [comment]
> 目前使用QMUIStickySectionLayout没法动态去删除其中一个item啊，只能重新设置adapter数据，这个性能，体验就不太好吧, notifyItemRemoved(int position) 无用武之地了

你好，你使用的时候能在库中找到QMUISection.Model这个接口吗

**Comment by cgspine** [comment]
找不到接口？ 是否是QMUI 的版本不够高？
