### ISSUE TITLE
QMUIGroupListView 的字体大小和颜色可以通过xml设置嘛

### ISSUE THREAD

**Issue by Theoneee** [Tencent/QMUI_Android#549]
项目里设置了调整字体大小选项[解决方法是这样子的](https://blog.csdn.net/qq_35849743/article/details/88818848)，QMUIDialog的字体大小我已经通过Style改了，TipsDialog的字体还没改还有QMUIGroupListView 。

**Comment by Theoneee** [comment]
如果xml不可以，那就得一个个的获取TextView再设置了。或者Base里写一个创建的方法，在那里设置。

**Comment by chanthuang** [comment]
见[源码 qmui_themes.xml](https://github.com/Tencent/QMUI_Android/blob/master/qmui/src/main/res/values/qmui_themes.xml#L143)
这几个值可以分别设置 VERTICAL 和 HORIZONTAl 下的 titleTextSize/detailTextSize，但只能全局设置，影响所有 QMUIGroupListView。

**Comment by Theoneee** [comment]
@chanthuang 好的。这个改字体大小就是全局的嘛。那就这样改了。感谢·~
