### ISSUE TITLE
QMUI能否官方建一个群

### ISSUE THREAD

**Issue by Theoneee** [Tencent/QMUI_Android#555]
不懂使用的直接在里面问了，如果是问题再到这里提Issues，毕竟这里回复的太慢了。

**Comment by nobita0522** [comment]
github > qq

**Comment by nobita0522** [comment]
在这儿提issue示为了帮助后面的人遇到同样的问题好可以找到答案.

**Comment by Theoneee** [comment]
在群里问，如果有同样的问题不是解决的更快？ 如果是Issues，再到这里写上。 @nobita0522

**Comment by nobita0522** [comment]
要都解决了，谁还会在这儿专门提issues啊。对不对

**Comment by Theoneee** [comment]
解决了的说明是已经有解决方案（这个问题出现过）,没有人解决说明这个问题没有人遇到过。然后再来提issues。如果这里的issues有50%的问题都是前面出现过的，那么有什么意义呢？重复出现的问题更浪费开发者时间去回复。

**Comment by nobita0522** [comment]
首先，解决方案不是那么快能出来的，很多都有临时解决方案。其次，这个方便开发者统一问题，和研究BUG，github是个工具，如果改到Q群，那github这个平台能做的基础功能就需要开发者自己去记录维护，反而增加很多工作量

**Comment by MoLice** [comment]
从已有的经验来看，存在了群后，由于提问门槛的降低，反而会让使用者略去自主排查定位问题的步骤，很多群里抛出来的问题要么 issue 已经有了，要么其实都是业务自己的问题，群更大的意义可能已经变成交流而非解答，所以我们短期内暂时没有建群的计划（不排除以后有），开发者有兴趣的话可以自行建群哈。
