### ISSUE TITLE
最新版本1.2.0 gradle依赖之后 没有tab包

### ISSUE THREAD

**Issue by Ade-rui** [Tencent/QMUI_Android#557]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
mTabSegment 无法通过builder来创建ta b 因为根本就没有tab 这个包 但是依赖下来的确实是1.2.0的代码
#### 异常日志（堆栈） ####

**Comment by fhwhg** [comment]
最新master 版本做了一些调整重构这块的内容调用方式不一样了，我也是发现引用1.2.0 没有Tab包你要下载1.2.0的源码看那个示例调用写法。

**Comment by netgb** [comment]
同样依赖1.2.0版本库文件，确实找不到demo里面的用法
和最新master不一样没有tab包
com.qmuiteam.qmui.widget.**tab**.QMUITabSegment

**Comment by Theoneee** [comment]
看1.2.0里面Demo的 用法就可以了。

**Comment by Theoneee** [comment]
现在Demo里的。

**Comment by cgspine** [comment]
master 重构了 QMUITabSegment，还没有发布。可以切换到 1.x 分支查看 1.2.0版本对应的 Demo 的使用
