### ISSUE TITLE
QMUITabSegment如何使用？

### ISSUE THREAD

**Issue by ywss** [Tencent/QMUI_Android#558]
### 运行环境 ###

最新版本

### 具体问题描述 ###

刚用这个ui库，报错了，也没找到详细文档，demo里是fragment，难道直接用在activity不行？
报下面的错误
Unable to start activity ComponentInfo{}: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class com.qmuiteam.qmui.widget.tab.QMUITabSegment

#### Layout Inspector 文件([如何获取]

<?xml version="1.0" encoding="utf-8"?>

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <androidx.viewpager.widget.ViewPager
        android:id="@+id/contentViewPager"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        android:fitsSystemWindows="true"/>

    <com.qmuiteam.qmui.widget.tab.QMUITabSegment
        android:id="@+id/tabs"
        android:layout_width="match_parent"
        android:layout_height="40dp"/>

</LinearLayout>

**Comment by Theoneee** [comment]
主题设置了吗？

**Comment by Theoneee** [comment]
<style name="BaseTheme" parent="QMUI.Compat.NoActionBar">

**Comment by ywss** [comment]
找到原因了，用了一个 attr ，demo里复制出来的，这个库文档太简单了。。。

**Comment by lovewysy** [comment]
QMUITabSegment中我都没有tabBuilder()等方法与demo不符，请问怎么解决

**Comment by cgspine** [comment]
可以将 demo 切换到1.x 分支。
