### ISSUE TITLE
R.id.qmuidemo 爆红

### ISSUE THREAD

**Issue by turnmind** [Tencent/QMUI_Android#559]
能build运行，就是无法引用 Cannot resolve symbol "R"，怎么解决？
而且运行在魅族15的底部导航图标也超出了

**Comment by cgspine** [comment]
Demo 里面选中tab的图片超出，这是 QMUITabSegment 的功能特性展示。
Cannot resolve symbol "R" 可以试试 clean 一下

**Comment by turnmind** [comment]
@cgspine 不行啊大佬 
![捕获11](https://user-images.githubusercontent.com/31524059/56073505-b22a9e00-5dd7-11e9-8f8b-c23a8e5c1a09.PNG)

**Comment by cgspine** [comment]
http://www.mamicode.com/info-detail-1761843.html

可以试试网上的一些解决方案

**Comment by turnmind** [comment]
@cgspine 问题已解决，原因是 Android Studio 3.2 与 Gradle 3.x 版不兼容，将其下调至 3.2 版后重新 Sync Project with Gradle 即可。
