### ISSUE TITLE
Could not find com.qmuiteam:qmui:1.2.0

### ISSUE THREAD

**Issue by lenvonsam** [Tencent/QMUI_Android#561]
### 运行环境 ###

- [x] 设备型号：如：`Pixel XL`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `3.1.0`
- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###
Could not find com.qmuiteam:qmui:1.2.0.
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/10168476/55901460-f7927400-5bfb-11e9-8970-440d1e802d2a.png)
![image](https://user-images.githubusercontent.com/10168476/55901471-fcefbe80-5bfb-11e9-8916-5c10bdf98298.png)
![image](https://user-images.githubusercontent.com/10168476/55901494-05e09000-5bfc-11e9-9a2e-e559d03ce30a.png)

**Comment by Theoneee** [comment]
maven { url 'https://jitpack.io' }

**Comment by Theoneee** [comment]
在最后一张图，google() 上面加

**Comment by lenvonsam** [comment]
我自己加了mirror导致的，去掉就好了
