### ISSUE TITLE
QMUIProgressBar进度为0时，出现问题了

### ISSUE THREAD

**Issue by davidgerka** [Tencent/QMUI_Android#562]
我想设置圆形进度条从120度开始（代码见下图），当进度值为0时，会出现进度条为100%了，有解决办法吗？
![40C3AAE2-BA3A-4211-A270-8876548C47DD](https://user-images.githubusercontent.com/13624423/56031238-70571480-5d51-11e9-845a-d67f5070eedc.png)
![WX20190412-182936](https://user-images.githubusercontent.com/13624423/56031248-76e58c00-5d51-11e9-9e00-a5943a1e91f1.png)

**Comment by cgspine** [comment]
什么手机？我这边改了后没有问题

**Comment by davidgerka** [comment]
> 什么手机？我这边改了后没有问题

红米3s，Android6.0

**Comment by cgspine** [comment]
目前不知道原因，但是在进度为0 时，可以不 draw 它， 以此来 fix 它
