### ISSUE TITLE
demo样式问题

### ISSUE THREAD

**Issue by SpringHgui** [Tencent/QMUI_Android#568]
### 运行环境 ###

- [x] 设备系统版本：android 7.1.1
- [x] 设备型号：如：魅族Pro6s
- [x] QMUI Android 版本：`master`

### 具体问题描述 ###
底部菜单按钮icon样式，过大
#### 问题截图 ####
![微信图片_20190417141753](https://user-images.githubusercontent.com/22363718/56265370-ee356a00-611b-11e9-9c60-0becc5bdb168.jpg)
![微信图片_20190417141800](https://user-images.githubusercontent.com/22363718/56265371-ee356a00-611b-11e9-8638-acb7a0aee59c.jpg)

**Comment by cgspine** [comment]
这是主干 QMUITabSegment 的功能展示。
