### ISSUE TITLE
错误: 找不到符号 符号:   类 QDWidgetContainer 位置: 类 QDDataManager

### ISSUE THREAD

**Issue by chinamingsss** [Tencent/QMUI_Android#570]
错误: 找不到符号
符号:   类 QDWidgetContainer
位置: 类 QDDataManager

**Comment by netgb** [comment]
同问，是新版版本的AS3.4吧，我的也一样问题，新版gradle插件annotation处理不奏效?

**Comment by nobita0522** [comment]
幸好没升级，每次升级了，都有一堆毛病

**Comment by cgspine** [comment]
我的mac升级 AS 到 3.4 后可以正常工作
