### ISSUE TITLE
QDWebExplorerFragment 设置进度条颜色无效

### ISSUE THREAD

**Issue by fhwhg** [Tencent/QMUI_Android#571]
mIsPageFinished = false;
mDstProgressIndex = msg.arg1;
mDuration = msg.arg2;
//mProgressBar.setVisibility(View.INVISIBLE);
mProgressBar.setVisibility(View.VISIBLE);
         mProgressBar.setIndeterminateTintList(ColorStateList.valueOf(Color.parseColor("#87CEFA")));
调用了这个设置颜色的方法还是没有改变颜色是我写法不对吗？

**Comment by cgspine** [comment]
应该用 setProgressDrawable 吧。 setIndeterminateTintList 没用过，不了解。

**Comment by fhwhg** [comment]
@cgspine OK了是得用setProgressDrawable这个方法。
