### ISSUE TITLE
侧滑退出activity，侧滑一小段距离则背景就变透明了

### ISSUE THREAD

**Issue by guizhongxiaobai** [Tencent/QMUI_Android#574]
### 运行环境 ###

- [x] 设备型号：`vivo Y83A`
- [x] 设备系统版本：`Android 8.1`
- [x] Gradle 版本：如 `3.0.1`
- [x] QMUI Android 版本：`1.2.0`
- [x] arch Android 版本：`0.3.1`

**Comment by cgspine** [comment]
可否截个 gif 图

**Comment by guizhongxiaobai** [comment]
![Screenrecording_20190423_161413](https://user-images.githubusercontent.com/22098435/56566501-63ee7980-65e5-11e9-8374-f7e85d40e775.gif)

**Comment by Theoneee** [comment]
设置背景颜色。

**Comment by guizhongxiaobai** [comment]
> 设置背景颜色。

是这样的，3Q
