### ISSUE TITLE
键盘升起后，QMUITopBarLayout高度被更改

### ISSUE THREAD

**Issue by JianLiangSub** [Tencent/QMUI_Android#581]
### 具体问题描述 ###
键盘升起后，QMUITopBarLayout高度被更改

#### 问题截图 ####
![13433](https://user-images.githubusercontent.com/28552613/56725389-5d940500-677f-11e9-8b55-248612a7b659.gif)

**Comment by JianLiangSub** [comment]
这是我使用的方式。

    <com.qmuiteam.qmui.widget.QMUITopBarLayout
        android:id="@+id/topbar_title"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true"></com.qmuiteam.qmui.widget.QMUITopBarLayout>

**Comment by cgspine** [comment]
界面最外层需要是 QMUIWindowInsetLayout，来消耗键盘区域
