### ISSUE TITLE
QMUI帮助太大了，写入论文，怎么给QMUI开个头

### ISSUE THREAD

**Issue by nobita0522** [Tencent/QMUI_Android#583]
QMUI帮助太大了，简化了我太多开发的东西了，本来我不是研究Android，我硬是搭建出来了Android客户端，而且界面还能看，客户端很多地方使用到了QMUI，打算写入论文了，怎么给QMUI开个头，分几个块来写。

**Comment by nobita0522** [comment]
对于QMUI的很多组件，我进一步进行了封装，让我更加进一步的面向业务，而不去在意界面，在抽象的过程中遇到过一些问题，也发现了QMUI还是存在一些设计不合理的地方。等答辩完了，将会系统地列出来。以及很多改进建议。

**Comment by nobita0522** [comment]
感谢研发组。致谢里面给你们留一段。大佬们留个大名吧，哈哈。衷心感谢。

**Comment by chanthuang** [comment]
感谢你对 QMUI 的支持。如有需要，可将“QMUI 开发团队”作为研发组名称写入，QMUI 既是项目名，也是团队名称。
期待你的改进建议，也欢迎提 PR。
