### ISSUE TITLE
QMUIFragment为什么每次返回都会执行下所返回Frament的onActivityCreated？

### ISSUE THREAD

**Issue by pandrawla** [Tencent/QMUI_Android#584]
QMUIFragment为什么每次返回都会执行下所返回Frament的onActivityCreated？

**Comment by cgspine** [comment]
这是Fragment框架的正常的生命周期

**Comment by pandrawla** [comment]
我用系统的并不会这样啊，每次在打开的时候执行一次，在此frament在打开另外一个fragment，然后返回此fragment还会执行一次这样不就重复执行了吗

**Comment by cgspine** [comment]
在此frament在打开另外一个fragment，是用 add 还是 replace ？
replace 一定会，其本意是打开第二个 fragment 后 回收前一个 fragment 的 View，然后返回时再重新实例化这个 View，以减少内存占用。

add 在层级非常深的情况下会有性能问题的，因为 add 操作并不会把前一个 fragment 的 view 从界面中移除，会使得界面承载非常多的 View

**Comment by pandrawla** [comment]
明白了大神，我看了源码了，用的就是replace,那这样的话数据请求放在哪个生命周期好点？

**Comment by cgspine** [comment]
如果是用 AAC 的话，推荐是 onCreate/init 的时候发起数据请求， 通过LiveData, viewLifecycleOwner 来通知UI刷新， observe 动作放在 onActivityCreated。这也是官方的使用方式

如果不是 LiveData 的方式，要注意数据异步回来时可能 UI 还没构建好的问题， 这种情况也可以在 onCreateView() 里调用。QMUIFragment 的 onCreateView 也只会调用一次，因为 QMUIFragment 会做手势返回，对 View 做了 cache。

推荐还是用官方的形式吧。 生命周期友好，还能尽早的开始准备数据。
