### ISSUE TITLE
      自定义  dialog.getWindow().setBackgroundDrawableResource(android.R.color.transparent);不起作用

### ISSUE THREAD

**Issue by as11051105** [Tencent/QMUI_Android#585]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
不起作用的点是？ 你期望的效果和实际效果分别是怎样？

**Comment by as11051105** [comment]
就是设置这个后 背景四个角依然是白色，有时自定义dialog的四角圆弧比较大，依然看得到白底的角

**Comment by cgspine** [comment]
这是因为 qmui 的 DialogView 有白色背景的原因吧。可以通过替换
`<item name="qmui_dialog_bg">@drawable/qmui_dialog_bg</item>` 来更改背景

**Comment by as11051105** [comment]
这个添加了所有的都变了， 只需要某一个自定义的就不满足了

**Comment by cgspine** [comment]
`QMUIDialogBuilder.create(int styleRes)`， 可以自定义的，create 时传入新的 styleRes 就行
