### ISSUE TITLE
最新版本Demo编译运行 右滑返回底部Fragment出现白屏

### ISSUE THREAD

**Issue by spysoos** [Tencent/QMUI_Android#589]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 5x`
- [x] 设备系统版本：如 `Android 6.0`
- [x] Gradle 版本：如 `3.3.1`
- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###
Android Studio 3.3.1

最新版本Demo编译环境没改，编译运行后右滑返回底部Fragment出现白屏,无论是虚拟机还是真机，都会出现这个问题, 从官网下载的Demo确没有... 

#### 问题截图 ####
![TIM截图20190508165225](https://user-images.githubusercontent.com/982866/57362984-99cd5980-71b2-11e9-99d4-ea9dd48606ed.png)

**Comment by cgspine** [comment]
androidx fragment 更改了某些实现，fixed，谢谢反馈
