### ISSUE TITLE
关于QMUIFragment的使用问题

### ISSUE THREAD

**Issue by spysoos** [Tencent/QMUI_Android#590]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###

如果我想在Fragment里再嵌套Fragment,比如这样的场景：
HomeFragment 底部是包含4个标签的导航栏，导航栏上方是ContentView, 用户点击底部标签切换Content View 当前的Fragment, 这里的切换是指replace，不是用viewpager进行滑动切换， 我知道QMUIFragmentActivity 提供 getContextViewId(), 然后startFragment进行转场，QMUIFragment没有提供类似getContextViewId()对某个ContentView 切换的功能。如果我仿照QMUIFragmentActivity里面的startFragment写一个 startNestFragment 并把 getSupportFragmentManager换成getChildFragmentManager, 这样是否可行？

**Comment by cgspine** [comment]
你可以继承 QMUIFragment 来实现类似 QMUIFragmentActivity 的事情，是可行的
