### ISSUE TITLE
启动应用时出现白屏

### ISSUE THREAD

**Issue by sceneren** [Tencent/QMUI_Android#594]
### 运行环境 ###

- [x] 设备型号：如：`pixel xl`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `3.4.0`
- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###
启动时出现白屏，配置了android:windowBackground仍然是白屏
#### 问题截图 ####
![39FAEF2E027D02DC202B45573D940D0F](https://user-images.githubusercontent.com/6612998/57500718-05c8d280-7317-11e9-8dd6-2e11a19df9d5.gif)

#### Layout Inspector 文件([如何获取](https://github.com/QMUI/QMUI_Android/wiki/%E6%8F%90%E4%BE%9B-Layout-Inspector-%E6%96%87%E4%BB%B6)) ####
[wiki.scene.kotlinmvpdemo_2019.05.10_11.30.li.zip](https://github.com/Tencent/QMUI_Android/files/3164794/wiki.scene.kotlinmvpdemo_2019.05.10_11.30.li.zip)

**Comment by cgspine** [comment]
你是如何配置 android:windowBackground 的？

**Comment by Theoneee** [comment]
这个问题和QMUI有啥关系。。
