### ISSUE TITLE
setToRefreshDirectly方法没有了吗？

### ISSUE THREAD

**Issue by blackberry2016** [Tencent/QMUI_Android#601]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
有的，不过还没有 release

**Comment by cgspine** [comment]
可升级到 1.3.1。
