### ISSUE TITLE
标题栏高度问题问题

### ISSUE THREAD

**Issue by pandrawla** [Tencent/QMUI_Android#602]
设置qmui_topbar_height无效果，还是原来的高度

**Comment by cgspine** [comment]
你是如何设置的？

**Comment by pandrawla** [comment]
就是在style里面<item name="qmui_topbar_height">48dp</item>

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/58394022-d84c8a80-8073-11e9-8103-73272615e8b2.png)
使用的时候是这样子的吗？ ，如果用 QMUITopBarLayout，则高度可以设为 wrap_content

**Comment by pandrawla** [comment]
用的就是QMUITopBarLayout

**Comment by cgspine** [comment]
层级问题啊，会被遮挡，如果只支持 Android L 以上的机器，是可以通过 elevation 来解决的。
