### ISSUE TITLE
QMUIProgressBar进度展示不正常

### ISSUE THREAD

**Issue by WinnieZy** [Tencent/QMUI_Android#603]
### 运行环境 ###

- [x] 设备型号：如：`Mi Mix3`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `3.3.2`
- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###

网速较快或下载文件较小时（10M），进度条没用更新进度/进度展示到10%不到但文件已下载完

网速较慢或下载文件较大时（50M），进度条进度展示正常

**Comment by cgspine** [comment]
这种是你 setProgress 的值不对吧

**Comment by WinnieZy** [comment]
不是啊，set的progress有打印日志看的，从0跑到100，但是QMUIProgressBar的进度没有更新，换成Android原生的progressBar就能正常更新进度

**Comment by cgspine** [comment]
在背景线程 setProgress 了？

**Comment by cgspine** [comment]
可以提供下代码吗？

**Comment by WinnieZy** [comment]
线程下载文件：
        new Thread(new Runnable() {
            @Override
            public void run() {
                try{
                    HttpURLConnection conn = (HttpURLConnection) new URL(apkUrl).openConnection();
                    conn.connect();
                    InputStream is = conn.getInputStream();
                    int length = conn.getContentLength();

                    FileOutputStream fos = new FileOutputStream(apkFile);

                    int count = 0;
                    byte[] buffer = new byte[1024];
                    while (true){
                        int numread = is.read(buffer);
                        count += numread;
                        // 计算进度条的当前位置，进度更新回调
                        progressListener.onProgressChanged((int) (((float)count/length) * 100));

                        // 下载完成
                        if (numread < 0){
                            progressListener.onProgressChanged(100);
                            progressListener.onDownloadFinished(apkFile);
                            break;
                        }
                        fos.write(buffer, 0, numread);
                    }
                    fos.close();
                    is.close();
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
        }).start();

下载进度监听器：
        new Downloader.DownLoadProgressListener() {
            @Override
            public void onProgressChanged(int progress) {
                Message msg = new Message();
                msg.what = MSG_UPGRADE_PROGRESS;
                msg.arg1 = progress;
                mHandler.sendMessage(msg);
            }

            @Override
            public void onDownloadFinished(File file) {
                Message msg = new Message();
                msg.what = MSG_INSTALL_APK;
                msg.obj = file;
                mHandler.sendMessage(msg);
            }
        };

Handler刷新UI:
    private static final int MSG_SHOW_PROGRESS = 0x01;
    private Handler mHandler = new Handler(Looper.getMainLooper()){
        @Override
        public void handleMessage(Message msg) {
            switch (msg.what){
                case MSG_UPGRADE_PROGRESS:
                    // 刷新进度条
                    mProgressBar.setProgress(msg.arg1);
                    break;
                default:
                    break;
            }
        }
    };

**Comment by WinnieZy** [comment]
线程下载文件：
`   new Thread(new Runnable() {
    @override
    public void run() {
        try{
                HttpURLConnection conn = (HttpURLConnection) new URL(apkUrl).openConnection();
                conn.connect();
                InputStream is = conn.getInputStream();
                int length = conn.getContentLength();

                FileOutputStream fos = new FileOutputStream(apkFile);

                int count = 0;
                byte[] buffer = new byte[1024];
                while (true){
                    int numread = is.read(buffer);
                    count += numread;
                    // 计算进度条的当前位置，进度更新回调
                    progressListener.onProgressChanged((int) (((float)count/length) * 100));

                    // 下载完成
                    if (numread < 0){
                        progressListener.onProgressChanged(100);
                        progressListener.onDownloadFinished(apkFile);
                        break;
                    }
                    fos.write(buffer, 0, numread);
                }
                fos.close();
                is.close();
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }).start();`

下载进度监听器：
`  new Downloader.DownLoadProgressListener() {
       @override
       public void onProgressChanged(int progress) {
            Message msg = new Message();
            msg.what = MSG_UPGRADE_PROGRESS;
            msg.arg1 = progress;
            mHandler.sendMessage(msg);
        }

        @Override
        public void onDownloadFinished(File file) {
            Message msg = new Message();
            msg.what = MSG_INSTALL_APK;
            msg.obj = file;
            mHandler.sendMessage(msg);
        }
    };`

Handler刷新UI:
`   private static final int MSG_SHOW_PROGRESS = 0x01;
    private Handler mHandler = new Handler(Looper.getMainLooper()){
        @override
        public void handleMessage(Message msg) {
            switch (msg.what){
                case MSG_UPGRADE_PROGRESS:
                    // 刷新进度条
                      mProgressBar.setProgress(msg.arg1);
                      break;
               default:
                      break;
            }
         }
    };`

**Comment by cgspine** [comment]
好像确实没什么问题，可以尝试下 `setProgress(progress, false)` 试试吗？我这边无法重现，怀疑是 
 animator 出了问题

**Comment by WinnieZy** [comment]
试过了，animate false进度就正常了。是要下载小文件的时候才会出现进度不正常的情况，你试试下载个10M的文件，我这里就是文件下载完成了但进度只更新了一点点

**Comment by cgspine** [comment]
试了下，应该是 message 发得太频繁， 而每次重新创建 animator 有点耗时，造成 MessageQueue 里有很多消息未处理。 可以尝试减小发送消息的数量。 多次`(int) (((float)count/length) * 100)` 的结果可能会相同，这个时候可以只发送一次消息就可以了。 组件这边后期会改掉频繁创建 animtor 的实现以避免这种情况

**Comment by WinnieZy** [comment]
是的，对progress值做了判断之后会好一点，但是下载更小的文件时（5M）仍然还是有进度更新不及时的问题，这里还是需要大佬修改一下

**Comment by WinnieZy** [comment]
是的，对progress值做了判断之后会好一点，但是下载更小的文件时（5M）仍然还是有进度更新不及时的问题，这里还是需要大佬修改一下
![image](https://user-images.githubusercontent.com/15833215/58450887-a0147d00-8143-11e9-8878-64edc1c78f15.png)

**Comment by cgspine** [comment]
可升级至1.3.1，解决了动画频繁创建的问题
