### ISSUE TITLE
QMUIRoundButton 背景变成黑色

### ISSUE THREAD

**Issue by a251115100** [Tencent/QMUI_Android#604]
### 运行环境 ###

- [x] 设备型号：如：`Redmi Note 4X`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `3.3.2`
- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###
背景变成黑色

**Comment by cgspine** [comment]
设置了 qmui_backgroundColor ?

**Comment by a251115100** [comment]
找到原因了,不是QMUI的问题,是com.google.android:flexbox背景变成黑色,sorry
