### ISSUE TITLE
QMUIFragment 与 ViewPage 配合使用的问题

### ISSUE THREAD

**Issue by entropyfeng** [Tencent/QMUI_Android#605]
### 运行环境 ###

- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###
QMUITabSegement 中 normalIcon   与selectedIcon 没有set 选项。
当 QMUITabSegement 与 ViewPage 配合时，在调用setupWithViewPager 方法时，将清除原来的TabItem，这时可以在适配器中为每一个item 添加标题来解决这个问题。
但是图片只能通过 反射的方式为TabItem 添加select 与 normal 效果
#### 问题截图 ####

![image](https://user-images.githubusercontent.com/22837042/58177640-56f1a280-7cd7-11e9-8184-268494826df6.png)

**Comment by cgspine** [comment]
可以通过 replaceTab 把整个 tabItem 换掉
