### ISSUE TITLE
请问怎么修改PullToRefreshLayout圆圈的颜色

### ISSUE THREAD

**Issue by YellowDoing** [Tencent/QMUI_Android#606]
请问怎么修改下拉刷新控件PullToRefreshLayout那个转动的圆圈的颜色，尝试在style设置很多属性都不行，请问具体怎么设置。
谢谢。

**Comment by cgspine** [comment]
可以通过覆写 createRefreshView，返回 RefreshView(context)，通过 RefreshView.setColorSchemeColors 设置颜色

**Comment by YellowDoing** [comment]
OK了
