### ISSUE TITLE
QMUITabSegment点击问题

### ISSUE THREAD

**Issue by Theoneee** [Tencent/QMUI_Android#608]
在设置QMUITabSegment.OnTabClickListener后，点击下边文字部分是无法触发的。

TabAdapter里bind方法里是对QMUITabSegment.TabItemView view设置的点击监听。
按理来说点击下面的文字部分也是可以触发的。可是并没有。

**Comment by cgspine** [comment]
我测试Demo没有问题啊，是否是你的view底部被其它透明view挡住了？

**Comment by Theoneee** [comment]
我把QMIUTopLayout写到前面了。。。
