### ISSUE TITLE
startFragmentAndDestroyCurrent异常问题

### ISSUE THREAD

**Issue by kakarrot** [Tencent/QMUI_Android#613]
### 运行环境 ###

- [x] 设备型号：如：`Genymotion 模拟器`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `3.4.1`
- [x] QMUI Android 版本：`1.x`

### 具体问题描述 ###

QMUIFragment 调用 startFragmentAndDestroyCurrent() 方法问题

情景描述：
1>. MainActivity 加载 QMUIFragment A ，通过 startFragment() 打开 B
2>. B 再通过startFragmentAndDestroyCurrent()方法 打开 C , 
3>. 然后在C 页面点击返回按钮 调用popBackStack()，点击第一次没反应（还是在C页面），点击第二次会关闭 MainActivity（退出app）。

补充：如果在第3>步中使用手势滑动返回，可以正常返回，不会出现上述问题。

#### Layout Inspector 文件([如何获取]
因为并非某个具体页面的显示问题，所以不太好提供li 文件。

#### 异常日志（堆栈） ####

调用startFragmentAndDestroyCurrent 会报以下异常：

I/QMUIFragment: SettingFragment onCreateView: mBackStackIndex = 1
W/System.err: java.lang.NoSuchFieldException: No field cmd in class Landroidx/fragment/app/FragmentTransaction$Op; (declaration of 'androidx.fragment.app.FragmentTransaction$Op' appears in /data/app/com.imoji.quickcash-Sl2O8wa2Tkaw9kC5u9t3tQ==/base.apk)
W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
W/System.err:     at com.qmuiteam.qmui.arch.QMUIFragmentActivity$1.handle(QMUIFragmentActivity.java:117)
W/System.err:     at com.qmuiteam.qmui.arch.Utils.findAndModifyOpInBackStackRecord(Utils.java:173)
W/System.err:     at com.qmuiteam.qmui.arch.QMUIFragmentActivity.startFragmentAndDestroyCurrent(QMUIFragmentActivity.java:112)
W/System.err:     at com.imoji.quickcash.ui.user.SettingFragment$initView$2.onClick(SettingFragment.kt:26)
W/System.err:     at android.view.View.performClick(View.java:6256)
W/System.err:     at android.view.View$PerformClick.run(View.java:24697)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err:     at android.os.Looper.loop(Looper.java:164)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)

2019-05-31 19:34:24.655 9476-9476/com.imoji.quickcash W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
W/System.err: java.lang.NoSuchFieldException: No field cmd in class Landroidx/fragment/app/FragmentTransaction$Op; (declaration of 'androidx.fragment.app.FragmentTransaction$Op' appears in /data/app/com.imoji.quickcash-Sl2O8wa2Tkaw9kC5u9t3tQ==/base.apk)
W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
W/System.err:     at com.qmuiteam.qmui.arch.QMUIFragmentActivity$1.handle(QMUIFragmentActivity.java:117)
W/System.err:     at com.qmuiteam.qmui.arch.Utils.findAndModifyOpInBackStackRecord(Utils.java:173)
W/System.err:     at com.qmuiteam.qmui.arch.QMUIFragmentActivity.startFragmentAndDestroyCurrent(QMUIFragmentActivity.java:112)
W/System.err:     at com.imoji.quickcash.ui.user.SettingFragment$initView$2.onClick(SettingFragment.kt:26)
W/System.err:     at android.view.View.performClick(View.java:6256)
W/System.err:     at android.view.View$PerformClick.run(View.java:24697)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
W/System.err:     at android.os.Looper.loop(Looper.java:164)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)

2019-05-31 19:34:24.657 9476-9476/com.imoji.quickcash W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)

**Comment by kakarrot** [comment]
使用的是AndroidX 版本

**Comment by kakarrot** [comment]
![image](https://user-images.githubusercontent.com/5986919/58705162-f05c3b00-83e0-11e9-8c47-4e5f1fdce88b.png)
QMUIFragmentActivity 好像在androidX 里面这样调用有问题。。。

**Comment by cgspine** [comment]
最新版 Android X 改了方法名，导致反射失败

**Comment by cgspine** [comment]
可升级到 0.5.0
