### ISSUE TITLE
java.lang.UnsupportedOperationException  Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f0301cb a=4}

### ISSUE THREAD

**Issue by Evatruy** [Tencent/QMUI_Android#616]
### 运行环境 ###

- [x] 设备型号：如：`荣耀 STF AL00`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `4.4`
- [x] QMUI Android 版本：`Android 9,level 28`

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/37918185/59010464-f2504f00-8863-11e9-950d-f5d1fb4f1d2d.png)

**Comment by cgspine** [comment]
没有用 QMUI 提供的 theme ?

**Comment by Evatruy** [comment]
> 没有用 QMUI 提供的 theme ?

必须采用qmui theme才可使用？

**Comment by Evatruy** [comment]
> > 没有用 QMUI 提供的 theme ?
> 
> 必须采用qmui theme才可使用？

复看代码，发现是已使用theme基础上出现此错误

**Comment by cgspine** [comment]
必须使用 QMUI theme 才行， 可以检查下是不是弹出 dialog 的 activity 的 theme 是独立与 application 的？或者是用了 appliactionContext ?
