### ISSUE TITLE
支持DataBinding的问题

### ISSUE THREAD

**Issue by whataa** [Tencent/QMUI_Android#618]
请问可以支持下DataBinding吗？

目前由于`QMUIActivity`里对contentView包裹了一层，导致使用 `DataBindingUtil.setContentView` 的形式时，其内部通过R.id.content得到的child并非传入的原始view而异常：
```
java.lang.RuntimeException: view must have a tag
```

**Comment by whataa** [comment]
浏览了下其它相关issue，作者似乎没有该计划

**Comment by Tinaltt** [comment]
请问有什么临时解决方案么？
