### ISSUE TITLE
没有在1.3.1版本中找到 QMUIPullRefreshLayout 的 setRefreshDirectly 方法

### ISSUE THREAD

**Issue by spysoos** [Tencent/QMUI_Android#621]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `4.10.1`
- [x] QMUI Android 版本：`1.3.1`

### 具体问题描述 ###
看更新日志说已经添加，把源码下下来却没找到
没有在1.3.1版本中找到 QMUIPullRefreshLayout 的 setRefreshDirectly 方法

**Comment by cgspine** [comment]
抱歉，release 的文案有误，我修正下，应该是 setToRefreshDirectly

**Comment by spysoos** [comment]
话说，QMUIPullRefreshLayout 能控制TargetView下拉的阻尼效果吗？ 不要跟着手指直上直下的,自然的效果应该是越下拉越难拉才对吧

**Comment by cgspine** [comment]
目前只提供了 `setDragRate` 来控制下拉容易程度

**Comment by spysoos** [comment]
对，就是它，要的就是这个效果 完结撒花！

**Comment by spysoos** [comment]
尴尬，阻尼的效果是有了，但是列表往下滚动一段后，再往上滚动，还没滚动到顶部，就触发下拉刷新事件了，我和demo用的都是recyclerview 可demo没有这个情况... 
![TIM截图20190614162515](https://user-images.githubusercontent.com/982866/59495038-1265bb00-8ec1-11e9-8926-e5360818d88d.png)


设置了 pullRefresh.setDragRate(0.5f);

**Comment by spysoos** [comment]
不设置 pullRefresh.setDragRate(0.5f); 是没有问题的

**Comment by cgspine** [comment]
RecyclerView 有被其它容器嵌套吗？ 如果有，则需调用 setChildScrollUpCallback，使用 RecyclerView 来作为判断依据

**Comment by spysoos** [comment]
QMUIPullRefreshLayout 包含 FrameLayout, FrameLayout包含RecyclerView , 设置setChildScrollUpCallback 后确实可以了，谢谢。
