### ISSUE TITLE
 QMUIVerticalTextView输入Emoji乱码

### ISSUE THREAD

**Issue by Cazaea** [Tencent/QMUI_Android#623]
### 运行环境 ###

- [x] 设备型号：`HUAWEI P10`
- [x] 设备系统版本： `Android 9`
- [x] Gradle 版本： `3.3.1`
- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###
QMUIVerticalTextView输入Emoji乱码
#### 问题截图 ####
![Emoji](https://user-images.githubusercontent.com/16607724/59574101-8d5cea80-90e8-11e9-82ee-eb1ed648cd56.jpg)

**Comment by chanthuang** [comment]
感谢反馈。v1.3.3 已解决

**Comment by Cazaea** [comment]
似乎没有效果。

**Comment by chanthuang** [comment]
> 似乎没有效果。

依赖的是 qmui 1.3.3 版本吗？存在什么问题？

**Comment by Cazaea** [comment]
我是Clone的项目，直接将Demo运行在手机上

**Comment by Cazaea** [comment]
我看到您这边只是更爱了继承的父类：由TextView改为AppCompatTextView

**Comment by chanthuang** [comment]
https://github.com/Tencent/QMUI_Android/commit/a70475d8a9136a6b90c89f43117f92e274fc4b0a 是这个 commit

**Comment by Cazaea** [comment]
OK。
问题解决了~
只是主分支合并拉取有点慢~
