### ISSUE TITLE
关于重用QMUIFragment的Bug!

### ISSUE THREAD

**Issue by spysoos** [Tencent/QMUI_Android#624]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 5x`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `5.4.1`
- [x] QMUI Android 版本：`1.3.1`

### 具体问题描述 ###
以 Demo 中的 QDTabSegmentFragment类举例。
![TIM截图20190618113628](https://user-images.githubusercontent.com/982866/59651689-5b698800-91bd-11e9-9e7d-7d2441ed08fc.png)

我把 QDTabSegmentFixModeFragment 保存在变量中，想下次点击 GroupListView 的第一项时 重复利用这个Fragment，具体看9行。当点击GroupListView第一项进入 QDTabSegmentFixModeFragment 然后再按返回键返回 QDTabSegmentFragment，再次点击GroupListView第一项进入 QDTabSegmentFixModeFragment，再按返回键返回 QDTabSegmentFragment 这个操作能正常相应。
问题再于，当我进入 QDTabSegmentFixModeFragment  后，当我把按返回键返回换成侧滑返回QDTabSegmentFragment时，能正常返回，但是再次点击GroupListView第一项进入 QDTabSegmentFixModeFragment时，QDTabSegmentFixModeFragment出现了白屏

#### 问题截图 ####

![device-2019-06-18-114444](https://user-images.githubusercontent.com/982866/59652071-cd8e9c80-91be-11e9-8399-f8c961224d0c.gif)

**Comment by cgspine** [comment]
因为没考虑过这种复用，手势返回后的状态没有清除。 这种有复用的场景？

**Comment by spysoos** [comment]
@cgspine 理论上，在用户看来，侧滑返回应该等同于按返回键返回吧？按返回键返回再复用进入能正常使用，侧滑返回不能，会不会怪怪的？

**Comment by cgspine** [comment]
在 onDestroy 里释放 cache view 等信息就能保证流程正常，但是这样的复用，是绝对复用不到 UI 的。google 官方其实对 View 的生命周期限制得更短，所以这样做也是符合官方要求的。

**Comment by spysoos** [comment]
OK 理解
