### ISSUE TITLE
SmartRefreshLayout 刷新库和QMUIContinuousNestedScrollLayout配合使用时有显示不完全情况

### ISSUE THREAD

**Issue by onlywsw** [Tencent/QMUI_Android#628]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by onlywsw** [comment]
QMUIPullRefreshLayout和QMUIContinuousNestedScrollLayout 配合使用,在下拉属性过程中,没有滑动到顶部,已经开始刷新了

**Comment by cgspine** [comment]
```java
mPullRefreshLayout.setChildScrollUpCallback(new QMUIPullRefreshLayout.OnChildScrollUpCallback() {
            @Override
            public boolean canChildScrollUp(QMUIPullRefreshLayout parent, @Nullable View child) {
                return mContinuousLayout.getCurrentScroll() > 0;
            }
});
```
当前 `QMUIPullRefreshLayout` 补上这个就可以正常工作。

**Comment by onlywsw** [comment]
QMUIPullRefreshLayout和QMUIContinuousNestedScrollLayout 配合使用OK了
