### ISSUE TITLE
BottomListSheetBuilder 在列表为空的情况下无法关闭dialog

### ISSUE THREAD

**Issue by ShenHaiyi** [Tencent/QMUI_Android#629]
### 运行环境 ###

- [x] 设备型号：`红米note7`
- [x] 设备系统版本：`Android 9.0`
- [x] Gradle 版本：`3.4.1`
- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###
BottomListSheetBuilder在没有addItem()情况下，调用show()，dialog无法关闭

**Comment by chanthuang** [comment]
感谢你的反馈。下个版本会修复。另一方面，没有任何 item 的一个 BottomSheet，是否应该考虑不让它 show 出来？

**Comment by Theoneee** [comment]
对啊。没有item。显示出来干嘛。给用户看有什么意义。虽然这是一个空间的问题。但是作为开发者也应该让这种问题杜绝在源头。
