### ISSUE TITLE
QMUI_Android编译：Cannot resolve symbol ‘R’

### ISSUE THREAD

**Issue by Tianyijian** [Tencent/QMUI_Android#634]
### 具体问题描述 ###
从github上克隆了整个QMUI_Android项目，未做任何改动，Android studio版本为3.1.1，安装了其需要的gradle版本等，在1.x分支上可以成功build，但是进入qmuidemo，每个类都报错：Cannot resolve symbol ‘R’。
我只是想更好的参考demo代码，应该怎么处理？
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/23497428/60340193-7fa73f00-99dd-11e9-8393-1d1b618372f0.png)

**Comment by cgspine** [comment]
可以尝试  Build->Clean Project
