### ISSUE TITLE
QMUIStickySectionLayout加锁失效？

### ISSUE THREAD

**Issue by A-Heavy-Rain** [Tencent/QMUI_Android#636]
### 运行环境 ###

- [x] 设备型号：如：`MI9`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `3.2.0`
- [x] QMUI Android 版本：`1.3.3`

#### 问题截图 ####
![WechatIMG2](https://user-images.githubusercontent.com/20280717/60562038-7248d680-9d88-11e9-8549-64fb035d7f21.png)

  section.setExistAfterDataToLoad(true);
  section.setExistBeforeDataToLoad(true);
这两个方法取消注释掉后为何未出现截图上的情况？按我对文档的理解Section3处于向后加载更多的时候是不会显示出来Section4的。
文档原话：加载更多会锁住之前或之后的内容。例如，如果是向后加载更多，那么加载期间，无法滚动到加载 section 之后的 section。 这样可以保证用户不会跳过加载中的内容。
最近有类似需求可能会用到，麻烦有时间回答下，感谢！

**Comment by A-Heavy-Rain** [comment]
![1065C19E-FACB-4A57-B64D-536782ED8635](https://user-images.githubusercontent.com/20280717/60569098-12aaf500-9da1-11e9-96c3-5a84b687b624.png)
截图是我修改demo中的，也就是第一次时候延迟0秒finishLoadMore，以后都是3秒，existMoreData都设置为true,然后慢慢滑动是没有问题的会被锁住，但快速滑动时候会先闪一下section2,然后在刷新成正常展示section1,并且loadMore仅被调用一次。

**Comment by cgspine** [comment]
第一次 set 内部确实没有处理 lock, 目前可以在构造 QMUISection 时通过参数控制是否lock，或者通过 scrollToSectionHeader 滚动到一个目标 section。 这里可以优化一下

**Comment by cgspine** [comment]
快速闪 section2 我还没重现到

**Comment by A-Heavy-Rain** [comment]
<img width="604" alt="A375CE80-7246-41AC-860A-794371E4D052" src="https://user-images.githubusercontent.com/20280717/60770768-3bb8e600-a111-11e9-8217-6a936e069e80.png">
初始化lock传true，demo中点进去是空白页面。

**Comment by A-Heavy-Rain** [comment]
![Screenshot_2019-07-07-23-47-03-485_com qmuiteam qmuidemo](https://user-images.githubusercontent.com/20280717/60770811-a2d69a80-a111-11e9-94ce-1088745a731c.png)

**Comment by cgspine** [comment]
你把所有的都lock了，需要至少有一个不是lock的

**Comment by A-Heavy-Rain** [comment]
![企业微信截图_9ce85126-e2af-4899-b4ff-c32cb691f936](https://user-images.githubusercontent.com/20280717/60937501-3fac5a00-a303-11e9-8989-982ed89dc99c.png)
只把第一个不加锁，但是展现出效果是只有第一个section会被加锁,之后不会锁住。依然有第一张截图的情况，但会有loadmore回调。

我想实现的效果是，比如有10章节课程，每个章节有100节课，每次请求20条数据，第一次请求第一章节1-20条，然后上拉时第二次自动加载接下来的21-40条条数据，在加载21-40条数据时应处于加锁状态。所以会存在每个section最初都会是加锁状态，请求完当前section数据才会解锁，QMUIStickySectionLayout是否能处理这种情况？或者该如何处理比较好？

**Comment by A-Heavy-Rain** [comment]
:thumbsup: 拉取最新代码，问题已修复。
