### ISSUE TITLE
版本1.1.11,EditText的光标颜色不是colorAccent!!!

### ISSUE THREAD

**Issue by lydlovexyz** [Tencent/QMUI_Android#640]
如题

**Comment by chanthuang** [comment]
是的，QMUI 将光标颜色置为与文字颜色一样。如要修改，应该用指定一个 ShapeDrawable 给 textCursorDrawable 属性。见源码 [theme](https://github.com/Tencent/QMUI_Android/blob/1.x/qmui/src/main/res/values/qmui_themes_compat.xml#L338)

**Comment by lydlovexyz** [comment]
谢大佬

**Comment by lydlovexyz** [comment]
改了以后只修改了Editext的光标颜色,QMUIDialog里边的EditText光标颜色并没有修改

**Comment by chanthuang** [comment]
感谢反馈，刚刚发布了 1.3.4 修改该问题。

**Comment by lydlovexyz** [comment]
感谢大佬

**Comment by Android-KJY** [comment]
EditTextDialogBuilder  光标颜色跟文字颜色还是不一致！

**Comment by Android-KJY** [comment]
2.0的版本

**Comment by cgspine** [comment]
Dialog 传递的 theme 并不是 App 的主 theme，会被覆盖， 可以通过 create 传递一个 theme，通过它来覆盖，可以参考 Demo 里的 DialogTheme2 使用
