### ISSUE TITLE
QMUIQQFaceView 显示span问题

### ISSUE THREAD

**Issue by chen188669** [Tencent/QMUI_Android#642]
### 运行环境 ###

- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###
QMUIQQFaceView 显示span显示不全 入xia下图
上面是QMUIQQFaceView 下面是textview 。span效果是通过匹配循环添加的，两种span
#### 问题截图 ####

![4ad01e52cb33f81cf81b3ddbb68465d](https://user-images.githubusercontent.com/31298181/60713044-dddaa180-9f4a-11e9-85b3-e17d6e8fc0b8.jpg)

**Comment by chen188669** [comment]
两个控件用的同一个spannablestring

**Comment by cgspine** [comment]
可以贴一下代码吗？

**Comment by chen188669** [comment]
public SpannableString setSpan(CharSequence s){
        this.source = s.toString();
        int fromIndex = 0;
        SpannableString sp = new SpannableString(source);

        fromIndex = 0;

        for (int i = 0; i < atList.size(); i++) {
            String atStr = atList.get(i);
            sp.setSpan(new QMUITouchableSpan(Color.RED, Color.BLACK, Color.YELLOW, Color.GREEN) {
                @Override
                public void onSpanClick(View widget) {
                    if (onSpanClick != null){
                        onSpanClick.atClick(atStr);
                    }
                }
            }, source.indexOf(atStr,fromIndex), source.indexOf(atStr,fromIndex) + atStr.length(), Spanned.SPAN_INCLUSIVE_EXCLUSIVE);
            fromIndex = source.indexOf(atStr,fromIndex) + atStr.length();
        }
        fromIndex = 0;
//        String topicStr1 = "#这是一个话题 ";
//        sp.setSpan(new QMUITouchableSpan(Color.RED, Color.BLACK, Color.YELLOW, Color.GREEN) {
//            @Override
//            public void onSpanClick(View widget) {
//                if (onSpanClick != null){
//                    onSpanClick.topicClick(topicStr1);
//                }
//            }
//        }, source.lastIndexOf(topicStr1), source.lastIndexOf(topicStr1) + topicStr1.length(), Spanned.SPAN_INCLUSIVE_EXCLUSIVE);

        for (int i = 0; i < topicList.size(); i++) {
            MyLog.d("topicList : "+i);
            String topicStr = topicList.get(i);
            sp.setSpan(new QMUITouchableSpan(Color.RED, Color.BLACK, Color.YELLOW, Color.GREEN) {
                @Override
                public void onSpanClick(View widget) {
                    if (onSpanClick != null){
                        onSpanClick.topicClick(topicStr);
                    }
                }
            }, source.indexOf(topicStr,fromIndex), source.indexOf(topicStr,fromIndex) + topicStr.length(), Spanned.SPAN_INCLUSIVE_EXCLUSIVE);
            fromIndex = source.indexOf(topicStr,fromIndex) + topicStr.length();
        }
        return sp;
    }


这是spannableString代码  atlist 和topiclist是两个List<String>  设置就是一个setText（）

**Comment by cgspine** [comment]
知道原因了，SpannableString.getSpan 返回结果是根据用户setSpan的顺序，而不是根据 index 排序的，我组件里需要排序一次

**Comment by chen188669** [comment]
对，现在是这样，spannablestring只能按index顺序显示，对于类似这种不确定的顺序的需求就需要把所有index排序再显示，这个问题下个版本会修复吗？

**Comment by cgspine** [comment]
可升级到1.4.0
