### ISSUE TITLE
继承BaseFragmentActivity回退到桌面再进入app无法正常popBackStack，变成退出app

### ISSUE THREAD

**Issue by sundaylol** [Tencent/QMUI_Android#644]
### 运行环境 ###

- [x] 设备型号：如：`Realme X青春版`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `5.1.1`
- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###
这边就是继承了BaseFragmentActivity的activity回退到桌面后再进入activity再点击按钮执行popBackStack无法回退，变成了退出app

#### 问题截图 ####
![1562835309184](https://user-images.githubusercontent.com/16680840/61038153-153fc700-a3ff-11e9-9007-b95ed474d83b.jpg)
![1562835257389](https://user-images.githubusercontent.com/16680840/61038154-153fc700-a3ff-11e9-9222-5f3869b2be4e.jpg)

**Comment by Theoneee** [comment]
```
 if (savedInstanceState == null) {
            BaseFragment fragment = getBaseFragment();
            getSupportFragmentManager()
                    .beginTransaction()
                    .add(getContextViewId(), fragment, fragment.getClass().getSimpleName())
                    .addToBackStack(fragment.getClass().getSimpleName())
                    .commit();
        }
```

**Comment by Theoneee** [comment]
要做一下判断。

**Comment by sundaylol** [comment]
> 要做一下判断。

这个是其中一个，我是做了判断的。

**Comment by cgspine** [comment]
当前只有一个 Activity且 Activity 里只有一个 Fragment ？

**Comment by sundaylol** [comment]
> 当前只有一个 Activity且 Activity 里只有一个 Fragment ？

找到

> 当前只有一个 Activity且 Activity 里只有一个 Fragment ？

找到问题了，原先入口activity设置成了singleIntance的，我改成singletask之后就OK了。
