### ISSUE TITLE
你们的官网又挂了

### ISSUE THREAD

**Issue by AwakenDragon** [Tencent/QMUI_Android#646]
访问你们的官网https://qmuiteam.com/，长时间没有响应，然后就直接挂了

**Comment by chanthuang** [comment]
感谢反馈，正在处理中。
如果需要访问文档，可以访问 [wiki](https://github.com/Tencent/QMUI_Android/wiki)。

**Comment by MoLice** [comment]
已恢复，感谢反馈。
