### ISSUE TITLE
QMUIFragment 的问题

### ISSUE THREAD

**Issue by Theoneee** [Tencent/QMUI_Android#648]
我不知道这个是QMUIFragment的问题还是我的写法有问题。

情况如下：
最外层IndexFramgent的布局QMUIViewPager+QMUISegment。
![1563421412061](https://user-images.githubusercontent.com/32156330/61427721-cf7c8480-a951-11e9-9fba-ad8fb8d87238.png)

然后在CategoryFragment里也是同样的，在CategoryItemFragment点击内容跳转后滑动返回时会出现CategoryItemFragment消失，滑动结束后会再出现。
![1563421419377](https://user-images.githubusercontent.com/32156330/61427841-326e1b80-a952-11e9-9f56-877492a9973e.png)

但是从HomeFragment跳转过去滑动返回的就不会出现这个问题。
![1563421406000](https://user-images.githubusercontent.com/32156330/61427892-5fbac980-a952-11e9-9536-86ada8342300.png)

**Comment by yuwoquan** [comment]
我也会出现这样子，你解决了吗

**Comment by Theoneee** [comment]
> 我也会出现这样子，你解决了吗

没有啊。都不知道啥问题导致的。

**Comment by cgspine** [comment]
QMUIFragment 的问题，我改改

**Comment by cgspine** [comment]
可升级 arch 到 0.6.1

**Comment by Theoneee** [comment]
好的。谢谢。
