### ISSUE TITLE
QMUIStickySectionLayout实现时库中缺少使用文档中提到的QMUISection.Model

### ISSUE THREAD

**Issue by xiaowang119** [Tencent/QMUI_Android#652]
是库又有更新，然后使用文档没更新吗，
但是提供的源码中又能找的这个接口
通过Gradle载入的库里却没有

**Comment by cgspine** [comment]
你的 QMUI 版本是多少？

**Comment by xiaowang119** [comment]
> 你的 QMUI 版本是多少？

根据readme文件中的使用方法
compile 'com.qmuiteam:qmui:1.0.6'

**Comment by Theoneee** [comment]
@xiaowang119  都1.4.0了。。。

**Comment by xiaowang119** [comment]
这样啊~~~~~~~，就说为什么直接下载的源包里能找到而通过Gradle下载的却没有，谢谢啦

**Comment by cgspine** [comment]
官网出了点问题，更新被回退了。所以你看到了很旧的版本，谢谢反馈。
