### ISSUE TITLE
建议完善一下各个组件的使用场景文档

### ISSUE THREAD

**Issue by zs1973** [Tencent/QMUI_Android#656]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by Theoneee** [comment]
基本上每个组件都做了一个使用示范吧。没有文档可以看Demo,可能某些细节确实没写出来，毕竟需求和组件的功能不可能完全吻合。
一个苹果，我给你示范的是洗了吃，有些人就喜欢削皮了吃。
