### ISSUE TITLE
下载失败是什么原因

### ISSUE THREAD

**Issue by gentlemanxzh** [Tencent/QMUI_Android#658]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `4.4`
- [x] QMUI Android 版本：`1.4.0`

### 具体问题描述 ###
Unable to resolve dependency for ':common@debug/compileClasspath': Could not download qmui.aar (com.qmuiteam:qmui:1.4.0)

**Comment by cgspine** [comment]
没有使用 jcenter 源？ 或者网络问题？

**Comment by gentlemanxzh** [comment]
有使用Jcenter源，网络应该也没有问题





------------------ 原始邮件 ------------------
发件人: "cgspine"<notifications@github.com>;
发送时间: 2019年7月28日(星期天) 晚上8:27
收件人: "Tencent/QMUI_Android"<QMUI_Android@noreply.github.com>;
抄送: "蒙其D龙"<1454561941@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Tencent/QMUI_Android] 下载失败是什么原因 (#658)




没有使用 jcenter 源？ 或者网络问题？
