### ISSUE TITLE
master分支与1.x分支的区别

### ISSUE THREAD

**Issue by WinnieZy** [Tencent/QMUI_Android#659]
master分支和1.x分支看起来好像都有在更新，想请问一下两条分支有什么区别，要用最新的代码的话应该clone哪一条分支？

**Comment by chanthuang** [comment]
请用 1.x 分支，目前用 gradle 引入的版本包括最新的 v1.4 都是基于 1. x 分支发布的。

**Comment by WinnieZy** [comment]
之前使用的是master分支，项目都迁到androidx了，1.x分支又用回com.android.support。。用1.x的话又要改回去。这样用着不太方便啊。。后面是都会基于1.x做更新吗？

**Comment by cgspine** [comment]
你是直接引入了源码？ 那你可以继续是用master. 1.x 的更新都会同步到 master 的。 不过master 是为 2.x 版本做准备，接口可能会有大的变动。

**Comment by WinnieZy** [comment]
准备换成离线依赖的方式，发现QMUITabSegment的实现1.x分支是落后与master的，在使用1.x分支发布之前为什么不先merge一下master的改动呢？现在1.x也有落后于master的部分，master也有落后与1.x分支的部分，用哪条分支都很奇怪，用发布的v1.4也需要回退部分修改（如QMUITabSegment）

**Comment by cgspine** [comment]
1.x 的修改都会merge回master，主干的无法merge回1.x了，因为主干全部换成androidx的了

**Comment by WinnieZy** [comment]
也就是1.x分支落后于master的部分不好做更新了吗？那就把1.x的修改merge回master然后用master作为发布分支呗，这样能保证master是最新的。请问什么时候能出一个融合master和1.x最新功能的版本？

**Comment by cgspine** [comment]
master 还准备大改 Popup浮层等，估计没那么快
