### ISSUE TITLE
qmuidemo.keystore not found

### ISSUE THREAD

**Issue by yetuweiba** [Tencent/QMUI_Android#664]
### 运行环境 ###

- [x] Gradle 版本：如 `5.5.1`
- [x] QMUI Android 版本：`1.4.0`

### 具体问题描述 ###
缺失keystore文件
编译报错信息: keystore file 'QMUI_Android-1.4.0/qmuidemo/qmuidemo.keystore' not found for signing config 'release'

这里消除编译错误的方式是将qmuidemo下的build.gradle中的13-19代码注释
```
//        release {
//            keyAlias properties.getProperty("RELEASE_KEY_ALIAS")
//            keyPassword properties.getProperty("RELEASE_KEY_PASSWORD")
//            storeFile file('qmuidemo.keystore')
//            storePassword properties.getProperty("RELEASE_STORE_PASSWORD")
//            v2SigningEnabled false
//        }
```

38行注释:
`//signingConfig signingConfigs.release`

之后根据android studio的提示对qmuidemo添加release的buildVariants来完成编译.

**Comment by Theoneee** [comment]
自己弄一个吧。

**Comment by cgspine** [comment]
这个只是我们 release 新的 apk 才用的，你编译 debug 包就行了吧

**Comment by yetuweiba** [comment]
这个错误是在下载release代码后,用android studio 打开工程时报出的错误.个人看代码的时候是不会release编译的.
