### ISSUE TITLE
关于嵌套滑动

### ISSUE THREAD

**Issue by yinxtno1** [Tencent/QMUI_Android#669]
### 运行环境 ###

- [x] 设备型号：无
- [x] 设备系统版本：无
- [x] Gradle 版本：无
- [x] QMUI Android 版本：无

### 具体问题描述 ###
我想问下QMUI 是自己实现的一套方案么，为什么不用 Google 的官方方案呢，这样做是有什么好处还是官方的嵌套滑动方案有什么问题
#### 问题截图 ####
无
#### Layout Inspector 文件([如何获取]
无

#### 异常日志（堆栈） ####
无

**Comment by Theoneee** [comment]
@yinxtno1  [QMUIContinuousNestedScrollLayout——连接滚动容器，专为文章详情页而生](http://blog.cgsdream.org/2019/06/10/qmuicontinuousnestedlayout/) 你可以看一下这个。
