### ISSUE TITLE
描述文件里写的支持api 14+,build.gradle定义的api 28...

### ISSUE THREAD

**Issue by syomie** [Tencent/QMUI_Android#670]
api 21 总是报错
` aapt : ERROR : In<declare-styleable> FontFamilyFont,unableto find attribute android:ttclndex. `` 
aapt : ERROR : In<declare-styleable> FontFamilyFont,unableto find attribute android:fontVariationSettings. ` 
是描述文件没更新么？

**Comment by cgspine** [comment]
可以看看这里：https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/205

api14+ 是最小支持api版本
