### ISSUE TITLE
QMUITopBar在Android5.0或5.1上时对状态栏的处理

### ISSUE THREAD

**Issue by Theoneee** [Tencent/QMUI_Android#672]
现在是在此两个版本上的处理是有一个层灰色的遮罩。可是在这两个版本，是可以通过`getWindow().setStatusBarColor(statusBarColor);`设置一下状态栏的背景颜色的。就目前来说，最低的也基本上也就是5.0了吧，以下的机型几乎已经没有了。如果在这个两个版本也加入遮罩是不是有点浪费这个功能了，让显示不那么舒服。当然，这是建立在TopBar背景是非白色情况下时，这里可以再加一个判断，如果为白色时就加上遮罩。

**Comment by cgspine** [comment]
`QMUIStatusBarHelper.translucent` 可以传第二个参数，决定5.x版本的背景色，如果topBar 非白色，那传透明就行。

**Comment by Theoneee** [comment]
@cgspine 我现在的处理办法是这样子的。。

1.Topbar加入渐变的Drawable背景，加入了一个`  <attr name="qmui_topbar_bg_drawable" format="reference"/>`，QMUI可以将这个放在`QMUITopBarStyle`里。
2.直接在`QMUIFragmentActivity  onCreate()`里判断

```
    if(isTranslucent()&& StatusBarUtil.isTranslucent(this)){
            QMUIStatusBarHelper.translucent(this, ContextCompat.getColor(this,R.color.qmui_config_color_transparent));
        }
```

```
public static boolean isTranslucent(Context context){
        Drawable bgDrawable;
        int bgColor;
        try {
            TypedArray array = context.obtainStyledAttributes(null, R.styleable.QMUITopBar, R.attr.QMUITopBarStyle, 0);
            bgColor = array.getColor(R.styleable.QMUITopBar_qmui_topbar_bg_color, Color.WHITE);
            bgDrawable = QMUIResHelper.getAttrDrawable(context, R.attr.qmui_topbar_bg_drawable);
            array.recycle();
        }catch (Exception e){
            bgDrawable = null;
            bgColor = Color.WHITE;
        }
       return null !=bgDrawable || bgColor!= Color.WHITE;
    }
```

当这两个条件满足时，直接让状态栏透明。当然，主题配置了是全局的，某些地方不需要，所以在`QMUIFragmentActivity`加入一个
```  protected boolean isTranslucent(){
        return true;
    }
```
让子类自己再确定。

**Comment by Theoneee** [comment]
或者再简单粗暴一点，直接给一个配置，主题里设置是否`isTranslucent`。

**Comment by cgspine** [comment]
这个做法会不会有点重？你这样必须遵循不同颜色的状态栏背景的Activity单独用单独的theme，配置单位是 Activity， 那同一个 Activity 下不同的 Fragment 要区分透明时怎么办？如果你的业务是以 Activity 为单位，倒是可以这么做。

**Comment by Theoneee** [comment]
如果是同一个Activity不同的Fragment下，就已经不是这个问题的原因了吧。就像我上次的那样，从一个有颜色背景的Fragment跳转到一个类似Demo里CollapsingTopBarFragment，这个布局的顶部图片已经延伸到了状态栏，当图片加载出来后，Flyme会根据当时状态栏那部分的颜色去判断切换白色还是黑色图标，如果切换成了黑色的了，返回时，就变不回去白色的了。这种我是把它另起一个Activity包裹。

（如果上面这个问题大佬有办法解决下面的就只看括号里的）

说回这个，如果不这么做，那我去适配5.x的不可能去一个个的Fragment去写吧（又或者把这个判断写到BaseFragment的onActivityCreated() 里面）。一般来说，一个APP的Topbar大多数都是一个色调，如果是白色的就不用区分透明了，非白色的Fragment里有需要分区透明的会导致上面的那个问题，所以一般还是另起一个Activity，再者是主页那种ViewPager+Tab的形式的，直接不要透明判断了。

**Comment by cgspine** [comment]
QMUIStatusBarHelper.translucent 方法放在 onViewCreated 或者 onActivityCreated 吧，每次返回时也会走进这两个方法更新状态栏颜色

**Comment by Theoneee** [comment]
对，放在那里面的。主要就是Flyme自动更换后就无法更改了。以前提过这个问题。不知道有没有办法解决。 @cgspine

**Comment by cgspine** [comment]
找到了台魅族 Android 7，自动更换后也可以更改，并且 Fragment 返回后也会被系统自动更换，只是系统更换的时机有点晚，Android 5 暂时还没找到魅族机器。

**Comment by Theoneee** [comment]
我的是Android 8.1 ，为啥我的不能。。

**Comment by Theoneee** [comment]
能否打个包，我测试一下。

**Comment by cgspine** [comment]
我就用 QMUIDemo 测试的， 在 BaseFragment 的 onActivityCreated 添加 QMUIStatusBarHelper.setStatusBarLightMode(getActivity());

**Comment by Theoneee** [comment]
代码控制的是可以的。但是问题就是那个界面我不知道是白色的还是深色的。所以我不能强制设置某个模式。当为白色时系统自动切换后，返回时就无法了。

换个测法：
把 QMUICollapsingTopBarLayout 的顶部图片随机放置白色的或者深色的图片。如何处理这种情况。

**Comment by cgspine** [comment]
这种情况只能是图片渲染时利用Palette去计算颜色，然后决定颜色，不过这样会耗费计算性能，一般都是在图片顶部加一层渐变的mask，避免纯白的图片出现，或者直接保留半透明的状态栏背景色。

**Comment by Theoneee** [comment]
可是那个半透明的状态栏背景加载那种地方就觉得不舒服。反正我是把它直接单独了一个Activity可以解决。让系统自己去更改。其他的机型好像那个地方会自动的补充一点颜色。不是纯白的感觉。
