### ISSUE TITLE
qmuidemo项目使用了什么路由框架吗

### ISSUE THREAD

**Issue by oscartorres9** [Tencent/QMUI_Android#673]
### 运行环境 ###

- [x] QMUI Android 版本：`1.4`

### 具体问题描述 ###
qmuidemo使用的是什么路由框架之类的东西吗？
如图这里的注解的用法，还有项目使用的框架结构是什么样的，好像所有UI都使用Fragement，抛弃了activity，有没有项目框架原理的文档可以看一下啊，纯看代码好晕啊

**Comment by oscartorres9** [comment]
补图

**Comment by Theoneee** [comment]
我也看不懂。但我也能用。因为只需要知道怎么用那些组件就行了。至于大佬的写法，可以去深入了解去学习。写法不一样而已，最终的目的是一样的。自己喜欢写就怎么来。注解这个你看看[lib](url)里写的。（注解一点都懂是咋回事）

**Comment by Theoneee** [comment]
也就是单Activity多fragment模式，你就把Fragment当成Activity用就行了。至于为什么这样，百度第一句话。

**Comment by oscartorres9** [comment]
弃坑了，kotlin下使用好多坑啊，各种类库里面的protected的方法在kotlin里面无法访问
Cannot access : it is public/*package*/ in
