### ISSUE TITLE
QMUITopBar在封装时使用include，导致AS预览出错

### ISSUE THREAD

**Issue by shejishi** [Tencent/QMUI_Android#674]
### 运行环境 ###

- [x] 设备型号：
- [x] 设备系统版本：
- [x] Gradle 版本：
- [x] QMUI Android 版本：`1.3.3`

#### 问题截图 [####]
[不使用include 的时候，布局预览正常](https://github.com/shejishi/ReadSourceCode/blob/master/raw/%E4%B8%8D%E9%80%82%E7%94%A8include.png)

[使用include的时候，预览背景直接显示一片黑](https://github.com/shejishi/ReadSourceCode/blob/master/raw/%E4%BD%BF%E7%94%A8include.png)

[封装的title组件](https://github.com/shejishi/ReadSourceCode/blob/master/raw/title.png)

**Comment by Theoneee** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<com.qmuiteam.qmui.widget.QMUITopBarLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/top_layout"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"/>
```

封装的里面直接这样写。

**Comment by Theoneee** [comment]
这还需要封装啥啊封装。style里直接就全局配置了。就算要写在base里，那就直接写在base里了。放在顶部它还要加一句 `android:fitsSystemWindows="true"`

**Comment by Theoneee** [comment]
AS预览也不出来啥玩意。就是一条线。
