### ISSUE TITLE
状态栏的颜色

### ISSUE THREAD

**Issue by LLXBH** [Tencent/QMUI_Android#676]
QMUIStatusBarHelper.translucent(this, getColor(R.color.colorPrimaryDark))
第二个属性是为状态栏设置颜色的吗？
如果是的话为啥我设置后无效，还是全透明的状态，它会在什么情况下失效？

**Comment by Theoneee** [comment]
你是放在哪里设置的。

**Comment by LLXBH** [comment]
> 你是放在哪里设置的。

Activity的 onCreate 里面的，然后activity 显示的是ViewPager

**Comment by Theoneee** [comment]
Activity的布局代码。还有你想实现什么样子的。你的需求是什么。

**Comment by LLXBH** [comment]
> Activity的布局代码。还有你想实现什么样子的。你的需求是什么。

ViewPager 是四个Fragment，里面的根布局都是 QMUIWindowInsetLayout，
有些页面的顶部是颜色，有些是图片。
想要的效果就是状态栏是个半透明的颜色，然后切换 Fragment 不会因为颜色过深或者太浅影响看不清状态栏的字

**Comment by Theoneee** [comment]
Demo里 QDFitSystemWindowViewPager 不就是你要的效果嘛
