### ISSUE TITLE
QMUITopBar QMUITopBarLayout title遮挡

### ISSUE THREAD

**Issue by huguoyan1989** [Tencent/QMUI_Android#677]
### 运行环境 ###

- [x] 设备型号：如：`小米8 荣耀8c`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `3.4.2`
- [x] QMUI Android 版本：`1.2.0`

### 具体问题描述 ###
使用QMUITopBar 设置android:fitsSystemWindows="true"左侧返回按钮显示正常，title没有下移被顶部遮挡
使用QMUITopBarLayout 设置android:fitsSystemWindows="true"左侧返回按钮和title都下移至topbar底部，被底部遮挡一半

**Comment by Theoneee** [comment]
布局发出来看看。

**Comment by huguoyan1989** [comment]
> 布局发出来看看。

<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/qmui_config_color_white"
    tools:context="com.hbis.ttie.mall.login.LoginActivity">

    <com.qmuiteam.qmui.widget.QMUITopBarLayout
        android:layout_width="0dp"
        android:layout_height="?attr/qmui_topbar_height"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:id="@+id/login_topbar">

    </com.qmuiteam.qmui.widget.QMUITopBarLayout>

    <ImageView
        android:id="@+id/login_image"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@mipmap/ic_launcher"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.2" />

    <Button
        android:id="@+id/login_userName_btn"
        android:layout_width="120dp"
        android:layout_height="wrap_content"
        android:background="@drawable/login_button_selector"
        android:text="账号登录"
        android:textSize="18sp"
        app:layout_constraintHorizontal_chainStyle="packed"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toLeftOf="@id/login_phone_btn"
        app:layout_constraintTop_toBottomOf="@id/login_image" />

    <Button
        android:id="@+id/login_phone_btn"
        android:layout_width="120dp"
        android:layout_height="wrap_content"
        android:background="@drawable/login_button_selector"
        android:text="手机号登录"
        android:textSize="18sp"
        app:layout_constraintLeft_toRightOf="@id/login_userName_btn"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="@id/login_userName_btn" />

    <EditText
        android:id="@+id/login_userName"
        android:layout_width="0dp"
        android:layout_height="40dp"
        android:layout_marginLeft="30dp"
        android:layout_marginTop="15dp"
        android:layout_marginRight="30dp"
        android:background="@color/transparent"
        android:hint="请输入手机号码"
        android:inputType="phone"
        android:maxLines="1"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@id/login_userName_btn" />

    <TextView
        android:layout_width="0dp"
        android:layout_height="1dp"
        app:layout_constraintTop_toBottomOf="@id/login_userName"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:layout_marginTop="5dp"
        android:layout_marginLeft="30dp"
        android:layout_marginRight="30dp"
        android:background="#eeeeee"
        android:id="@+id/login_userName_split"/>

    <com.hbis.ttie.mall.login.ui.view.GradientColorTextButton
        android:layout_width="wrap_content"
        android:layout_height="30dp"
        app:layout_constraintBottom_toBottomOf="@id/login_userName"
        app:layout_constraintRight_toRightOf="@id/login_userName"
        app:layout_constraintTop_toTopOf="@id/login_userName"
        android:background="@drawable/login_captcha_layer"
        android:text="获取验证码"
        android:textSize="13sp"
        android:id="@+id/login_captcha_btn"/>

    <EditText
        android:id="@+id/login_password"
        android:layout_width="0dp"
        android:layout_height="40dp"
        android:layout_marginLeft="30dp"
        android:layout_marginRight="30dp"
        android:layout_marginTop="5dp"
        android:background="@color/transparent"
        android:hint="请输入密码"
        android:inputType="textPassword"
        android:maxLines="1"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@id/login_userName_split" />

    <TextView
        android:layout_width="0dp"
        android:layout_height="1dp"
        app:layout_constraintTop_toBottomOf="@id/login_password"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:layout_marginLeft="30dp"
        android:layout_marginRight="30dp"
        android:layout_marginTop="5dp"
        android:background="#eeeeee"
        android:id="@+id/login_password_split"/>

    <CheckBox
        android:id="@+id/login_auto"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:buttonTint="@color/blue"
        android:checked="true"
        android:text="自动登录"
        app:layout_constraintLeft_toLeftOf="@id/login_password"
        app:layout_constraintTop_toBottomOf="@id/login_password_split"
        android:visibility="gone"/>

    <Button
        android:id="@+id/login_submit"
        android:layout_width="0dp"
        android:layout_height="40dp"
        android:layout_marginLeft="30dp"
        android:layout_marginTop="5dp"
        android:layout_marginRight="30dp"
        android:background="@drawable/button_change"
        android:text="登录"
        android:textColor="@color/qmui_config_color_white"
        android:textSize="18sp"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@id/login_auto" />

    <TextView
        android:id="@+id/login_register"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="5dp"
        android:text="免费注册"
        android:textColor="@color/blue"
        app:layout_constraintLeft_toLeftOf="@id/login_submit"
        app:layout_constraintTop_toBottomOf="@id/login_submit" />

    <TextView
        android:id="@+id/login_forget"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="5dp"
        android:text="忘记密码?"
        android:textColor="@color/blue"
        app:layout_constraintRight_toRightOf="@id/login_submit"
        app:layout_constraintTop_toBottomOf="@id/login_submit" />

</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by Theoneee** [comment]
这个布局没用过。。不过看你这想要的效果。很简单。要不你换一个布局。最外层参照Demo里写的。TopBar下面的你自己想什么写就怎么写。

**Comment by huguoyan1989** [comment]
> 这个布局没用过。。不过看你这想要的效果。很简单。要不你换一个布局。最外层参照Demo里写的。TopBar下面的你自己想什么写就怎么写。

就是说不适配ConstraintLayout这种布局呗，还是希望能适配这种布局，我有很多复杂的页面还是需要这种布局的

**Comment by cgspine** [comment]
你暂时可以参考 1.x 分支的 QMUIWindowInsetLayout2 写一个，代码很简单，这个之后版本才会带上

**Comment by huguoyan1989** [comment]
> 你暂时可以参考 1.x 分支的 QMUIWindowInsetLayout2 写一个，代码很简单，这个之后版本才会带上

某些特殊原因，暂时没办法使用QMUIWindowInsetLayout

**Comment by cgspine** [comment]
你可以参考里面的逻辑给你自己的 Layout 补充 QMUIWindowInsetLayout2 的逻辑的，主要逻辑都被抽取到了 QMUIWindowInsetHelper 里，因此 QMUIWindowInsetLayout2 的逻辑是比较简单的

**Comment by huguoyan1989** [comment]
> 你可以参考里面的逻辑给你自己的 Layout 补充 QMUIWindowInsetLayout2 的逻辑的，主要逻辑都被抽取到了 QMUIWindowInsetHelper 里，因此 QMUIWindowInsetLayout2 的逻辑是比较简单的

<com.hbis.ttie.mall.util.ui.WindowInsetLayoutConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/qmui_config_color_white"
    tools:context="com.hbis.ttie.mall.login.LoginActivity">

    <com.qmuiteam.qmui.widget.QMUITopBarLayout
        android:layout_width="0dp"
        android:layout_height="?attr/qmui_topbar_height"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:id="@+id/login_topbar"
        android:fitsSystemWindows="true">

    </com.qmuiteam.qmui.widget.QMUITopBarLayout>

    <ImageView
        android:id="@+id/login_image"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@mipmap/ic_launcher"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.2" />

    <Button
        android:id="@+id/login_userName_btn"
        android:layout_width="120dp"
        android:layout_height="wrap_content"
        android:background="@drawable/login_button_selector"
        android:text="账号登录"
        android:textSize="18sp"
        app:layout_constraintHorizontal_chainStyle="packed"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toLeftOf="@id/login_phone_btn"
        app:layout_constraintTop_toBottomOf="@id/login_image" />

    <Button
        android:id="@+id/login_phone_btn"
        android:layout_width="120dp"
        android:layout_height="wrap_content"
        android:background="@drawable/login_button_selector"
        android:text="手机号登录"
        android:textSize="18sp"
        app:layout_constraintLeft_toRightOf="@id/login_userName_btn"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="@id/login_userName_btn" />

    <EditText
        android:id="@+id/login_userName"
        android:layout_width="0dp"
        android:layout_height="40dp"
        android:layout_marginLeft="30dp"
        android:layout_marginTop="15dp"
        android:layout_marginRight="30dp"
        android:background="@color/transparent"
        android:hint="请输入手机号码"
        android:inputType="phone"
        android:maxLines="1"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@id/login_userName_btn" />

    <TextView
        android:layout_width="0dp"
        android:layout_height="1dp"
        app:layout_constraintTop_toBottomOf="@id/login_userName"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:layout_marginTop="5dp"
        android:layout_marginLeft="30dp"
        android:layout_marginRight="30dp"
        android:background="#eeeeee"
        android:id="@+id/login_userName_split"/>

    <com.hbis.ttie.mall.login.ui.view.GradientColorTextButton
        android:layout_width="wrap_content"
        android:layout_height="30dp"
        app:layout_constraintBottom_toBottomOf="@id/login_userName"
        app:layout_constraintRight_toRightOf="@id/login_userName"
        app:layout_constraintTop_toTopOf="@id/login_userName"
        android:background="@drawable/login_captcha_layer"
        android:text="获取验证码"
        android:textSize="13sp"
        android:id="@+id/login_captcha_btn"/>

    <EditText
        android:id="@+id/login_password"
        android:layout_width="0dp"
        android:layout_height="40dp"
        android:layout_marginLeft="30dp"
        android:layout_marginRight="30dp"
        android:layout_marginTop="5dp"
        android:background="@color/transparent"
        android:hint="请输入密码"
        android:inputType="textPassword"
        android:maxLines="1"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@id/login_userName_split" />

    <TextView
        android:layout_width="0dp"
        android:layout_height="1dp"
        app:layout_constraintTop_toBottomOf="@id/login_password"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:layout_marginLeft="30dp"
        android:layout_marginRight="30dp"
        android:layout_marginTop="5dp"
        android:background="#eeeeee"
        android:id="@+id/login_password_split"/>

    <CheckBox
        android:id="@+id/login_auto"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:buttonTint="@color/blue"
        android:checked="true"
        android:text="自动登录"
        app:layout_constraintLeft_toLeftOf="@id/login_password"
        app:layout_constraintTop_toBottomOf="@id/login_password_split"
        android:visibility="gone"/>

    <Button
        android:id="@+id/login_submit"
        android:layout_width="0dp"
        android:layout_height="40dp"
        android:layout_marginLeft="30dp"
        android:layout_marginTop="5dp"
        android:layout_marginRight="30dp"
        android:background="@drawable/button_change"
        android:text="登录"
        android:textColor="@color/qmui_config_color_white"
        android:textSize="18sp"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@id/login_auto" />

    <TextView
        android:id="@+id/login_register"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="5dp"
        android:text="免费注册"
        android:textColor="@color/blue"
        app:layout_constraintLeft_toLeftOf="@id/login_submit"
        app:layout_constraintTop_toBottomOf="@id/login_submit" />

    <TextView
        android:id="@+id/login_forget"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="5dp"
        android:text="忘记密码?"
        android:textColor="@color/blue"
        app:layout_constraintRight_toRightOf="@id/login_submit"
        app:layout_constraintTop_toBottomOf="@id/login_submit" />

</com.hbis.ttie.mall.util.ui.WindowInsetLayoutConstraintLayout>

增加了之后还是会被遮挡，[http://i2.tiimg.com/697552/364b7e2a439ec23d.jpg](url)，还需要增加什么代码么

**Comment by cgspine** [comment]
QMUITopBarLayout 的高度应该 wrap_content

**Comment by huguoyan1989** [comment]
> QMUITopBarLayout 的高度应该 wrap_content

完美解决，感谢帮助
