### ISSUE TITLE
顶部导航栏在点击输入框时变高

### ISSUE THREAD

**Issue by hanyulang** [Tencent/QMUI_Android#678]
点击webview中的editext控件时 顶部导航栏变高了
![Screenshot_20190816_143047_com tryout verify](https://user-images.githubusercontent.com/13556989/63148148-da9b0100-c032-11e9-85fe-ec7835e989bd.jpg)

**Comment by Theoneee** [comment]
布局怎么写的。

**Comment by hanyulang** [comment]
<img width="729" alt="WX20190819-100223@2x" src="https://user-images.githubusercontent.com/13556989/63234637-c17b9580-c268-11e9-8059-d602acf9e0e2.png">

**Comment by Dragon-T** [comment]
我也遇到了相同的问题，最后按照demo写的布局解决了
![image](https://user-images.githubusercontent.com/25969333/64395437-dcce0980-d08c-11e9-9580-3a40833ee852.png)

**Comment by cgspine** [comment]
@hanyulang QMUITopBarLayout的父级需要是QMUIWindowInsetLayout才行的，可以参照 Demo 的写法
@Dragon-T 你的布局看上去应该是没有问题，或者 QMUITopBarLayout没有被 QMUIWindowInsetLayout 包裹？
