### ISSUE TITLE
项目clone下来运行提示程序包javafx.util不存在

### ISSUE THREAD

**Issue by zaaach** [Tencent/QMUI_Android#679]

**Comment by qq570026938** [comment]
我也发现这个问题了，你解决没

**Comment by cgspine** [comment]
抱歉，我是自动 import， 只用于一个文件的 Pair 类，你可以尝试替换为 com.sun.tools.javac.util.Pair 试试？

**Comment by zaaach** [comment]
我暂时把那个类删除了=。=

**Comment by FYSong** [comment]
这是jdk的库类，配置1.8版本便可

**Comment by tangchao0106** [comment]
![image](https://user-images.githubusercontent.com/19529121/64185554-f1997a00-ce9f-11e9-9c37-da4d1d93c766.png)
不报错怎么变不了运行图标
