### ISSUE TITLE
在AndroidStudio中打开报错：Gradle sync failed: CreateProcess error=2, 系统找不到指定的文件

### ISSUE THREAD

**Issue by LZKDreamer** [Tencent/QMUI_Android#682]
在AndroidStudio中打开报错：Gradle sync failed: CreateProcess error=2, 系统找不到指定的文件。
我是将整个项目用git拉下来的，请问怎么解决？

**Comment by cgspine** [comment]
有详细错误吗？ 一般这个是Android Studio 访问不到 git 命令导致构建指令失败，你可以在 Adroid Studio 的 Terminal 访问下git试试。或者 Android Studio 版本低？

**Comment by LZKDreamer** [comment]
ERROR: CreateProcess error=2, 系统找不到指定的文件。这个错误指向的是builg.gradle中的这一句：def gitVersion = cmd.execute().text.trim().toInteger()

**Comment by LZKDreamer** [comment]
在网上找到一篇相同错误的帖子，已经解决了，谢谢

**Comment by LZKDreamer** [comment]
> 請問是參考哪一篇文章解決的? 謝謝

时间太久了，我也忘记了，可以复制错误信息在Google搜索一下
