### ISSUE TITLE
手势返回时，SwipeBackgroundView.draw时，高德地图无法绘制到背景的问题

### ISSUE THREAD

**Issue by leanjiang** [Tencent/QMUI_Android#684]
### 运行环境 ###

- [x] 设备型号：如：`Meizu M3 Note`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `5.1.1`
- [x] QMUI Android 版本：`1.4.0`

### 具体问题描述 ###
如图所示
地图的为MainActivity，使用的是高德地图，默认的高德地图是MapView使用SurfaceView实现，示例中用的也是这个，我也用TextureMapView尝试过。在使用手势时，com.qmuiteam.qmui.arch.SwipeBackgroundView.ViewInfo#draw这个方法确实也调用过，我在想是不是因为高德地图的绘制不同于Android普通的View，所以导致最终没绘制出来。想问下，借鉴了
SwipeBackLayout 为啥不使用把windowBackground变成透明的形式，而是用SwipeBackgroundView 再绘制一次prevActivity呢？如果我自己改成让background透明的形式会有啥问题不？

#### 问题截图 ####

![near](https://user-images.githubusercontent.com/3284486/63313182-349f0d80-c336-11e9-87b7-eaa83dc30386.gif)

**Comment by cgspine** [comment]
1. 性能
2. 如果有横竖屏旋转，可能会触发 Only fullscreen opaque activities can request orientation 的 crash

**Comment by Theoneee** [comment]
MEIZU

**Comment by leanjiang** [comment]
感谢，我已经改成透明的方式实现。
透明方式都不需要再绘制windowBackground的背景，以及backgroundView的draw也不需要调用了，为啥反而会影响性能呢？

**Comment by cgspine** [comment]
因为背后那个Activity不会 pause，两个Activity是一直处于resume 状态的，耗费渲染
