### ISSUE TITLE
QMUIStickySectionLayout SectionItem为空时的提示

### ISSUE THREAD

**Issue by uCloudCastle** [Tencent/QMUI_Android#687]
### 运行环境 ###
- [x] QMUI Android 版本：`1.4.1`

### 具体问题描述 ###
我是在点击SectionHeader后去拉取相应的数据，有的SectionHeader下面的数据为空，需要给用户提示；
尝试使用CustomItem并在onGenerateCustomIndexAfterItemList方法中添加了CustomIndex，但结果是只有存在SectionItem的后面显示了customItem，如果SectionItem为空，customItem还是不显示。

请问有什么好的解决办法吗。确实不太想用一个特殊的SectionItem去workaround，多谢！

**Comment by cgspine** [comment]
可升级到 1.4.2，去掉了 list.isEmpty 的判断

**Comment by uCloudCastle** [comment]
> 可升级到 1.4.2，去掉了 list.isEmpty 的判断

刚升级下可以了，感谢！
