### ISSUE TITLE
抽象类继续于QMUIFragment，fragment无法滑动返回

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [Tencent/QMUI_Android#688]
抽象类继承于QMUIFragment，fragment无法滑动返回

**Comment by LiWeiQiangAndroid** [comment]
如 实现类fragment 继承 抽象类 LoadFragment 继承 抽象类BaseLoadFragment 继承 demo中的 BaseFragment时候滑动没有响应

**Comment by cgspine** [comment]
是否是重写了 canDragBack() ?

**Comment by LiWeiQiangAndroid** [comment]
没有重写，重写后也是不能滑动的

**Comment by cgspine** [comment]
可以检查下View层级里是否有View会消耗边缘事件？
