### ISSUE TITLE
ViewPager有三个页时滑动报错（已升级到最新版）

### ISSUE THREAD

**Issue by hjywyj** [Tencent/QMUI_Android#691]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4440)
        at android.view.ViewGroup.addView(ViewGroup.java:4276)
        at android.view.ViewGroup.addView(ViewGroup.java:4248)
        at com.qmuiteam.qmui.arch.SwipeBackLayout.wrap(SwipeBackLayout.java:629)
        at com.qmuiteam.qmui.arch.QMUIFragment.newSwipeBackLayout(QMUIFragment.java:365)
        at com.qmuiteam.qmui.arch.QMUIFragment.onCreateView(QMUIFragment.java:706)

**Comment by cgspine** [comment]
qmui-arch 0.5 以上版本？

**Comment by hjywyj** [comment]
> qmui-arch 0.5 以上版本？

对的，我在SwipeBackLayout加了个判断就好了
 ViewGroup parent = (ViewGroup) child.getParent();
        if (parent != null) {
            parent.removeView(child);
        }

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/64223894-1de8e100-cf08-11e9-8b53-b05548884f23.png)
高版本我在wrap前就已经有这个保护了啊

**Comment by hjywyj** [comment]
> ![image](https://user-images.githubusercontent.com/7828876/64223894-1de8e100-cf08-11e9-8b53-b05548884f23.png)
> 高版本我在wrap前就已经有这个保护了啊

特意看了一下
com.qmuiteam.qmui.arch.QMUIActivity.newSwipeBackLayout
并没有

**Comment by cgspine** [comment]
只是 QMUIFragment 需要吧， QMUIActivity 没这个必要，难道你多次 setContentView，并且传入同一个 View ? 你的报错堆栈也是 Fragment 的。 另一种可能是 你 Fragment.onCreateView 返回错了

**Comment by hjywyj** [comment]
QMUIFragment里，ViewPager，切换子Fragment的时候出现的这个异常
经测试
在切换Tab的时候，走了QMUIFragment.onDestroy，导致了mCacheRootView=null
然后再切换回去的时候，走的是if里的代码
  private SwipeBackLayout newSwipeBackLayout() {
        View rootView = mCacheRootView;
        if (rootView == null) {
            rootView = onCreateView();
            mCacheRootView = rootView;
最后导致报错，
解决方案：
onDestroy里加了行
 if (mCacheRootView != null && mCacheRootView.getParent() != null) {
            ((ViewGroup) mCacheRootView.getParent()).removeView(mCacheRootView);
        }

**Comment by cgspine** [comment]
onDestroy后，整个fragment就不应该被使用了啊，应该重新new一个啊
