### ISSUE TITLE
最新的arch库版本是0.6.1么，好像缺少record

### ISSUE THREAD

**Issue by SKYHua** [Tencent/QMUI_Android#693]
### 具体问题描述 ###
为什么我依赖下来的库里面没有record相关的文件
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/22288143/63991567-e6022800-cb1a-11e9-859a-c9ac883caf3c.png)

**Comment by cgspine** [comment]
有点神奇，我拉取下来是存在record，试试最新的0.6.2呢？

**Comment by SKYHua** [comment]
谢谢，解决了，0.6.2的是正常的，这应该是某些**特性**导致的
