### ISSUE TITLE
qmuidemo 在android studio中跑不起来。

### ISSUE THREAD

**Issue by kingctan** [Tencent/QMUI_Android#694]
加载后，Sync Project with Gradle Files，报这个错：

···
ERROR: Unable to find method 'sun.security.internal.spec.TlsMasterSecretParameterSpec.getExtendedMasterSecretSessionHash()[B'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
···

**Comment by cgspine** [comment]
你这是网络问题吧

**Comment by kingctan** [comment]
还是报错：
```
ERROR: Unable to find module with Gradle path 'main' (needed by modules: 'arch-compiler', 'compiler'.)
```

**Comment by cgspine** [comment]
https://www.jianshu.com/p/049b902f1055
你可以尝试一下这个解决方式
