### ISSUE TITLE
setShadowColor能否向下兼容

### ISSUE THREAD

**Issue by daxiong--** [Tencent/QMUI_Android#702]
### 运行环境 ###
 private void setShadowColorInner(int shadowColor) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            View owner = mOwner.get();
            if (owner == null) {
                return;
            }
            owner.setOutlineAmbientShadowColor(shadowColor);
            owner.setOutlineSpotShadowColor(shadowColor);
        }
    }

**Comment by cgspine** [comment]
通过 elevation 来实现阴影的，目前没找到兼容方式。

**Comment by daxiong--** [comment]
加油！
