### ISSUE TITLE
想在setUserVisibleHint方法中刷新数据，但是打印log 并未调用此方法呢

### ISSUE THREAD

**Issue by zs1973** [Tencent/QMUI_Android#703]
每次切换到某个界面中都需要刷新数据，想在setUserVisibleHint方法中刷新数据，但是打印log 并未调用此方法呢？

**Comment by cgspine** [comment]
Fragment 的 setUserVisibleHint 默认是true，并且需要你自己主动去调用的，像 FragmentPagerAdapter 这种和 ViewPager配合使用的才有帮你处理它。

**Comment by JakeWoki** [comment]
ViewPager2天然支持懒加载，setUserVisibleHint已经被弃用了

**Comment by zs1973** [comment]
> ViewPager2天然支持懒加载，setUserVisibleHint已经被弃用了
