### ISSUE TITLE
QMUIViewPager无限轮播

### ISSUE THREAD

**Issue by WinnieZy** [Tencent/QMUI_Android#707]
### 运行环境 ###

- [x] 设备型号：如：`vivo x27`
- [x] 设备系统版本：如 `Android 8.1.0`
- [x] Gradle 版本：如 `3.3.2`
- [x] QMUI Android 版本：`1.4.0`

### 具体问题描述 ###

Demo中QDLoopViewPagerFragment类的循环轮播是使用了QMUIViewPager.setEnableLoop(true);接口，循环的情况是向右可无限轮播（如0->1->2->3->4->5->0->1->2->3->4->5->.....)，但是向左的时候则是向右滑动了多少则向左返回多少（即上面示例中，返回的情况为5->4->3->2->1->0->5->4->3->2->1->0就到头了）。

请问QMUIViewPager是否能支持向左向右均能无限轮播？（即到0时再往左能从5开始继续循环下去）
另：关于count<=3时发生的crash问题，是否已有解决方案？

**Comment by cgspine** [comment]
这个方案不是真正的无限循环，不管是向左还是向右，都会有终点的，最多重复100次，你可以直接setPosition到一个比较大的值，就没那么容易忘左很快到头了。 
目前而言，我觉得可能最好的方式是使用官方新提供的 ViewPager2 来实现这种无限循环了

**Comment by WinnieZy** [comment]
也就是目前QMUI没有支持无限循环的ViewPager，需要我自己实现是吧

**Comment by cgspine** [comment]
目前推荐用 ViewPager2 自己实现

**Comment by WinnieZy** [comment]
好的明白，那这个需求还是先自己实现
