### ISSUE TITLE
QMUIDialog显示异常

### ISSUE THREAD

**Issue by Steam-Ace** [Tencent/QMUI_Android#709]
### 运行环境 ###

- [x] 设备型号：如：`Android SDK built for x86_64`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `3.4.1`
- [x] QMUI Android 版本：`1.4.0`

### 具体问题描述 ###
QMUIDialog.MessageDialogBuilder 创建的Dialog,弹出后能看到按钮，但是按钮立刻被窗体滚动一下，就隐藏了，只显示了半截。目前发现跟长度有关，但是弹窗不能保证内容具体长度，也没测试其他机型是否也存在类似问题。
#### 问题截图 ####
![`GPU8N1@9VJBDQ4~AI97L_9](https://user-images.githubusercontent.com/24566628/65474427-539d3c00-deae-11e9-9bc1-2a3ad7c18fa2.png)
![7$~F1@%XBDA9FE{~IXAT6$0](https://user-images.githubusercontent.com/24566628/65474762-914e9480-deaf-11e9-8b64-c7c7bc250125.png)

#### 一定长度的正常截图 ####
![{H9W 2CT73(YP 5VTF0G5Y](https://user-images.githubusercontent.com/24566628/65474786-adeacc80-deaf-11e9-9502-cff6f765091b.png)

**Comment by cgspine** [comment]
你这是分屏模式下？正常手机高度应该都够显示这个dialog，MessageDialogBuilder 确实没考虑分屏模式下高度不够的情况。

**Comment by Steam-Ace** [comment]
> 你这是分屏模式下？正常手机高度应该都够显示这个对话框，MessageDialogBu​​ilder确实没考虑分屏模式下高度不够的情况。

您好，app不是分屏模式，是正常使用情况下出现的这个问题。

**Comment by cgspine** [comment]
正常情况不应该，屏幕高度肯定够显示全部内容的，可以提供下 layout inspector 文件吗？

**Comment by Steam-Ace** [comment]
> 正常情况不应该，屏幕高度肯定够显示全部内容的，可以提供下 layout inspector 文件吗？

好的。界面是正常高度，出现这情况很纳闷。不能直接上传，所以我压缩了一下。

[2019.09.25_11.05.zip](https://github.com/Tencent/QMUI_Android/files/3650373/2019.09.25_11.05.zip)

**Comment by cgspine** [comment]
你应该给我dialog的layout inspector，目前是你主界面的

**Comment by Steam-Ace** [comment]
> 你应该给我dialog的layout inspector，目前是你主界面的

[2019.09.25_11.24-1.zip](https://github.com/Tencent/QMUI_Android/files/3650405/2019.09.25_11.24-1.zip)

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/65571421-40b26680-df97-11e9-8062-05242edfd149.png)
你这里的measure信息很神奇，竟然是UNSPECIFIED，可以提供下你的 theme 配置吗？或者拿你的theme在 QMUIDemo上使用，看看能不能重现？

**Comment by Steam-Ace** [comment]
找到问题了，不是QMUI的问题，项目用的今日头条屏幕适配方案，是这个引起的适配问题！

**Comment by Steam-Ace** [comment]
> ![image](https://user-images.githubusercontent.com/7828876/65571421-40b26680-df97-11e9-8062-05242edfd149.png)
> 你这里的measure信息很神奇，竟然是UNSPECIFIED，可以提供下你的 theme 配置吗？或者拿你的theme在 QMUIDemo上使用，看看能不能重现？

非常感谢，不是QMUI的问题，显示异常的问题已经解决

**Comment by lzybilian** [comment]
> 找到问题了，不是QMUI的问题，项目用的今日头条屏幕适配方案，是这个引起的适配问题！

具体是什么问题能说下嘛，目前好像也碰到了类似的问题
