### ISSUE TITLE
QMUISpanTouchFixTextView配合maxLines和ellipsize值显示相应的行数但是不现实省略符号

### ISSUE THREAD

**Issue by wangtonggen** [Tencent/QMUI_Android#717]
<com.qmuiteam.qmui.widget.textview.QMUISpanTouchFixTextView
        android:id="@+id/tv_title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="@dimen/dp_16"
        android:ellipsize="end"
        android:maxLines="2"
        android:fontFamily="sans-serif-medium"
        android:textColor="@color/color_333333"
        android:textSize="@dimen/sp_16" />

**Comment by cgspine** [comment]
#226 估计是TextView自身的 bug

**Comment by wangtonggen** [comment]
> #226 估计是TextView自身的 bug

已经解决了富文本的textView会默认把上下滑动打开，导致不显示省略符，只可以上下滑动，现在需要把设置setMovementMethodCompat设置成自己重写后的滑动方法就行了。
