### ISSUE TITLE
QMUICollapsingTopBarLayout

### ISSUE THREAD

**Issue by Theoneee** [Tencent/QMUI_Android#719]
我把QMUICollapsingTopBarLayout的代码复制到了本地。然后在`OffsetUpdateListener`里监听了状态，代码如下：

```
private State mCurrentState = State.IDLE;

    private class OffsetUpdateListener implements AppBarLayout.OnOffsetChangedListener {
        OffsetUpdateListener() {
        }

        @Override
        public void onOffsetChanged(AppBarLayout layout, int verticalOffset) {
            mCurrentOffset = verticalOffset;
            final int insetTop = getWindowInsetTop();
            if (null != mStateChangeListener) {
                if (verticalOffset == 0) {
                    mCurrentState = State.EXPANDED;
                } else if (Math.abs(verticalOffset) >= layout.getTotalScrollRange()) {
                    mCurrentState = State.COLLAPSED;
                } else {
                    mCurrentState = State.IDLE;
                }
                mStateChangeListener.onStateChanged(mCurrentState, verticalOffset);
            }
        ......
       }
    }
```

然后在代码里设置颜色失效。压根就不显示了好像。。

```
 mCollapsingTopBarLayout.setCollapsedTitleTextColor(getColorr(R.color.qmui_config_color_gray_2));
        mCollapsingTopBarLayout.setExpandedTitleColor(getColorr(R.color.qmui_config_color_white));
```

原因不知道从何找起。。。

![QMUICollapsingTopBarLayout](https://user-images.githubusercontent.com/32156330/65828191-c9e4d880-e2ca-11e9-8647-c13fe26feff0.jpg)

额，我不知道怎么传文件。这个是JAVA文件，下载后更改下后缀应该就可以了。

**Comment by cgspine** [comment]
代码只能发zip包，图片处于失效状态，没法下载。不过为何要在offset的过程中设置Collapsed 与 expanded 颜色？ 这两个应该一开始设置好，offset过程会根据 它们两个动态计算出颜色值，我猜你这里应该是它本身会动态计算一个值，而你又重新设置，导致它有需要重新计算，大量的触发invalidate，导致没有真正的绘制

**Comment by Theoneee** [comment]
> 代码只能发zip包，图片处于失效状态，没法下载。不过为何要在offset的过程中设置Collapsed 与 expanded 颜色？ 这两个应该一开始设置好，offset过程会根据 它们两个动态计算出颜色值，我猜你这里应该是它本身会动态计算一个值，而你又重新设置，导致它有需要重新计算，大量的触发invalidate，导致没有真正的绘制

没有在offset时设置，我的意思是在Fragment里用代码设置。

```
        mCollapsingTopBarLayout.setCollapsedTitleTextColor(getColorr(R.color.qmui_config_color_gray_2));
        mCollapsingTopBarLayout.setExpandedTitleColor(getColorr(R.color.qmui_config_color_white));
        mCollapsingTopBarLayout.setStateChangeListener(new QMUICollapsingTopBarLayout.AppBarStateChangeListener() {
            @Override
            public void onStateChanged(QMUICollapsingTopBarLayout.State state, int offset) {
                if(state == QMUICollapsingTopBarLayout.State.COLLAPSED){
                    mTopBar.setBackground(getDrawablee(R.drawable.qmui_list_item_bg_with_border_bottom));
                }else if(state == QMUICollapsingTopBarLayout.State.EXPANDED){
                    mTopBar.setBackground(getDrawablee(R.drawable.qmui_s_list_item_transparent_bg_with_none));
                }
            }
        });
```

换成QMUI自带的没有监听，字体颜色设置有效。加了监听后，设置这个颜色（或者不设置）。应该说是加了监听后不显示Title了。

**Comment by Theoneee** [comment]
[QMUICollapsingTopBarLayout.zip](https://github.com/Tencent/QMUI_Android/files/3668328/QMUICollapsingTopBarLayout.zip)

**Comment by cgspine** [comment]
mac解压后是cpgz后缀？ 文件上传失败？还是特殊工具生成的 zip ?

**Comment by Theoneee** [comment]
额。。  RAR我直接改的后缀。。

现在这个应该是了

[QMUICollapsingTopBarLayout.zip](https://github.com/Tencent/QMUI_Android/files/3700110/QMUICollapsingTopBarLayout.zip)

**Comment by Theoneee** [comment]
@cgspine

**Comment by Theoneee** [comment]
```
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
```

这个能加多个吗。
我有三个项目，很多都是相同的，我想把相同的写在一个，不同项目只写不同的。

**Comment by Theoneee** [comment]
还有这个 

QMUIStickySectionLayout 如果设置 sticky 为false时，如何获取当前页面显示的第一个item的header呢。

**Comment by Theoneee** [comment]
九宫格控件

由于item的复用机制，在回滚时，由于数量不一致，重绘时会出现高度不一样导致的“卡顿”。（不知道我这样描述对不对）

这种大佬有遇到过吗。怎么解决的呢。

**Comment by cgspine** [comment]
1. QMUIStickySectionLayout 可以通过 getRelativeStickyPosition 去寻找 对应的 header position.
2. proguardFiles  好像是可以用多个？https://juejin.im/post/5c97485e6fb9a070f03d016d
3. 你说的九宫格是每一行高度也不一致吗？瀑布流那样? StaggeredGridLayoutManager?

**Comment by Theoneee** [comment]
1. 我想在TopBar上显示header的内容，那这样是不是就得在监听里在滑动时一直不断的去 获取header嘛？
3. 类似朋友圈的九宫格图片的那种控件。现在的解决方法就是增加item的缓存量。但是这个治标不治本。

**Comment by Theoneee** [comment]
@cgspine

**Comment by cgspine** [comment]
1. QMUIStickySectionLayout 开启 sticky 其实也是通过 ItemDecoration，不断的去更新， scroll 监听不到第一次的情况
2. 应该也只有几种图片大小的类型，我觉得分别缓存就行，跨item复用。若果要优化到极致，可以用一个View，图片全部通过draw出来，点击事件也分区域处理。
