### ISSUE TITLE
QMUIButton实现不了阴影效果

### ISSUE THREAD

**Issue by davidgerka** [Tencent/QMUI_Android#721]
代码如下图，为什么实现不了绿色阴影效果，而且阴影效果左右两边大，上下只有一点点
![image](https://user-images.githubusercontent.com/13624423/66472002-ec42d700-eabe-11e9-9a4a-7d40d1dbaebb.png)
![image](https://user-images.githubusercontent.com/13624423/66472132-2b712800-eabf-11e9-9a00-00ace37aa5d8.png)

**Comment by cgspine** [comment]
1. shadowColor 只在 Android P 以后生效
2. 你的上下没有阴影，应该是被父View裁剪了，你需要为阴影留点空间，或者在父级的父级设置 clipChildren = false

**Comment by davidgerka** [comment]
正解，3Q
