### ISSUE TITLE
用QMUIStickySectionLayout实现分组粘性头部列表，阴影效果bug

### ISSUE THREAD

**Issue by davidgerka** [Tencent/QMUI_Android#723]
如下图所示，当列表滑动到顶部时，阴影效果会出现在顶部，猜测是sticky视图移出了屏幕顶部，它的底部阴影效果刚才投进来了
![image](https://user-images.githubusercontent.com/13624423/66532784-41c0c780-eb43-11e9-853e-035431e6cbe2.png)

**Comment by cgspine** [comment]
确实会这样，但是这种情况如果隐藏，则出现时会抖动，所以目前，直接悬浮覆盖第一个header，阴影出现在第一个header下方
