### ISSUE TITLE
引入后报错

### ISSUE THREAD

**Issue by Fretory** [Tencent/QMUI_Android#724]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 7.0`
- [x] QMUI Android 版本：`1.4.0`

### 具体问题描述 ###
Manifest merger failed : Attribute application@appComponentFactory value=(androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0-beta01] AndroidManifest.xml:22:18-86
	is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:8:5-23:19 to override.

尝试了stcokflow的解决方式，未解决

**Comment by cgspine** [comment]
你的项目已经切换到androidx，而没有开启 enableJetifier ？

**Comment by Fretory** [comment]
> 你的项目已经切换到androidx，而没有开启 enableJetifier ？

`android.useAndroidX=true
android.enableJetifier=true
`
这是我的gradle.properties

编译运行后未通过，报错为

> More than one file was found with OS independent path 'META-INF/androidx.legacy_legacy-support-core-utils.version'

尝试了[https://stackoverflow.com/questions/51465643/more-than-one-file-was-found-with-os-independent-path-meta-inf-androidx-legacy](https://stackoverflow.com/questions/51465643/more-than-one-file-was-found-with-os-independent-path-meta-inf-androidx-legacy)这个方法，好像也不大行。

**Comment by cgspine** [comment]
是否有其它UI依赖或者项目本身也引入了 support-v4 包？

**Comment by Fretory** [comment]
> 是否有其它UI依赖或者项目本身也引入了 support-v4 包？

`dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.0-beta01'
    implementation 'com.qmuiteam:qmui:1.4.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'

}`
这是我的dependencies,挨个注释，除了implementation 'androidx.appcompat:appcompat:1.0.0-beta01'被注释后会编译出错，其余的注释后均为刚才提到的提示。

排查了下我的代码，没有地方import了support-v4

**Comment by cgspine** [comment]
可以提供下你的运行环境吗？ 我 Android studio 3.5, gradle-5.4.1, gradle plugin 3.5.0 是可以正常运行 androidx 的

**Comment by Fretory** [comment]
> 可以提供下你的运行环境吗？ 我 Android studio 3.5, gradle-5.4.1, gradle plugin 3.5.0 是可以正常运行 androidx 的

感谢，我按照您的运行自检了一遍，最后修改到gradle plugin 3.5.0 ，程序可以正常运行，非常感谢您的耐心回复，比心~
