### ISSUE TITLE
Demo编译失败

### ISSUE THREAD

**Issue by zqlq4ever** [Tencent/QMUI_Android#727]
`Could not find com.qmuiteam:skin-maker-plugin:0.0.1.
Searched in the following locations:
  - file:/C:/Users/zqlq4ever/.m2/repository/com/qmuiteam/skin-maker-plugin/0.0.1/skin-maker-plugin-0.0.1.pom
  - file:/C:/Users/zqlq4ever/.m2/repository/com/qmuiteam/skin-maker-plugin/0.0.1/skin-maker-plugin-0.0.1.jar
  - https://dl.google.com/dl/android/maven2/com/qmuiteam/skin-maker-plugin/0.0.1/skin-maker-plugin-0.0.1.pom
  - https://dl.google.com/dl/android/maven2/com/qmuiteam/skin-maker-plugin/0.0.1/skin-maker-plugin-0.0.1.jar
  - https://jcenter.bintray.com/com/qmuiteam/skin-maker-plugin/0.0.1/skin-maker-plugin-0.0.1.pom
  - https://jcenter.bintray.com/com/qmuiteam/skin-maker-plugin/0.0.1/skin-maker-plugin-0.0.1.jar
Required by:
    project :`

**Comment by soul0932** [comment]
同样的问题

**Comment by cgspine** [comment]
如果是想看demo代码，可以切换到 1.x 分支。

skin-maker-plugin 还在开发中，可以运行 `./gradlew :skin-maker-plugin:clean :skin-maker-plugin:build skin-maker-plugin:publishToMavenLocal `将插件发布到本地，可以保证主干代码编译通过
