### ISSUE TITLE
QMUIGroupListView 使用异常。

### ISSUE THREAD

**Issue by felixcc** [Tencent/QMUI_Android#730]
### 运行环境 ###

- [x] 设备型号：如：`OnePlus 7pro`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `3.5.1`
- [x] QMUI Android 版本：`1.4.0`

### 具体问题描述 ###
参照 demo：
![image](https://user-images.githubusercontent.com/459409/67414489-c86ead80-f5f5-11e9-99f3-4ff6eb301320.png)

![image](https://user-images.githubusercontent.com/459409/67414500-d0c6e880-f5f5-11e9-87d2-62c4976c6d42.png)

![image](https://user-images.githubusercontent.com/459409/67414580-f18f3e00-f5f5-11e9-928d-83a1b98772f3.png)

initGroupListView 方法完全参照 demo 里的，只不过是没有截全。
#### 问题截图 ####

![image](https://user-images.githubusercontent.com/459409/67414770-55b20200-f5f6-11e9-8049-c46d13dbb091.png)

**Comment by Theoneee** [comment]
Demo能不能运行 - >
找出与Demo不相同的代码注释掉再运行监测是否正常 ->
加入部分注释掉的代码运行 ->
找到问题出现的代码 , 结合日志进行分析排查原因。

**Comment by felixcc** [comment]
> Demo能不能运行 - >
> 找出与Demo不相同的代码注释掉再运行监测是否正常 ->
> 加入部分注释掉的代码运行 ->
> 找到问题出现的代码 , 结合日志进行分析排查原因。

demo 可以运行，demo 是 fragment，我用的 activity。
没啥大影响，xml 以及代码复制是一样的。

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by cgspine** [comment]
引入了androidx， 再引入下 'androidx.legacy:legacy-support-v4:1.0.0' 应该就行

**Comment by felixcc** [comment]
我加了句”    implementation 'androidx.appcompat:appcompat:1.1.0'“
就解决了。
