### ISSUE TITLE
popBackStack 有办法关闭多个吗？

### ISSUE THREAD

**Issue by wflian** [Tencent/QMUI_Android#731]
比如  AFragment  -> BFragment -> CFragment -> DFragment

有办法在DFragment 关闭 BCD三个Fragment 直接回到AFragment吗？

**Comment by wflian** [comment]
QMUIFragment 这两个方法错了！！！
   protected void popBackStack(Class<QMUIFragment> cls) {}
   protected void popBackStackInclusive(Class<QMUIFragment> cls) {}
  应该改成
 protected void popBackStack(Class<? extends QMUIFragment> cls) {}
 protected void popBackStackInclusive(Class<? extends QMUIFragment> cls) {}

**Comment by cgspine** [comment]
我改改

**Comment by strivezsh** [comment]
杂么 直接 销毁 所有fragment?
就是 注销 跳转到 登录界面

**Comment by cgspine** [comment]
直接finish当前activity，然后启动个新的activity来承载登录界面

**Comment by strivezsh** [comment]
这就尴尬了
MainActivity extends BaseFragmentActivity
只有一个 activity 剩下 全是 fragment

**Comment by cgspine** [comment]
另起一个 MainActivity 就行了啊

**Comment by wflian** [comment]
getBaseFragmentActivity().popBackStackInclusive();
