### ISSUE TITLE
https://qmuiteam.com/join-us 不存在啊，长期无效啊

### ISSUE THREAD

**Issue by moz1q1** [Tencent/QMUI_Android#732]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
现在已经下掉了，你在哪里看到的这个链接？

**Comment by moz1q1** [comment]
额，我长期关注项目，看到链接没了

**Comment by moz1q1** [comment]
你们之前写长期有效

**Comment by cgspine** [comment]
抱歉，之前文案确实不合理。
