### ISSUE TITLE
API使用说明不够详细呀，新手上手得费点时间了

### ISSUE THREAD

**Issue by 297179121** [Tencent/QMUI_Android#738]
要是组件的API能够详细些这套UI就更完美了（但愿别是KPI项目，祈祷~）

**Comment by 297179121** [comment]
github中有
![image](https://user-images.githubusercontent.com/3394927/68064767-aba34a00-fd5a-11e9-9bb7-f6733ed4ecc3.png)
但是我在自己的项目中添加依赖后发现
![image](https://user-images.githubusercontent.com/3394927/68064774-d1c8ea00-fd5a-11e9-9b0e-2a7c35e7afdb.png)

怎么回事？

**Comment by Theoneee** [comment]
如果要关闭滑动返回，上面那个方法返回false，如果是下面那个问题，你说开发版和正式版会有区别的区别在哪里？

**Comment by cgspine** [comment]
github 上的修改目前还没发release版本
