### ISSUE TITLE
为啥文档注释乱码

### ISSUE THREAD

**Issue by LLXBH** [Tencent/QMUI_Android#739]
![image](https://user-images.githubusercontent.com/34165598/68137463-fe028780-ff61-11e9-94b2-5b8356863b4a.png)

**Comment by cgspine** [comment]
Android Studio 编码格式不是UTF-8？

**Comment by LLXBH** [comment]
> Android Studio 编码格式不是UTF-8？

是设置这里吗？已全部选择utf-8了
studio版本是3.5.2
![批注 2019-11-06 144249](https://user-images.githubusercontent.com/34165598/68274395-f3500b80-00a3-11ea-9047-e9ddb7de566f.png)

**Comment by cgspine** [comment]
可以尝试下更改字体？有些是不支持中文的，你直接编写中文会乱码吗？

**Comment by LLXBH** [comment]
> 可以尝试下更改字体？有些是不支持中文的，你直接编写中文会乱码吗？

修改这里的吗？刚才换了好几个字体都不行
![image](https://user-images.githubusercontent.com/34165598/68280000-99edd980-00af-11ea-941d-523e8224ab36.png)

好像只有qmui会这样，我看了好几依赖，他们的显示正常的
![image](https://user-images.githubusercontent.com/34165598/68280078-c99ce180-00af-11ea-9dbb-7557ff749118.png)

**Comment by LLXBH** [comment]
> 可以尝试下更改字体？有些是不支持中文的，你直接编写中文会乱码吗？

我代码中的中文不会乱码

**Comment by cgspine** [comment]
直接点进去源文件也是乱码吗？如果在源文件直接修改 file-encoding 呢？有点奇怪

**Comment by LLXBH** [comment]
> 直接点进去源文件也是乱码吗？如果在源文件直接修改 file-encoding 呢？有点奇怪

![image](https://user-images.githubusercontent.com/34165598/68282767-39619b00-00b5-11ea-964e-67dda576714e.png)
源文件正常的，然后是修改这个吗？修改了好几个发现源文件都没有变化
![image](https://user-images.githubusercontent.com/34165598/68282873-6dd55700-00b5-11ea-9065-b8f798311ca0.png)

**Comment by cgspine** [comment]
这是你首次引入 QMUI 就出现乱码吗？可以试试重新同步一次gradle。

**Comment by LLXBH** [comment]
> 这是你首次引入 QMUI 就出现乱码吗？可以试试重新同步一次gradle。

对的，我新装电脑系统后安装最新的as（3.5.2）是发现有的，我刚刚尝试把gradle下载的jar包删除了，重新构建它还是这样的
以前as（3.4）的时候是正常的

**Comment by LLXBH** [comment]
> 这是你首次发布QMUI就出现乱码吗？可以试试重新同步一次gradle。

QMUI2 的文档显示正常了

**Comment by cgspine** [comment]
这， 也行吧，我好像也没改啥文档相关的，迷之Android Studio
