### ISSUE TITLE
草泥马写的什么垃圾DEMO，一个简单的布局抽来抽去，傻逼东西

### ISSUE THREAD

**Issue by TsaiYongChuan** [Tencent/QMUI_Android#740]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by kaniel520** [comment]
哈哈哈，我也觉得是！他们喜欢把简单的东西写的复杂，显示出高超技术

**Comment by TsaiYongChuan** [comment]
> 哈哈哈，我也觉得是！他们喜欢把简单的东西写的复杂，显示出高超技术

其实还是我太菜，当初可能太暴躁了
