### ISSUE TITLE
QMUIRoundButtonDrawable使用问题

### ISSUE THREAD

**Issue by goodfree** [Tencent/QMUI_Android#742]
`
FrameLayout roundFrameLayout = (FrameLayout) layoutView;
//roundFrameLayout.setBackgroundColor(Color.WHITE);
QMUIRoundButtonDrawable bg = new QMUIRoundButtonDrawable();
//bg.setColor(ContextCompat.getColor(activity, R.color.white));
//bg.setBgData(ColorStateList.valueOf(ContextCompat.getColor(activity, R.color.white)));
float[] radii = new float[]{0, 0,0, 0,
                        QMUIDisplayHelper.dp2px(activity, 8), QMUIDisplayHelper.dp2px(activity, 8),
                        QMUIDisplayHelper.dp2px(activity, 8), QMUIDisplayHelper.dp2px(activity, 8)};
bg.setCornerRadii(radii);
QMUIViewHelper.setBackgroundKeepingPadding(roundFrameLayout, bg);
`
以上代码实现动态设置带圆角背景失效

其中使用// 注释部分都测试过，无效

**Comment by goodfree** [comment]
#492

**Comment by goodfree** [comment]
QMUIRoundFrameLayout roundFrameLayout = (QMUIRoundFrameLayout) layoutView;
                QMUIRoundButtonDrawable bg = (QMUIRoundButtonDrawable) roundFrameLayout.getBackground();
                bg.setBgData(ColorStateList.valueOf(ContextCompat.getColor(activity, R.color.red)));
                float[] radii = new float[]{0, 0,0, 0,
                        QMUIDisplayHelper.dp2px(activity, 8), QMUIDisplayHelper.dp2px(activity, 8),
                        QMUIDisplayHelper.dp2px(activity, 8), QMUIDisplayHelper.dp2px(activity, 8)};
                bg.setCornerRadii(radii);
                QMUIViewHelper.setBackgroundKeepingPadding(roundFrameLayout, bg);

**Comment by cgspine** [comment]
需要加上下面的代码，因为默认在 theme 里设置了 isRadiusAdjustBounds 为 true, 其次不需要再将background 设置回去，同一个对象，setBackground 内部判断同一个对象时直接返回了。
```
bg.setIsRadiusAdjustBounds(false);
bg.invalidateSelf();
```

**Comment by goodfree** [comment]
解决了，谢谢

**Comment by goodfree** [comment]
> 需要加上下面的代码，因为默认在 theme 里设置了 isRadiusAdjustBounds 为 true, 其次不需要再将background 设置回去，同一个对象，setBackground 内部判断同一个对象时直接返回了。
> 
> ```
> bg.setIsRadiusAdjustBounds(false);
> bg.invalidateSelf();
> ```

解决了，谢谢
