### ISSUE TITLE
QMUIFragmentActivity.intentOf 崩溃报错

### ISSUE THREAD

**Issue by abc8312111** [Tencent/QMUI_Android#744]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 6.0`
- [x] Gradle 版本：如 `2.4.1`
- [x] QMUI Android 版本：`1.4.0`

### 具体问题描述 ###
6.0系统存在崩溃现象 异常说找不到方法。
错误代码QMUIFragmentActivity.intentOf(this, MainActivity.class, OrganizationFragment.class);
应用适配了androidx  
android.useAndroidX=true
android.enableJetifier=true
#### 异常日志（堆栈） ####
java.lang.NoSuchMethodError

No interface method getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ljava/util/Map; or its super classes (declaration of 'java.util.Map' appears in /system/framework/core-libart.jar)

com.cedte.cloud.admin.ui.MainActivity_FragmentFinder.getIdByFragmentClass(MainActivity_FragmentFinder.java:34)
--
2 com.qmuiteam.qmui.arch.QMUIFragmentActivity.intentOf(QMUIFragmentActivity.java:333)
3 com.qmuiteam.qmui.arch.QMUIFragmentActivity.intentOf(QMUIFragmentActivity.java:313)
4 com.cedte.cloud.admin.ui.SplashActivity.lambda$onCreate$0$SplashActivity(SplashActivity.java:77)
5 com.cedte.cloud.admin.ui.-$$Lambda$SplashActivity$IAp4lYeFR9yT0oD9fRnapNi9FDY.run(lambda)
6 android.os.Handler.handleCallback(Handler.java:739)
7 android.os.Handler.dispatchMessage(Handler.java:95)
8 android.os.Looper.loop(Looper.java:148)
9 android.app.ActivityThread.main(ActivityThread.java:5417)
10 java.lang.reflect.Method.invoke(Native Method)
11 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
12 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by abc8312111** [comment]
android 7.0 8.0 测试无崩溃现象 请问有解决方案吗？

**Comment by abc8312111** [comment]
help

**Comment by cgspine** [comment]
arch 和 arch compiler 版本升级到 0.6.2

**Comment by abc8312111** [comment]
implementation 'com.qmuiteam:qmui:1.4.0'
    def qmui_arch_version = '0.6.2'
    implementation "com.qmuiteam:arch:$qmui_arch_version"
    annotationProcessor "com.qmuiteam:arch-compiler:$qmui_arch_version"

这是我的当前配置

**Comment by cgspine** [comment]
啊，抱歉，我遗漏在外网发布 fix 包了，我补发了，可以升级 arch 到 0.7.0， qmui 到 1.4.4

**Comment by abc8312111** [comment]
好的，感谢作者。

**Comment by abc8312111** [comment]
好的，感谢您的耐心回复。
