### ISSUE TITLE
QMUIQQFaceView配合QMUITouchableSpan使用时，onSpanClick不执行

### ISSUE THREAD

**Issue by rettey** [Tencent/QMUI_Android#747]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 6.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.4.1`

### 具体问题描述 ###
QMUIQQFaceView配合QMUITouchableSpan使用时，当设置Gravity为Gravity.Center或者Gravity.Right时，SpanInfo的mStartPoint和mEndPoint计算错误，导致onTouch判断不准确，最终导致onSpanClick不执行。
#### 问题截图 ####

![image](https://user-images.githubusercontent.com/7775431/68737443-6c101400-061e-11ea-9946-0f0fcb2887c0.png)

**Comment by rettey** [comment]
临时修复方法，在SpanInfo 的setEnd方法时重新计算mStartPoint和mEndPoint的值

public void setEnd(int endLine,final int endPoint) {
            mEndLine = endLine;
            mEndPoint = endPoint;

            QMUIQQFaceView.this.post(new Runnable() {
                @Override
                public void run() {
                    int userWidth = getWidth() - getPaddingLeft() - getPaddingRight();
                    if (mGravity == Gravity.CENTER) {
                        mStartPoint = (userWidth - mCurrentCalWidth) / 2 + mStartPoint + getPaddingLeft()/2;
                        mEndPoint = (userWidth - mCurrentCalWidth) / 2 + endPoint + getPaddingLeft()/2;
                    } else if (mGravity == Gravity.RIGHT) {
                        mStartPoint = userWidth - mCurrentCalWidth + mStartPoint + getPaddingLeft();
                        mEndPoint = userWidth - mCurrentCalWidth + endPoint + getPaddingLeft();
                    }
                }
            });
        }

**Comment by cgspine** [comment]
1.4.5 fixed
