### ISSUE TITLE
想咨询一下作者大概什么时候更新2.0版本？？？

### ISSUE THREAD

**Issue by xionger0520** [Tencent/QMUI_Android#748]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by cgspine** [comment]
来了来了 2.0.0-alpha01 版本 release 了
