### ISSUE TITLE
2.0 版本的一些期待

### ISSUE THREAD

**Issue by turnmind** [Tencent/QMUI_Android#749]
1、增加夜间暗黑模式
2、设计更加符合现代UI风格，比如 seekbar 换成 Flyme 8 或者苹果那种柱形，方便手指拖动；Dlg 窗口位置下沉；支持色彩切换；
3、TabSegment 支持调整 图标的 padding

**Comment by cgspine** [comment]
2.0.0-alpha01 版本 release 了。
1. 支持夜间模式
2. 提供了 QMUISlider 组件，和苹果的 Slider 很像， Dialog位置下沉可以通过改 window 的 gravity 实现？ 色彩切换是指？
3.  图标的 padding? 你是希望调整图标与文字间的距离？现在可以通过 QMUITab.setIconTextGap 设置

**Comment by turnmind** [comment]
> 2.0.0-alpha01 版本 release 了。
> 
> 1. 支持夜间模式
> 2. 提供了 QMUISlider 组件，和苹果的 Slider 很像， Dialog位置下沉可以通过改 window 的 gravity 实现？ 色彩切换是指？
> 3. 图标的 padding? 你是希望调整图标与文字间的距离？现在可以通过 QMUITab.setIconTextGap 设置

@cgspine 大佬牛皮牛皮
