### ISSUE TITLE
QMUIQQFaceView ellipsize="end" 无效

### ISSUE THREAD

**Issue by mny459** [Tencent/QMUI_Android#750]
### 运行环境 ###

- [x] 设备型号：小米8 nova3
- [x] 设备系统版本：android 10 android 9
- [x] Gradle 版本：Demo 1.4.2版本 
- [x] QMUI Android 版本：1.4.2 1.4.4

### 具体问题描述 ###
Demo QQ表情使用展示中的 “单行表情，末尾省略 ” 和 “最多显示3行，末尾省略” 无效
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/24559456/69240294-1a93f600-0bd7-11ea-996d-dae89fe0a82b.png)

**Comment by cgspine** [comment]
谢谢反馈，中间版本改出来的 bug 导致 xml 无法生效。

**Comment by cgspine** [comment]
1.4.5 fixed
