### ISSUE TITLE
状态栏不能沉浸式

### ISSUE THREAD

**Issue by turnmind** [Tencent/QMUI_Android#751]
### 运行环境 ###

- [x] 设备型号：`魅族 16s`
- [x] 设备系统版本： `Android 9 + Flyme 8`
- [x] Gradle 版本：`3.4.2`
- [x] QMUI Android 版本：`1.4.4`

### 具体问题描述 ###
Demo 不是沉浸式， 使用 StatusBarHelper 也不能实现
#### 问题截图 ####
[https://s2.ax1x.com/2019/11/21/MI1zNV.jpg](https://s2.ax1x.com/2019/11/21/MI1zNV.jpg)

**Comment by Theoneee** [comment]
Flyme 8  是吧？

**Comment by Theoneee** [comment]
[QMUIStatusBarHelper.zip](https://github.com/Tencent/QMUI_Android/files/3878755/QMUIStatusBarHelper.zip)

```
if (isStatusBarLightMode()) {
            QMUIStatusBarHelper.translucent(this);
            QMUIStatusBarHelper.setStatusBarLightMode(this);
        } else {
            QMUIStatusBarHelper.translucent(this,getColorr(R.color.qmui_config_color_transparent));
            QMUIStatusBarHelper.setStatusBarDarkMode(this);
        }
```

**Comment by Theoneee** [comment]
我也不记得改了什么。只记得是Flyme8用了Android的原生方案。
```
QMUIStatusBarHelper.translucent(this,getColorr(R.color.qmui_config_color_transparent));
```

这句是有些5.x的机型如果TopBar的背景是非白色，那么可以把状态栏的遮罩去掉。

**Comment by Theoneee** [comment]
@cgspine 大佬，这个应该解决下。QMUIStatusBarHelper里该换了。

**Comment by cgspine** [comment]
最新1.4.5改了这个，可以试试，我只是判断了版本，没有机器实测，可以试试看

**Comment by lydlovezjr** [comment]
1.4.5发布了吗,大佬

**Comment by cgspine** [comment]
已经发了
