### ISSUE TITLE
Kotlin 与 Fragment 框架

### ISSUE THREAD

**Issue by LLXBH** [Tencent/QMUI_Android#754]
平常都是在 onActivityCreated 初始化控件信息（比如Tab这些），现在发现不行了，现在返回的时候都会导致重新添加，有啥好的解决方法吗
1. 如果每次都在清理初始化前清理一次，会不会导致影响性能导致卡顿

**Comment by cgspine** [comment]
QMUIFragment 会缓存View的，添加了 onViewCreated(View)  方法（只有参数），可以在这里初始化控件，它和onCreateView() 是对应的，不会出现重复添加

**Comment by LLXBH** [comment]
> QMUIFragment 会缓存View的，添加了 onViewCreated(View) 方法（只有参数），可以在这里初始化控件，它和onCreateView() 是对应的，不会出现重复添加

非常感谢，解决了之前也有调用到 onViewCreated() （多个参数的），也会导致重复初始化
