### ISSUE TITLE
QMUITopBarLayout 关于自定义view对齐问题

### ISSUE THREAD

**Issue by turnmind** [Tencent/QMUI_Android#756]
使用 addLeftImageButton 方法添加的图片大小不合适，于是使用 addLeftView 添加 ImageView ，图片大小自适应，怎么解决上下居中对齐问题？【图】
[https://s2.ax1x.com/2019/11/28/QiUZdK.png](https://s2.ax1x.com/2019/11/28/QiUZdK.png)

**Comment by turnmind** [comment]
我目前只能想到用这种方法，请问有更合适的吗？  @cgspine 
`RelativeLayout.LayoutParams lp = new RelativeLayout.LayoutParams(
                RelativeLayout.LayoutParams.WRAP_CONTENT,
                RelativeLayout.LayoutParams.WRAP_CONTENT
        );
        lp.addRule(RelativeLayout.CENTER_VERTICAL);
        mTopBar.addLeftImageButton(R.drawable.ic_drawer_home, R.id.topbar_left_menu_button).setLayoutParams(lp);`

**Comment by cgspine** [comment]
addLeftView 支持传第三个参数，传一个 LayoutParams， 更合适一点。

**Comment by turnmind** [comment]
> addLeftView 支持传第三个参数，传一个 LayoutParams， 更合适一点。
`RelativeLayout.LayoutParams lp = new RelativeLayout.LayoutParams( 
                LayoutParams.WRAP_CONTENT, 
                LayoutParams.WRAP_CONTENT 
        ); 
        lp.addRule(RelativeLayout.CENTER_VERTICAL); 
        
        ImageView imageView = new ImageView(getContext()); 
        imageView.setImageResource(R.drawable.ic_drawer_home); 
        
        mTopBar.addLeftView(imageView, R.id.topbar_left_menu_button, lp);`

**Comment by turnmind** [comment]
` `
