### ISSUE TITLE
QMUIGroupListView Item的高度怎么设置呢？

### ISSUE THREAD

**Issue by smilesginger** [Tencent/QMUI_Android#757]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###

开发者您好！请问QMUIGroupListView Item的高度怎么设置呢？

**Comment by cgspine** [comment]
createItemView 时可以传入高度

**Comment by smilesginger** [comment]
> createItemView 时可以传入高度

这。。。谢谢了，怪自己没仔细看
