### ISSUE TITLE
沉浸式状态栏颜色没有覆盖

### ISSUE THREAD

**Issue by maxrco** [Tencent/QMUI_Android#759]
沉浸式生效了,但是里面的布局的状态栏颜色没有延伸进去,麻烦老大帮我看下哪里出了个问题.谢谢了!
![1](https://user-images.githubusercontent.com/24934356/69908851-5ecf9380-142c-11ea-9494-3d576e17b6d0.png)
![2](https://user-images.githubusercontent.com/24934356/69908852-6131ed80-142c-11ea-9df9-b42a94424284.png)
布局文件如下:
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawerLayout"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:fitsSystemWindows="true"
    android:background="@color/qmui_config_color_white"
    tools:context=".ui.home.HomeFragment">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        <com.qmuiteam.qmui.widget.QMUITopBar
            android:layout_width="match_parent"
            android:layout_height="?attr/qmui_topbar_height">

            <de.hdodenhof.circleimageview.CircleImageView
                android:id="@+id/civ_avatar"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_centerVertical="true"
                android:paddingLeft="5dp"
                android:src="@mipmap/ic_launcher" />

            <EditText
                android:id="@+id/et_search"
                android:layout_width="match_parent"
                android:layout_height="30dp"
                android:layout_centerVertical="true"
                android:layout_marginLeft="10dp"
                android:layout_marginRight="10dp"
                android:layout_toLeftOf="@+id/iv_mail"
                android:layout_toRightOf="@+id/civ_avatar"
                android:background="@drawable/shape_gray_30dp"
                android:drawableLeft="@drawable/search"
                android:drawablePadding="10dp"
                android:hint="搜索股票/基金/投顾/组合"
                android:paddingLeft="10dp" />

            <ImageView
                android:id="@+id/iv_mail"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:layout_alignParentRight="true"
                android:layout_centerVertical="true"
                android:paddingRight="5dp"
                android:src="@mipmap/ic_launcher" />

        </com.qmuiteam.qmui.widget.QMUITopBar>

        <android.support.v7.widget.RecyclerView
            android:id="@+id/rv_home"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </LinearLayout>

    <LinearLayout
        android:layout_width="match_parent"
        android:orientation="vertical"
        android:layout_gravity="left"
        android:fitsSystemWindows="true"
        android:background="@color/qmui_config_color_red"
        android:layout_height="match_parent">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@color/qmui_config_color_black"
            android:layout_gravity="center"
            android:text="侧滑栏"/>
    </LinearLayout>
</android.support.v4.widget.DrawerLayout>

**Comment by cgspine** [comment]
看了下 DrawerLayout 的代码，它会取 colorPrimaryDark 然后 draw 在状态栏下面, 你可以通过 `setStatusBarBackgroundColor(0)` 将它改为透明的。

**Comment by maxrco** [comment]
谢谢老大,终于解决了,开心!必须star一波,老大回复也是神速受宠若惊

**Comment by maxrco** [comment]
老大什么出Kotlin版本很期待呢

**Comment by cgspine** [comment]
会加入kotlin的支持， 2.0.0-alpha01已经有了一点kotlin代码了，它的作用只是让代码写起来更舒服
