### ISSUE TITLE
官方apk打不开

### ISSUE THREAD

**Issue by wang2793312458** [Tencent/QMUI_Android#761]
Unable to start activity ComponentInfo{com.qmuiteam.qmuidemo/com.qmuiteam.qmuidemo.QDMainActivity}: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class android.view.ViewStub

**Comment by wang2793312458** [comment]
红米note3手机，从官网下的apk

**Comment by xcb322612** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qmuiteam.qmuidemo/com.qmuiteam.qmuidemo.QDMainActivity}: android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class <unknown>

**Comment by cgspine** [comment]
#766

**Comment by cgspine** [comment]
2.0.0-alpha02 版本修复了
