### ISSUE TITLE
QMUIBottomSheet弹出后，被底部虚拟导航栏遮挡

### ISSUE THREAD

**Issue by zaaach** [Tencent/QMUI_Android#763]
### 运行环境 ###

- [x] 设备型号：`Samsung A9Star`
- [x] 设备系统版本： `Android 9.0`
- [x] Gradle 版本： `官方demo`
- [x] QMUI Android 版本：`2.0.0-alpha01`

### 具体问题描述 ###
QMUIBottomSheet弹出后，底部虚拟导航栏变透明了，也被遮挡了
#### 问题截图 ####
![微信图片_20191202092315](https://user-images.githubusercontent.com/9695127/69924256-71f26a00-14e5-11ea-8844-63061b938f58.jpg)

**Comment by cgspine** [comment]
2.0.0-alpha02 已修复
