### ISSUE TITLE
 2.0.0-alpha01 Demo问题

### ISSUE THREAD

**Issue by mny459** [Tencent/QMUI_Android#764]
### 运行环境 ###

- [x] 设备型号：华为 Nova 3
- [x] 设备系统版本：9
- [x] Gradle 版本：5.6.1
- [x] QMUI Android 版本：github上的版本 2.0.0-alpha01 试跑

### 具体问题描述 ###
尝试运行最新Demo，遇到以下几个问题
1. 两个编译的优化文件见 异常日志
2. QMUIBottomSheet 从Demo的效果上看似乎没有做底部导航栏的适配？
#### 问题截图 ####
1. QMUIBottomSheet 与底部导航栏重合
![image](https://user-images.githubusercontent.com/24559456/69925662-4921a300-14ec-11ea-9a42-267535995205.png)
2. 倒数第二个Item的布局似乎有问题
#### 异常日志（堆栈） ####
1. 没有签名文件
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qmuidemo:validateSigningRelease'.
> Keystore file 'D:\code\github\QMUI_Android\qmuidemo\qmuidemo.keystore' not found for signing config 'release'.
```
2. 应该是编译的一个优化提示吧
```
> Configure project :qmui
Kotlin plugin should be enabled before 'kotlin-android-extensions'
```

**Comment by cgspine** [comment]
#763 BottomSheet 的是Bug， 我改改。
1. 签名是 release 包用的，这个不会放到 git 提交的。
2. 优化提示我改改

**Comment by cgspine** [comment]
2.0.0-alpha02 已修改
