### ISSUE TITLE
CustomDialogBuilder  如何取到布局id 

### ISSUE THREAD

**Issue by z876335662** [Tencent/QMUI_Android#767]
CustomDialogBuilder  如何取到布局id   看源码这个设置进去的setLayout  没办法获取设布局

**Comment by cgspine** [comment]
你是想直接设置一个 View 进去 ？ 这样你可以直接继承 QMUIDialogBuilder，重写 onCreateContent 方法。

**Comment by z876335662** [comment]
![image](https://user-images.githubusercontent.com/6060307/69943546-683a2800-1520-11ea-8141-6b338dc92510.png)
为啥不给个getLayout View  现在是 qmuiDialog.getWindow().getDecorView() 获取

**Comment by cgspine** [comment]
创建出dialog 后，通过 dialog.findViewById(你传入的layoutRes) 就可以取出来了

**Comment by z876335662** [comment]
好的 谢谢
