### ISSUE TITLE
自定义style为啥不起作用

### ISSUE THREAD

**Issue by hjywyj** [Tencent/QMUI_Android#769]
<com.qmuiteam.qmui.widget.roundwidget.QMUIRoundButton
                style="@style/QMUI.Button.Red.Radius"
                android:layout_width="match_parent"
                android:layout_height="40dp"
                android:layout_marginTop="34dp"
                android:gravity="center"
                android:text="登录"
                app:qmui_radius="20dp" />

    <style name="QMUI.Button" parent="@style/ButtonBase.Compat" />
    <style name="QMUI.Button.Red" parent="QMUI.Button">
        <item name="qmui_backgroundColor">@color/qmui_btn_red_bg</item>
        <item name="android:textColor">@color/qmui_btn_white_text</item>
        <item name="qmui_borderColor">@color/qmui_btn_red_border</item>
        <item name="qmui_isRadiusAdjustBounds">false</item>
    </style>
    <style name="QMUI.Button.Red.Radius" parent="QMUI.Button.Red">
        <item name="qmui_isRadiusAdjustBounds">true</item>
    </style>

**Comment by Theoneee** [comment]
![image](https://user-images.githubusercontent.com/32156330/70007792-aa10b000-15ac-11ea-8cef-a956205b387f.png)


```
    <com.qmuiteam.qmui.widget.roundwidget.QMUIRoundButton
        style="@style/QMUI.Button.Red.Radius"
        android:layout_width="match_parent"
        android:layout_height="40dp"
        android:layout_marginTop="34dp"
        android:layout_margin="30dp"
        android:layout_centerInParent="true"
        android:text="登录"
        app:qmui_radius="5dp" />
```
 style是按照你的写的。这样对你来说是生效了还是没生效呢。

**Comment by hjywyj** [comment]
implementation  "com.qmuiteam:skin:0.0.1"    error?

**Comment by hjywyj** [comment]
how to use skin？

**Comment by Theoneee** [comment]
demo

**Comment by hjywyj** [comment]
demo修改后的截图
https://oscimg.oschina.net/oscnet/up-0942e59e84e8a0c0fa521f962f6073ca69b.png
https://oscimg.oschina.net/oscnet/up-477ad826a578679f37724a6f0ee0469bbb7.JPEG

**Comment by hjywyj** [comment]
在demo基础上修改，没起效果
https://oscimg.oschina.net/oscnet/up-e8aa78b8796f3fac4c0b03381c5073de1da.png
https://oscimg.oschina.net/oscnet/up-46bcc831669785d6382e92ce6b054ab0207.JPEG

**Comment by cgspine** [comment]
没有 com.qmuiteam:skin:0.0.1 的， QMUI 就包含了换肤的功能的

**Comment by cgspine** [comment]
Demo 是收到 QMUISkinManager 换肤的影响，你在 QDMainActivity 里 重写 followSkin 然后返回 false， 应该就可以看到你想要的效果了

**Comment by cgspine** [comment]
Demo 是受到 QMUISkinManager 换肤的影响，你在 QDMainActivity 里 重写 followSkin 然后返回 false， 应该就可以看到你想要的效果了

**Comment by hjywyj** [comment]
> Demo 是受到 QMUISkinManager 换肤的影响，你在 QDMainActivity 里 重写 followSkin 然后返回 false， 应该就可以看到你想要的效果了

谢谢，我先看看，我通过这种方式实现了
<style name="QMUI.Button.Blue" parent="QMUI.Button">
        <item name="qmui_skin_background">?attr/qmui_button_blue</item>
        <item name="qmui_skin_text_color">?attr/qmui_button_white</item>
        <item name="qmui_skin_border">?attr/qmui_button_blue</item>
        <item name="qmui_isRadiusAdjustBounds">false</item>
    </style>

**Comment by hjywyj** [comment]
@cgspine 
在demo基础上，写了个testActivity，换肤成功
将testActivity 改为databinding，换肤失败

**Comment by cgspine** [comment]
没测试过 DataBinding， 可能是  databinding 也设置了 LayoutInflaterFactory， 应该 java 方式设置可以
