### ISSUE TITLE
请教作者

### ISSUE THREAD

**Issue by brucewuu520** [Tencent/QMUI_Android#776]
在继承QMUIActivity或QMUIFragment后，实现沉浸式状态栏还需要在自己的布局文件最外层嵌套QMUIWindowInsetLayout，查看QMUIActivity和QMUIFragment源码发现，在我们布局的最外层包裹了一层SwipeBackLayout，而这个SwipeBackLayout正是继承了QMUIWindowInsetLayout；这样会显得布局嵌套冗余，可否在SwipeBackLayout直接支持沉浸式状态栏，这样我们就不用在自己的局部最外层再嵌套一个QMUIWindowInsetLayout了；
另外滑动返回时，把window设置为透明的了，一般情况下我设置布局背景是用android:windowBackground全局设定的，不会再设置自己的布局最外层background，这样滑动返回就尴尬了，当前activity直接透明了，QMUIActivity可以曝露接口设置SwipeBackLayout的背景，这样就可以在基类中统一设置activity的背景了

**Comment by bastYYJ** [comment]
不是必须需要嵌套QMUIWindowInsetLayout 的吧

**Comment by brucewuu520** [comment]
好像还真的需要，如果设置translucentFull() 返回true，状态栏是沉浸了，但TopBarLayout会伸入状态栏底部，设置android:fitsSystemWindows="true" 或者false都没有用

**Comment by bastYYJ** [comment]
我用QMUITopBar ，继承QMUIActivity 就能实现沉浸了。

**Comment by brucewuu520** [comment]
@bastYYJ 请教下你是怎么弄的，我用的是2.0.0-alpha02版本，布局里中QMUITopBar/QMUITopBarLayout都试过，translucentFull()返回true/false都试过，就是不行呢

**Comment by brucewuu520** [comment]
看TranslucentActivity示例方案，使用QMUITopBar，布局最外层可以随意用，但是设置背景颜色，如果内容背景颜色一般为白色或灰白色，那又要设置内容部分的背景色，还是得再套一层layout，设置其背景色，这种方式并不通用，而且设置的背景色过多，overdraw了；
通常即使不继承QMUIActivity，使用普通的AppCompatActivity，QMUITopBarLayout配合QMUIWindowInsetLayout可实现沉浸式状态栏，那么既然继承了QMUIActivity就不想再套一层QMUIWindowInsetLayout了，何解呢

**Comment by brucewuu520** [comment]
@cgspine 看到你上线了，能否回复下我这个问题呀

**Comment by cgspine** [comment]
1.  SwipeBackLayout 那一层完全是为了手势返回用的， 手势返回时会移动内容 View，因此内容嵌套的 Layout 必须存在。
2. 沉浸式放在内容区做，是因为有些情况你会希望图片延伸的状态栏下，所以还不如提供一个完全自由的环境，由使用者根据业务再封装一下（比如你的所有界面都是 Topbar + 内容区域， 那你可以封装一个基类。）
3. TranslucentActivity 我会去改成 QMUIWindowInsetLayout 实现。 不 translucentFull() ，你就要单独处理状态栏的背景，TranslucentActivity 也就是使用背景来取代状态栏的背景，不是个号方案，目前应该也直接去 setStatusBarBackground，但是不能处理 Android 6 一下的机器。
4.  Activity 手势返回，正常情况下是不会把 window 改成透明的，只有横竖屏发生变化才会， 这个目前我没有更好的办法，不然会发生 crash？
5. Activity 一般不要去设置透明，因为这样背后那个Activity 不会 stop，一直在后面跑，比你用两层 背景更浪费性能。

主要是不同版本兼容性和易用性的一些取舍，官方提供的 api 就那么多，有时为了功能而增添了层级或者 overdraw，这也是没办法的事情。或许有的存在更好的方式，也欢迎交流。

**Comment by brucewuu520** [comment]
1、2：布局内容不能直接用merge，必须要嵌套一层layout可以理解，但不可以不要必须是QMUIWindowInsetLayout，其他的Layout也可以；
5、我并没有Activity设为透明，windowBackground也设置有颜色，不过自己布局的layout没有设置background，在滑动返回的时候，整个Activity变透明了，直接能看到底下的UI

**Comment by brucewuu520** [comment]
我把arch代码拉下来改源码测试，其实可以把SwipeBackLayout里这段代码去掉：
`@Override
    public boolean applySystemWindowInsets19(Rect insets) {
        super.applySystemWindowInsets19(insets);
        return true;
    }

    @Override
    public boolean applySystemWindowInsets21(Object insets) {
        super.applySystemWindowInsets21(insets);
        return true;
    }`
QMUIActivity和QMUIFragment里的这段代码去掉：
`if (translucentFull()) {
            swipeBackLayout.getContentView().setFitsSystemWindows(false);
        } else {
            swipeBackLayout.getContentView().setFitsSystemWindows(true);
        }`
我们的布局最外层不用QMUIWindowInsetLayout用其他的layout也可以实现沉浸式，ImageView也可以伸到状态栏底部
如果用户不想使用沉浸式，可以在自己布局的最外层layout加上，android:fitsSystemWindows="true"

**Comment by cgspine** [comment]
1. 不用 QMUIWindowInsetLayout， 就没办法处理内容有的 View 需要 fitSystemWindows 为 true，有的 View 需要 fitSystemWindows 为 false 的场景啊，fitSystemWindows 要想多 view 特殊处理，就必须一层层的用 QMUIWindowInsetLayout 派发，这是 Android 系统的坑。 当然只要容器自定义处理了 fitSystemWindows 的派发，不用 QMUIWindowInsetLayout 也是可以的， 例如 QMUI 2 提供了QMUIWindowInsetLayout2，实际上是 ConstraintLayout，如果你需要其它的 Layout，你可以同样处理。
2. 那个不是 window 透明，是我把背后的 View 绘制到了当前 window 的底部，所以内容区域是必须要背景的，这样手势返回才不会出翔。

**Comment by cgspine** [comment]
你说的方案，如果需要图片延伸的顶部，TopBar 沉浸式，要怎么做？

**Comment by brucewuu520** [comment]
按照上面改了后，使用TopBarLayout是可以沉浸式的，图片在底部，TopBarLayout初始alpha设为0，滑动时改变其alpha值

**Comment by cgspine** [comment]
这样就是 TopBarLayout 消耗 fitSystemWindow，那如果我再添加一个内容区域，需要让它沉浸式，应该就无效了。 因为系统自己的  fitSystemWindow 消耗机制就是只要有一个消耗了 fitSystemWindow， 那就不派发了。

QMUI 是，如果用 WindowInsetLayout 包裹，每个子 View 都有机会决定自己要不要沉浸式。 如果不用 WindowInsetLayout 包裹， 则由 QMUIFragment. translucentFull() 来决定整个界面要不要沉浸式。

你提供的这种是， 最外层用 fitSystemWindow 来决定整个界面要不要沉浸式， 或者选择一个子 View 来沉浸式。

**Comment by brucewuu520** [comment]
嗯，是这样的，了解了，谢谢!
