### ISSUE TITLE
QMUIPopup如果从页面的顶部弹出?

### ISSUE THREAD

**Issue by YxmCute** [Tencent/QMUI_Android#777]
### 运行环境 ###

- [x] 设备型号：如：`RedMI Note8`
- [x] 设备系统版本：如 `Android 8.0`
- [x] QMUI Android 版本：`1.4.0`

### 具体问题描述 ###
如图

#### 问题截图 ####
![TIM截图20191206183757.jpg](https://i.loli.net/2019/12/06/Ot5VkmlFKTna7UZ.jpg)

**Comment by cgspine** [comment]
目前没有这种使用方式，不过你这种也复用不了多少，可能直接用原生的 PopupWindow 就可以，从组件化来说，也没办法进一步封装了。从业务上可以通过 PopupWindow 封装

**Comment by YxmCute** [comment]
我一直没写出效果，我以为是我的写法错了，好的，谢谢,感谢回答
