### ISSUE TITLE
qmui_skin_support_common_list_icon_tint_color的问题

### ISSUE THREAD

**Issue by hjywyj** [Tencent/QMUI_Android#779]
qmui_common_list_item里的ImageView加了tint_color，导致我传颜色不一样的彩色图片，显示有问题
tint_color改为了透明/白色也不行

**Comment by cgspine** [comment]
稍后我加一个方法，可以让它不跟随skin

**Comment by hjywyj** [comment]
还有，关于QMUIEmptyView的
有这个属性
qmui_skin_support_empty_view_btn_border_color
却没有border_width
定义了background为白色，字为蓝色，border为蓝色，结果border没生效

**Comment by cgspine** [comment]
我加一下 border_width，我试了 qmui_skin_support_empty_view_btn_border_color 是可以生效的，你的没生效是整个 border 没显示？

**Comment by hjywyj** [comment]
> 我加一下 border_width，我试了 qmui_skin_support_empty_view_btn_border_color 是可以生效的，你的没生效是整个 border 没显示？

对的，跟border_width为0的效果一样，背景白色，border没显示，光有字了，成了TextView了

**Comment by cgspine** [comment]
可以贴下你的代码吗？

**Comment by hjywyj** [comment]
就是修改了style的几个empty_btn的颜色属性
`    <style name="QMUI" parent="AppConfigTheme">

        
        <item name="qmui_topbar_height">56dp</item>
        
        <item name="qmui_skin_support_topbar_separator_color">?attr/qmui_skin_support_color_separator</item>
        <item name="qmui_skin_support_topbar_bg">?attr/qmui_config_color_blue</item>
        <item name="qmui_skin_support_topbar_title_color">?attr/qmui_config_color_white</item>
        <item name="qmui_skin_support_topbar_subtitle_color">?attr/qmui_config_color_white</item>
        <item name="qmui_skin_support_topbar_text_btn_color_state_list">?attr/qmui_config_color_white</item>
        <item name="qmui_skin_support_topbar_image_tint_color">?attr/qmui_config_color_white</item>
        

        

        
        <item name="qmui_skin_support_tab_bg">?attr/qmui_config_color_white</item>
        <item name="qmui_skin_support_tab_separator_color">?attr/qmui_skin_support_color_separator</item>
        <item name="qmui_skin_support_tab_normal_color">?attr/qmui_config_color_gray_6</item>
        <item name="qmui_skin_support_tab_selected_color">?attr/qmui_config_color_blue</item>
        <item name="qmui_skin_support_tab_sign_count_view_text_color">?attr/qmui_config_color_white</item>
        <item name="qmui_skin_support_tab_sign_count_view_bg_color">?attr/qmui_config_color_blue</item>
        


        <item name="qmui_tab_sign_count_view">@style/QMUI.TabSegment.SignCount</item>
        <item name="qmui_tab_sign_count_view_minSize">@dimen/qmui_tab_sign_count_view_minSize</item>
        <item name="qmui_tab_sign_count_view_minSize_with_text">
            @dimen/qmui_tab_sign_count_view_minSize_with_text
        </item>
        <item name="qmui_tab_sign_count_view_padding_horizontal">4dp</item>

        

        
        <item name="qmui_skin_support_round_btn_bg_color">?attr/qmui_config_color_blue</item>
        <item name="qmui_skin_support_round_btn_border_color">?attr/qmui_config_color_blue</item>
        <item name="qmui_skin_support_round_btn_text_color">@color/qmui_config_color_white</item>
        

        <item name="qmui_round_btn_text_size">@dimen/qmui_btn_text_size</item>
        <item name="qmui_round_btn_border_width">@dimen/qmui_btn_border_width</item>

        

        
        <item name="qmui_skin_support_loading_color">@color/qmui_config_color_gray_5</item>
        

        <item name="qmui_loading_size">20dp</item>


        

        
        <item name="qmui_skin_support_empty_view_loading_color">?attr/qmui_skin_support_loading_color</item>
        <item name="qmui_skin_support_empty_view_title_color">?attr/qmui_config_color_gray_3</item>
        <item name="qmui_skin_support_empty_view_sub_title_color">?attr/qmui_config_color_gray_3</item>
        <item name="qmui_skin_support_empty_view_btn_bg_color">?attr/qmui_config_color_white</item>
        <item name="qmui_skin_support_empty_view_btn_border_color">?attr/qmui_config_color_blue</item>
        <item name="qmui_skin_support_empty_view_btn_text_color">?attr/qmui_config_color_blue</item>
        

        <item name="qmui_empty_view_loading_size">?attr/qmui_loading_size</item>
        <item name="qmui_empty_view_title_normal_margin_top">16dp</item>
        <item name="qmui_empty_view_title_text_size">16sp</item>
        <item name="qmui_empty_view_title_margin_hor">?attr/qmui_content_spacing_horizontal</item>
        <item name="qmui_empty_view_sub_title_normal_margin_top">16dp</item>
        <item name="qmui_empty_view_sub_title_text_size">14sp</item>
        <item name="qmui_empty_view_sub_title_margin_hor">?attr/qmui_content_spacing_horizontal</item>
        <item name="qmui_empty_view_btn_height">36dp</item>
        <item name="qmui_empty_view_btn_margin_hor">55dp</item>
        <item name="qmui_empty_view_btn_text_size">14sp</item>
        <item name="qmui_empty_view_btn_normal_margin_top">10dp</item>


        

        
        <item name="qmui_skin_support_common_list_title_color">?attr/qmui_config_color_gray_1</item>
        <item name="qmui_skin_support_common_list_detail_color">?attr/qmui_config_color_gray_5</item>
        <item name="qmui_skin_support_common_list_icon_tint_color">?attr/qmui_config_color_blue</item>
        <item name="qmui_skin_support_common_list_red_point_tint_color">?attr/qmui_config_color_white</item>
        <item name="qmui_skin_support_common_list_new_drawable">@drawable/qmui_icon_tip_new</item>
        <item name="qmui_skin_support_common_list_separator_color">?attr/qmui_skin_support_color_separator</item>
        <item name="qmui_skin_support_s_common_list_bg">?attr/qmui_skin_support_s_list_item_bg_2</item>
        <item name="qmui_skin_support_common_list_chevron_color">?attr/qmui_config_color_gray_5</item>
        

        <item name="qmui_common_list_item_icon_margin_right">12dp</item>
        <item name="qmui_common_list_item_accessory_margin_left">14dp</item>
        <item name="qmui_common_list_item_title_v_text_size">15sp</item>
        <item name="qmui_common_list_item_title_h_text_size">16sp</item>
        <item name="qmui_common_list_item_title_line_space">5dp</item>
        <item name="qmui_common_list_item_detail_v_text_size">13sp</item>
        <item name="qmui_common_list_item_detail_h_text_size">14sp</item>
        <item name="qmui_common_list_item_detail_line_space">5dp</item>
        <item name="qmui_common_list_item_detail_h_margin_with_title">20dp</item>
        <item name="qmui_common_list_item_detail_h_margin_with_title_large">52dp</item>
        <item name="qmui_common_list_item_detail_v_margin_with_title">4dp</item>
        <item name="qmui_common_list_item_holder_margin_with_title">8dp</item>
        <item name="qmui_common_list_item_chevron">@drawable/qmui_icon_chevron</item>
        <item name="qmui_common_list_item_switch">@drawable/qmui_s_icon_switch</item>


        <item name="qmui_content_padding_horizontal">@dimen/qmui_content_padding_horizontal
        </item> 
        <item name="qmui_content_spacing_horizontal">@dimen/qmui_content_spacing_horizontal</item>

        
        <item name="qmui_config_color_white">@color/qmui_config_color_white</item>
        <item name="qmui_config_color_blue">@color/qmui_config_color_blue</item>
        <item name="qmui_config_color_red">@color/qmui_config_color_red</item>
        <item name="qmui_config_color_transparent">@color/qmui_config_color_transparent</item>
        <item name="qmui_button_black">@color/qmui_config_color_black</item>
        <item name="qmui_button_blue">@color/qmui_config_color_blue</item>
        <item name="qmui_button_cyan">@color/qmui_config_color_cyan</item>
        <item name="qmui_button_gray">@color/qmui_config_color_gray_8</item>
        <item name="qmui_button_green">@color/qmui_config_color_green</item>
        <item name="qmui_button_red">@color/qmui_config_color_red</item>
        <item name="qmui_button_white">@color/qmui_config_color_white</item>
        <item name="qmui_button_yellow">@color/qmui_config_color_yellow</item>

        <item name="qmui_config_color_black">@color/qmui_config_color_black</item>
        <item name="qmui_config_color_link">@color/qmui_config_color_link</item>
        <item name="qmui_config_color_pressed">@color/qmui_config_color_pressed</item>

        <item name="qmui_config_color_gray_1">@color/qmui_config_color_gray_1</item>
        <item name="qmui_config_color_gray_2">@color/qmui_config_color_gray_2</item>
        <item name="qmui_config_color_gray_3">@color/qmui_config_color_gray_3</item>
        <item name="qmui_config_color_gray_4">@color/qmui_config_color_gray_4</item>
        <item name="qmui_config_color_gray_5">@color/qmui_config_color_gray_5</item>
        <item name="qmui_config_color_gray_6">@color/qmui_config_color_gray_6</item>
        <item name="qmui_config_color_gray_7">@color/qmui_config_color_gray_7</item>
        <item name="qmui_config_color_gray_8">@color/qmui_config_color_gray_8</item>
        <item name="qmui_config_color_gray_9">@color/qmui_config_color_gray_9</item>

        <item name="qmui_alpha_pressed">0.5</item>
        <item name="qmui_alpha_disabled">0.5</item>

        <item name="qmui_general_shadow_elevation">14dp</item>
        <item name="qmui_general_shadow_alpha">0.25</item>

        <item name="qmui_skin_support_activity_background">@color/qmui_config_color_background</item>
        <item name="qmui_skin_support_color_separator">@color/qmui_config_color_separator</item>
        <item name="qmui_skin_support_color_separator_darken">@color/qmui_config_color_separator_darken</item>
        <item name="qmui_skin_support_color_background">@color/qmui_config_color_background</item>
        <item name="qmui_skin_support_color_background_pressed">@color/qmui_config_color_background_pressed</item>
        <item name="qmui_skin_support_pull_refresh_view_color">?attr/qmui_config_color_blue</item>

        
        <item name="qmui_dialog_min_width">260dp</item>
        <item name="qmui_dialog_max_width">320dp</item>
        <item name="qmui_dialog_radius">@dimen/qmui_dialog_radius</item>
        <item name="qmui_dialog_inset_hor">40dp</item>
        <item name="qmui_dialog_inset_ver">20dp</item>
        <item name="qmui_dialog_background_dim_amount">0.6</item>
        <item name="qmui_dialog_padding_horizontal">24dp</item>
        <item name="qmui_dialog_edit_margin_top">20dp</item>
        <item name="qmui_dialog_edit_margin_bottom">24dp</item>
        <item name="qmui_dialog_edit_bottom_line_height">1dp</item>
        <item name="qmui_dialog_title_style">@style/QMUI.Dialog.Title</item>
        <item name="qmui_dialog_message_content_style">@style/QMUI.Dialog.MessageContent</item>
        <item name="qmui_dialog_action_container_style">@style/QMUI.Dialog.ActionContainer</item>
        <item name="qmui_dialog_action_style">@style/QMUI.Dialog.Action</item>
        <item name="qmui_dialog_edit_content_style">@style/QMUI.Dialog.EditContent</item>
        <item name="qmui_dialog_menu_container_style">@style/QMUI.Dialog.MenuContainer</item>
        <item name="qmui_dialog_menu_item_style">@style/QMUI.Dialog_MenuItem</item>


        <item name="qmui_skin_support_dialog_bg">@color/qmui_config_color_white</item>
        <item name="qmui_skin_support_dialog_title_text_color">?attr/qmui_config_color_black</item>
        <item name="qmui_skin_support_dialog_message_text_color">?attr/qmui_config_color_gray_4</item>
        <item name="qmui_skin_support_dialog_action_bg">@null</item>
        <item name="qmui_skin_support_dialog_action_text_color">?attr/qmui_config_color_blue</item>
        <item name="qmui_skin_support_dialog_positive_action_text_color">?attr/qmui_config_color_blue</item>
        <item name="qmui_skin_support_dialog_negative_action_text_color">?attr/qmui_config_color_blue</item>
        <item name="qmui_skin_support_dialog_action_divider_color">?attr/qmui_skin_support_color_separator</item>
        <item name="qmui_skin_support_dialog_edit_bottom_line_color">?attr/qmui_skin_support_color_separator</item>
        <item name="qmui_skin_support_dialog_edit_text_color">?attr/qmui_config_color_black</item>
        <item name="qmui_skin_support_dialog_edit_text_hint_color">?attr/qmui_config_color_gray_3</item>
        <item name="qmui_skin_support_s_dialog_menu_item_bg">?attr/qmui_skin_support_s_list_item_bg_1</item>
        <item name="qmui_skin_support_dialog_menu_item_text_color">?attr/qmui_config_color_black</item>
        <item name="qmui_skin_support_s_dialog_check_drawable">?attr/qmui_skin_support_s_checkbox</item>
        <item name="qmui_skin_support_dialog_mark_drawable">?attr/qmui_skin_support_icon_mark</item>

        <item name="qmui_skin_def_dialog_bg">qmui_skin_support_dialog_bg</item>
        <item name="qmui_skin_def_dialog_title_text_color">qmui_skin_support_dialog_title_text_color</item>
        <item name="qmui_skin_def_dialog_message_text_color">qmui_skin_support_dialog_message_text_color</item>
        <item name="qmui_skin_def_s_dialog_check_drawable">qmui_skin_support_dialog_s_check_drawable</item>
        <item name="qmui_skin_def_dialog_mark_drawable">qmui_skin_support_dialog_mark_drawable</item>
        <item name="qmui_skin_def_dialog_edit_bottom_line_color">qmui_skin_support_dialog_edit_bottom_line_color</item>
        <item name="qmui_skin_def_dialog_edit_text_color">qmui_skin_support_dialog_edit_text_color</item>
        <item name="qmui_skin_def_dialog_edit_text_hint_color">qmui_skin_support_dialog_edit_text_hint_color</item>
        <item name="qmui_skin_def_s_dialog_menu_item_bg">qmui_skin_support_s_dialog_menu_item_bg</item>
        <item name="qmui_skin_def_dialog_menu_item_text_color">qmui_skin_support_dialog_menu_item_text_color</item>


        
        <item name="qmui_tip_dialog_min_width">120dp</item>
        <item name="qmui_tip_dialog_min_height">40dp</item>
        <item name="qmui_tip_dialog_max_width">270dp</item>
        <item name="qmui_tip_dialog_padding_vertical">14dp</item>
        <item name="qmui_tip_dialog_padding_horizontal">?attr/qmui_content_padding_horizontal</item>
        <item name="qmui_tip_dialog_radius">15dp</item>
        <item name="qmui_tip_dialog_loading_size">32dp</item>
        <item name="qmui_tip_dialog_text_margin_top">12dp</item>
        <item name="qmui_tip_dialog_text_size">14sp</item>

        <item name="qmui_skin_support_tip_dialog_bg">@color/qmui_config_color_75_pure_black</item>
        <item name="qmui_skin_support_tip_dialog_loading_color">@color/qmui_config_color_white</item>
        <item name="qmui_skin_support_tip_dialog_text_color">@color/qmui_config_color_white</item>
        <item name="qmui_skin_support_tip_dialog_icon_success_src">@drawable/qmui_icon_notify_done</item>
        <item name="qmui_skin_support_tip_dialog_icon_error_src">@drawable/qmui_icon_notify_error</item>
        <item name="qmui_skin_support_tip_dialog_icon_info_src">@drawable/qmui_icon_notify_info</item>

        <item name="qmui_skin_def_tip_dialog_bg">qmui_skin_support_tip_dialog_bg</item>
        <item name="qmui_skin_def_tip_dialog_loading_color">qmui_skin_support_tip_dialog_loading_color</item>
        <item name="qmui_skin_def_tip_dialog_text_color">qmui_skin_support_tip_dialog_text_color</item>
        <item name="qmui_skin_def_tip_dialog_icon_success_src">qmui_skin_support_tip_dialog_icon_success_src</item>
        <item name="qmui_skin_def_tip_dialog_icon_error_src">qmui_skin_support_tip_dialog_icon_error_src</item>
        <item name="qmui_skin_def_tip_dialog_icon_info_src">qmui_skin_support_tip_dialog_icon_info_src</item>

        
        <item name="qmui_list_item_height">@dimen/qmui_list_item_height</item>
        <item name="qmui_list_item_height_higher">@dimen/qmui_list_item_height_higher</item>

        <item name="qmui_skin_support_s_list_item_bg_1">@drawable/qmui_s_list_item_bg_1</item>
        <item name="qmui_skin_support_s_list_item_bg_2">@drawable/qmui_s_list_item_bg_2</item>


        
        <item name="qmui_skin_support_s_checkbox">@drawable/qmui_s_checkbox</item>
        <item name="qmui_skin_support_icon_mark">@drawable/qmui_icon_checkmark</item>

        
        <item name="qmui_skin_support_slider_bar_bg_color">?attr/qmui_config_color_gray_3</item>
        <item name="qmui_skin_support_slider_bar_progress_color">?attr/qmui_config_color_blue</item>
        <item name="qmui_skin_support_slider_thumb_bg_color">@color/qmui_config_color_white</item>
        <item name="qmui_skin_support_slider_thumb_border_color">?attr/qmui_skin_support_color_separator</item>


        
        <item name="qmui_skin_support_bottom_sheet_bg">@color/qmui_config_color_white</item>
        <item name="qmui_skin_support_bottom_sheet_title_text_color">?attr/qmui_config_color_gray_5</item>
        <item name="qmui_skin_support_bottom_sheet_cancel_text_color">?attr/qmui_config_color_black</item>
        <item name="qmui_skin_support_bottom_sheet_cancel_bg">?attr/qmui_skin_support_s_list_item_bg_1</item>
        <item name="qmui_skin_support_bottom_sheet_separator_color">?attr/qmui_skin_support_color_separator</item>
        <item name="qmui_skin_support_bottom_sheet_list_item_bg">?attr/qmui_skin_support_s_list_item_bg_1</item>
        <item name="qmui_skin_support_bottom_sheet_list_item_text_color">?attr/qmui_config_color_black</item>
        <item name="qmui_skin_support_bottom_sheet_list_red_point_color">?attr/qmui_config_color_blue</item>
        <item name="qmui_skin_support_bottom_sheet_list_mark">?attr/qmui_skin_support_icon_mark</item>
        <item name="qmui_skin_support_bottom_sheet_grid_item_text_color">?attr/qmui_config_color_gray_3</item>

        <item name="qmui_skin_def_bottom_sheet_bg">qmui_skin_support_bottom_sheet_bg</item>
        <item name="qmui_skin_def_bottom_sheet_title_text_color">qmui_skin_support_bottom_sheet_title_text_color</item>
        <item name="qmui_skin_def_bottom_sheet_cancel_text_color">qmui_skin_support_bottom_sheet_cancel_text_color</item>
        <item name="qmui_skin_def_bottom_sheet_cancel_bg">qmui_skin_support_bottom_sheet_cancel_bg</item>
        <item name="qmui_skin_def_bottom_sheet_separator_color">qmui_skin_support_bottom_sheet_separator_color</item>
        <item name="qmui_skin_def_bottom_sheet_list_item_bg">qmui_skin_support_bottom_sheet_list_item_bg</item>
        <item name="qmui_skin_def_bottom_sheet_list_red_point_color">qmui_skin_support_bottom_sheet_list_red_point_color</item>
        <item name="qmui_skin_def_bottom_sheet_list_mark">qmui_skin_support_bottom_sheet_list_mark</item>

        <item name="qmui_bottom_sheet_radius">12dp</item>
        <item name="qmui_bottom_sheet_padding_hor">?attr/qmui_content_padding_horizontal</item>
        <item name="qmui_bottom_sheet_use_percent_min_height">640dp</item>
        <item name="qmui_bottom_sheet_height_percent">0.75</item>
        <item name="qmui_bottom_sheet_max_width">500dp</item>
        <item name="qmui_bottom_sheet_background_dim_amount">0.6</item>
        <item name="qmui_bottom_sheet_cancel_btn_height">56dp</item>
        <item name="qmui_bottom_sheet_list_item_height">56dp</item>
        <item name="qmui_bottom_sheet_list_item_icon_size">22dp</item>
        <item name="qmui_bottom_sheet_list_item_red_point_size">@dimen/qmui_tips_point_size</item>
        <item name="qmui_bottom_sheet_list_item_icon_margin_right">12dp</item>
        <item name="qmui_bottom_sheet_list_item_mark_margin_left">12dp</item>
        <item name="qmui_bottom_sheet_list_item_tip_point_margin_left">4dp</item>
        <item name="qmui_bottom_sheet_grid_padding_vertical">12dp</item>
        <item name="qmui_bottom_sheet_grid_line_vertical_space">0dp</item>
        <item name="qmui_bottom_sheet_grid_item_padding_ver">12dp</item>
        <item name="qmui_bottom_sheet_grid_item_text_margin_top">9dp</item>
        <item name="qmui_bottom_sheet_grid_item_mini_width">84dp</item>
        <item name="qmui_bottom_sheet_grid_item_icon_size">56dp</item>

        <item name="qmui_bottom_sheet_title_style">@style/QMUI.BottomSheet.Title</item>
        <item name="qmui_bottom_sheet_cancel_style">@style/QMUI.BottomSheet.Cancel</item>
        <item name="qmui_bottom_sheet_list_item_text_style">@style/QMUI.BottomSheet.List.Text</item>
        <item name="qmui_bottom_sheet_grid_item_text_style">@style/QMUI.BottomSheet.Grid.Text</item>


        
        <item name="qmui_popup_radius">12dp</item>
        <item name="qmui_popup_border_width">1px</item>
        <item name="qmui_popup_shadow_elevation">16dp</item>
        <item name="qmui_popup_shadow_alpha">0.25</item>
        <item name="qmui_popup_shadow_inset">30dp</item>
        <item name="qmui_popup_arrow_width">18dp</item>
        <item name="qmui_popup_arrow_height">10dp</item>
        <item name="qmui_quick_action_item_padding_hor">4dp</item>
        <item name="qmui_quick_action_item_padding_ver">2dp</item>
        <item name="qmui_quick_action_item_middle_space">4dp</item>
        <item name="qmui_quick_action_padding_hor">4dp</item>
        <item name="qmui_quick_action_more_arrow_width">36dp</item>

        <item name="qmui_skin_support_popup_border_color">?attr/qmui_skin_support_color_separator</item>
        <item name="qmui_skin_support_popup_bg">@color/qmui_config_color_white</item>
        <item name="qmui_skin_support_popup_close_icon">@drawable/qmui_icon_popup_close_with_bg</item>
        <item name="qmui_skin_support_quick_action_item_tint_color">?attr/qmui_config_color_gray_1</item>
        <item name="qmui_skin_support_quick_action_more_left_arrow">@drawable/qmui_icon_quick_action_more_arrow_left</item>
        <item name="qmui_skin_support_quick_action_more_right_arrow">@drawable/qmui_icon_quick_action_more_arrow_right</item>
        <item name="qmui_skin_support_quick_action_more_tint_color">?attr/qmui_skin_support_quick_action_item_tint_color</item>


        
        <item name="QMUIButtonStyle">@style/QMUI.RoundButton</item>
        <item name="QMUITabSegmentStyle">@style/QMUI.TabSegment</item>
        <item name="QMUICommonListItemViewStyle">@style/QMUI.CommonListItemView</item>
        <item name="QMUIGroupListSectionViewStyle">@style/QMUI.GroupListSectionView</item>
        <item name="QMUITopBarStyle">@style/QMUI.TopBar</item>

        <item name="QMUITipPointStyle">@style/QMUI.TipPoint</item>
        <item name="QMUITipNewStyle">@style/QMUI.TipNew</item>

        <item name="QMUILoadingStyle">@style/QMUI.Loading</item>
        <item name="QMUIPullRefreshLayoutStyle">@style/QMUI.PullRefreshLayout</item>
        <item name="QMUIRadiusImageViewStyle">@style/QMUI.RadiusImageView</item>
        <item name="QMUIQQFaceStyle">@style/QMUI.QQFaceView</item>
        <item name="QMUISliderStyle">@style/QMUI.Slider</item>
        <item name="QMUISliderThumbStyle">@style/QMUI.SliderThumb</item>
    </style>`

**Comment by hjywyj** [comment]
qmui_button_*     是我自定义的样式，可以删掉

**Comment by cgspine** [comment]
可以升级到 2.0.0-alpha03， 通过 `QMUICommonListItemView.setSkinConfig` 来更改 theme 配置。
