### ISSUE TITLE
版本问题遇到的 Caused by: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by wflian** [Tencent/QMUI_Android#781]
### 运行环境 ###

- [x] 设备型号：如：`锤子T2`
- [x] 设备系统版本：如 `Android 5.1.1`
- [x] Gradle 版本：如 `3.5.2`
- [x] QMUI Android 版本：`1.4.3`
- [x] arch Android 版本：`0.6.2`
- [x] support版本：`androidx 1.1.0`

### 具体问题描述 ###
getLazyViewLifecycleOwner().getLifecycle().addObserver(this) 引起奔溃

#### 异常日志（堆栈） ####
The observer class has some methods that use newer APIs which are not available in the current OS version. Lifecycles cannot access even other methods so you should make sure that your observer classes only access framework classes that are available in your min API level OR use lifecycle:compiler annotation processor.

**Comment by cgspine** [comment]
看源码，好像是lifecycle 库反射代码`klass.getDeclaredMethods()`失败？你的这个手机版本不支持反射？

**Comment by wflian** [comment]
应该是不支持吧！目前手上几部手机，就这一部遇到

**Comment by cgspine** [comment]
可以 引入 `annotationProcessor "androidx.lifecycle:lifecycle-compiler:$lifecycle_version"` ，不用反射，而用代码生成

**Comment by wflian** [comment]
嗯！只能这样最保险了
