### ISSUE TITLE
2.0 的 Tab 的 icon 的使用疑惑

### ISSUE THREAD

**Issue by LLXBH** [Tencent/QMUI_Android#784]
我设置了 icon 两种状态的图片资源，
但都会给 Tab 接管后变成默认色（选中蓝色，未选灰色），
如何不被这样处理，想显示原有的状态

通过 setColorAttr（） 设置颜色后，
指定 R.color.xxxx 的某个颜色，也没有正确显示出该颜色（大多都变成两种状态都是红色），
而指定了qmui默认自带的颜色函数则没有问题

**Comment by v200123** [comment]
如果没记错，在Tab的构造函数有这个的控制

**Comment by cgspine** [comment]
tabBuilder.skinChangeWithTintColor(false) 就可以去掉 tint 了。
 setColorAttr 是传 R.attr，不是 R.color。 这个是换肤用的
