### ISSUE TITLE
QMUI适配AndroidX后老版本不兼容问题

### ISSUE THREAD

**Issue by Chen-Xi-g** [Tencent/QMUI_Android#785]
项目中有其他三方依赖库没有适配AndroidX，无法迁移导致无法使用新版QMUI及新迭代功能，是否考虑同时适配下老版本。

**Comment by cgspine** [comment]
在 gradle.properties 里 enableJetifier 就可以在编译器让其它三方库改成 Androidx 了。

**Comment by Chen-Xi-g** [comment]
> 在gradle.properties里enableJetifier就可以在编译器让其他三方库改成Androidx了。

你所说的办法在三方库中对 Support 包使用了强依赖，这时就会出错。

**Comment by cgspine** [comment]
有出错的例子的吗？我们项目依赖了很多第三方库，但好像没有会出错的
