### ISSUE TITLE
主体样式无效

### ISSUE THREAD

**Issue by ChangMuChen** [Tencent/QMUI_Android#789]
### 运行环境 ###

- [x] 设备型号：如：`Pixel 2`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `5.4.1`
- [x] QMUI Android 版本：`2.0.0`

### 具体问题描述 ###

我新建一个简单项目（用的是抽屉模板），别的什么都没做，只修改了App.Theme和AppTheme.NoActionBar，发现样式全变成了灰白，是不是我还需要其他操作，我没有找到任何有帮助的资料在网上。。。

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/17783347/71050866-60fe5580-2181-11ea-81f3-f24168eb0db5.png)

![image](https://user-images.githubusercontent.com/17783347/71050758-05cc6300-2181-11ea-8412-554dfbe2cfef.png)

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/71152233-cd0bb700-2270-11ea-801b-79f8fe37595c.png)

这里的颜色是通过 colorPrimary 控制的

**Comment by liupeng826** [comment]
Demo里面并没有设置，是为何？

**Comment by cgspine** [comment]
QMUI 在 qmui_theme.xml AppConfigTheme 里有设置。 Demo里面没用到官方 ToolBar
