### ISSUE TITLE
addRightView 如何设置 跟tittle 相同高度

### ISSUE THREAD

**Issue by Fanyunf** [Tencent/QMUI_Android#791]
使用 generateTopBarImageButtonLayoutParams 无效  找不到 方法
![image](https://user-images.githubusercontent.com/42140599/71148432-af395480-2266-11ea-9476-554171088944.png)

应该如何解决

**Comment by cgspine** [comment]
你用的是 QMUITopBarLayout ? 这个方法在 QMUITopBar 里， 不过好像从 QMUITopBarLayout 里没有方法去 get 到它，我可以加一下。

你也可以通过 `new LayoutParams(LayoutParams.WRAP_CONTENT, QMUIResHelper.getAttrDimen(getContext(), R.attr.qmui_topbar_height)` 来设置你自定义 View的高度为 topBar 的高度。

**Comment by Fanyunf** [comment]
试了一下 
![image](https://user-images.githubusercontent.com/42140599/71153674-aa7b9d00-2274-11ea-9b90-2f53aaa9eb95.png)
但还是没效果啊
![image](https://user-images.githubusercontent.com/42140599/71153632-8e77fb80-2274-11ea-81a9-a1ac2e28efed.png)

**Comment by cgspine** [comment]
用 Layout Inspector 看看， 是否是里面的 View 没有居中，另外， 既然是 icon，为何使用 addRightImageButton ?

**Comment by Fanyunf** [comment]
因为 要加3个Img 所以之间的 间距 使用addRightImageButton  不能设置间距

**Comment by cgspine** [comment]
可以通过 qmui_topbar_image_btn_width 来调整 ImgView 的宽度。 如果效果不行，那么就只能是 addRightView 了， 那么可以用  Layout Inspector 看看问题出在哪里了

**Comment by Fanyunf** [comment]
![image](https://user-images.githubusercontent.com/42140599/71440847-e06bc600-2739-11ea-9fad-54ebecec1097.png)

是View没居中

**Comment by Fanyunf** [comment]
![image](https://user-images.githubusercontent.com/42140599/71440910-127d2800-273a-11ea-806c-5c6e9c0e13fb.png)
嗯 是view 没居中

**Comment by Fanyunf** [comment]
解决了 谢谢了
