### ISSUE TITLE
遇到一个很奇怪的问题

### ISSUE THREAD

**Issue by wflian** [Tencent/QMUI_Android#796]
### 运行环境 ###

- [x] 设备型号：如：所有
- [x] 设备系统版本：所有
- [x] Gradle 版本：所有
- [x] QMUI Android 版本：`2.0.0`

### 具体问题描述 ###

遇到一个很奇怪的问题：
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    >
  <com.qmuiteam.qmui.widget.roundwidget.QMUIRoundButton
      android:id="@+id/btn_login"
      android:layout_width="match_parent"
      android:layout_height="37dp"
      android:text="登录"
      android:textColor="#00f"
      android:textSize="17sp"
      app:qmui_backgroundColor="#0f0"
      app:qmui_borderColor="#f00"
      app:qmui_borderWidth="3dp"
      app:qmui_radius="5dp"
      app:layout_constraintTop_toTopOf="parent"
      app:layout_constraintLeft_toLeftOf="parent"
      ></com.qmuiteam.qmui.widget.roundwidget.QMUIRoundButton>
<com.qmuiteam.qmui.widget.roundwidget.QMUIRoundRelativeLayout
      android:layout_width="200dp"
      android:layout_height="200dp"
      app:layout_constraintLeft_toLeftOf="parent"
      app:layout_constraintTop_toBottomOf="@+id/btn_login"
      app:qmui_backgroundColor="#0f0"
      app:qmui_borderColor="#f00"
      android:layout_marginTop="20dp"
      ></com.qmuiteam.qmui.widget.roundwidget.QMUIRoundRelativeLayout>
</androidx.constraintlayout.widget.ConstraintLayout>

QMUIRoundRelativeLayout所有功能都很正常，但是QMUIRoundButton涉及到尺寸部分的qmui_borderWidth、qmui_radius设置有效，涉及到颜色部分的backgroundColor、qmui_borderColor全部无效，新建demo测试又很正常，项目里面也无特殊处理。懵逼ing

**Comment by cgspine** [comment]
用了 2.0 版本 ? 2.0 版本 QMUIRoundButton 是有换肤控制的。 QMUIRoundRelativeLayout 这些遗漏了，我也会补上。

如果有换肤控制，很多一般的设置都会被换肤的覆盖掉，我后面加一个控制项好了。

**Comment by wflian** [comment]
但是我没设置换肤，配置都跟1.x 版本一样

**Comment by wflian** [comment]
回退1.4.3 版本没问题，而且这个是配合QMUIFragment+QMUIFragment 才会出现这个问题，如果一个普通的Activity里面使用就没有问题

**Comment by cgspine** [comment]
那就有点奇怪了， 可以在 QMUIRoundButton 里未 setBackgroundColor、setBgData、setStrokeColors 打下断点，看看是不是有方法调用了它来改颜色

**Comment by fengdesola** [comment]
2.0的版本，我跑的就是demo，发现颜色设置selector方式能正常显示，如果设置单个颜色，预览正常的，运行起来颜色显示不出来，是默认皮肤的颜色
![image](https://user-images.githubusercontent.com/7188399/71437475-ea3afc80-272c-11ea-8d36-d29f1dcbc259.png)

**Comment by wflian** [comment]
你这个跟我一样！设置颜色都无效，预览没问题，显示有问题。我现在先换回1.4.3版本，等闲了 要断点跟踪看下

**Comment by cgspine** [comment]
可以升级到 2.0.0-alpha03，应该可以了
