### ISSUE TITLE
询问建议

### ISSUE THREAD

**Issue by tanqidi** [Tencent/QMUI_Android#798]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [ ] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###

大哥，要怎样才能做到像你一样只新建少量必须的activity工程主体子业务与页面等用fragment来代替啊？我们工程有着大量的activity很不友好，另外2.0特别特别炫酷喜欢极了@_~

**Comment by cgspine** [comment]
http://blog.cgsdream.org/2019/12/21/qmui-gank-03/

看看这篇文章？
