### ISSUE TITLE
还是那个empty_view_detail文件中@id的问题  

### ISSUE THREAD

**Issue by 1359694358** [Tencent/QMUI_Android#802]
请看截图 我们集成 后编译不过的 debug和release都有问题 我把你的aar down下来本地改成@+id就对了 但这样你们后面更新我无法使用最新的
![图片](https://user-images.githubusercontent.com/18720445/71433821-46495500-271c-11ea-9e23-e5be04fc3af2.png)

**Comment by fengdesola** [comment]
这应该是gradle版本的问题，5以上的应该没问题，你试试

**Comment by cgspine** [comment]
可升级到 2.0.0-alpha03
