### ISSUE TITLE
升级 2.0 有些控件找不到

### ISSUE THREAD

**Issue by felixcc** [Tencent/QMUI_Android#804]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `6.0.1`
- [x] QMUI Android 版本：`2.0.0-alpha02`

### 具体问题描述 ###

升级了 2.0 以后
// qm ui
    implementation 'com.qmuiteam:qmui:2.0.0-alpha02'

    // qm arch
    implementation "com.qmuiteam:arch:2.0.0-alpha02"

QMUIListPopup

QMUITabSegment

这俩控件为什么找不着了？

**Comment by JonZone** [comment]
您好，这个问题怎么解决的?
我查找了代码里吗，确实是没有QMUIListPopup 这个类了

**Comment by cgspine** [comment]
QMUITabSegment 单独放到一个 package 里了，而且代码重构了。
QMUIListPopup 删除了， 可通过 QMUIPopups.listPopup() 来使用

**Comment by JonZone** [comment]
是的，我最后也发现了，本来打算放弃使用，直接用QMUIPopup了，结果无意中发现了QMUIPopups。这个文档和代码不匹配害死人啊。我还一直以为我集成有问题呢。
