### ISSUE TITLE
2.0对QMUITopBar怎么设置背景颜色啊

### ISSUE THREAD

**Issue by YuAmbrose** [Tencent/QMUI_Android#805]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`2.0.0`

**Comment by felixcc** [comment]
同问。

**Comment by cgspine** [comment]
1. 全局配置， theme 里配置 qmui_skin_support_topbar_bg
2. 无skin要求下， 直接使用系统的 setBackground
3. 有skin要求下，走 QMUISkinValueBuilder.background(attr)，然后通过 QMUISkinHelper.setSkinValue 进行设置

**Comment by qq282418234** [comment]
<com.qmuiteam.qmui.widget.QMUITopBar
        android:id="@+id/qmuitop"
        android:layout_width="match_parent"
        android:layout_height="45dp"
        android:background="@android:color/holo_red_dark" />  设置背景色不管用那

**Comment by felixcc** [comment]
![image](https://user-images.githubusercontent.com/459409/71637943-8a90a400-2c8c-11ea-87f8-8aab6dc95656.png)

运行 demo-topbar 是白色，无响应

![image](https://user-images.githubusercontent.com/459409/71637944-95e3cf80-2c8c-11ea-878c-d42f8e3ec3b9.png)


尝试用系统的 setBackground 无响应
-------------------------------------------------

而在全局设置
![image](https://user-images.githubusercontent.com/459409/71637946-abf19000-2c8c-11ea-9b3f-b5cd9c8d28c9.png)


在 xml 布局里实时响应

**Comment by cgspine** [comment]
在 Activity 层面，重写 

```
@Override
 protected boolean followSkin() {
        return false;
 }

```

禁用掉 skin 就行了，我改下这里的逻辑，目前默认必定会 followSkin 的。

**Comment by YuAmbrose** [comment]
QMUISkinValueBuilder builder = QMUISkinValueBuilder.acquire();
        builder.background(R.attr.app_primary_color);
        QMUISkinHelper.setSkinValue(mtopbar, builder);
可以在代码这样设置

**Comment by cgspine** [comment]
可升级到 2.0.0-alpha03

**Comment by YuAmbrose** [comment]
@Override
 protected boolean followSkin() {
        return false;
 }
2.0.0-alpha04 没找到这个方法。请问如果要禁用换肤主题需要如何配置

**Comment by cgspine** [comment]
更改了接口， 在 onCreate 里设置 setSkinManager(null)，现在有它的文档了：https://github.com/Tencent/QMUI_Android/wiki/QMUI-%E6%8D%A2%E8%82%A4
