### ISSUE TITLE
QMUIRoundButton问题

### ISSUE THREAD

**Issue by felixcc** [Tencent/QMUI_Android#806]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
<com.qmuiteam.qmui.widget.roundwidget.QMUIRoundButton
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_horizontal"
            android:clickable="true"
            android:focusable="true"
            android:gravity="center"
            android:padding="10dp"
            android:text="更改文字颜色、边框颜色和背景颜色"
            android:textColor="@color/white"
            app:qmui_backgroundColor="#FE790C"
            app:qmui_borderColor="#FE790C"
            app:qmui_borderWidth="1px" />

为啥生成背景失效啊？demo 里也是这么写的。

**Comment by cgspine** [comment]
你有开启 skin 控制吗？ QMUIDemo 是用 QDSkinManager 开启了 skin 控制的，因而其受到换肤的设置影响

**Comment by felixcc** [comment]
没有 skin 的控制。

**Comment by cgspine** [comment]
可以在 QMUIRoundButtonDrawable.fromAttributeSet 断点看看？

**Comment by cgspine** [comment]
在 Activity 层面，重写 

```
@Override
 protected boolean followSkin() {
        return false;
 }

```

禁用掉 skin 就行了，我改下这里的逻辑，目前默认必定会 followSkin 的。
