### ISSUE TITLE
关于禁用返回的问题

### ISSUE THREAD

**Issue by yueqianzhang** [Tencent/QMUI_Android#811]
### 运行环境 ###

- [x] QMUI Android 版本：2.0.0-alpha02

### 具体问题描述 ###
如下图，这个弃用方法才有效，下面的推荐方法无效
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/20694300/71673239-3a603180-2db3-11ea-8550-ae042e080726.png)
![image](https://user-images.githubusercontent.com/20694300/71673403-afcc0200-2db3-11ea-806e-faf3a3cd29a1.png)

**Comment by cgspine** [comment]
修改遗漏，谢谢反馈，我改改，周末会更新下一个版本
