### ISSUE TITLE
TopBarLayout添加两个按钮，如何设两个按钮间距

### ISSUE THREAD

**Issue by Andy957** [Tencent/QMUI_Android#813]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ### 
有设置的方法吗？

**Comment by Andy957** [comment]
间距很大，好丑

**Comment by cgspine** [comment]
可以在 theme 里重写 QMUITopBarStyle， 提供 小一点的 qmui_topbar_text_btn_padding_horizontal：

例如：

```
<item name="QMUITopBarStyle">@style/AppTopBar</item>

<style name="AppTopBar" parent="QMUI.TopBar">
    <item name="qmui_topbar_text_btn_padding_horizontal">5dp</item>
</style>
```

**Comment by Andy957** [comment]
好的，谢谢您
