### ISSUE TITLE
QMUITabSegment不能设置indicator的颜色吗

### ISSUE THREAD

**Issue by efkeok** [Tencent/QMUI_Android#817]
看到无论XMl里还是代码都没有设置颜色的地方，请问一下怎么设置颜色呢？

**Comment by cgspine** [comment]
目前 indicator 是由选中 tab 的颜色决定的，如果你不想跟随，可以通过 setIndicatorDrawable 通过 drawable 的形式来控制

**Comment by efkeok** [comment]
好的谢谢
