### ISSUE TITLE
混淆错误？

### ISSUE THREAD

**Issue by LLXBH** [Tencent/QMUI_Android#820]
### 运行环境 ###

- [x] 设备型号：如：`红米 Note 4x`
- [x] 设备系统版本：如 `Android 7.0`
- [x] Gradle 版本：如 `3.5.3`
- [x] QMUI Android 版本：`2.0.0-alpha02`

### 具体问题描述 ###
debug 模式下正常使用；
开启混淆打包后，页面空白，且点击返回键无法返回；
新项目如此，旧项目正常。

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/34165598/72323039-b8410880-36e2-11ea-8df8-eb44ff04481d.png)

#### Layout Inspector 文件([如何获取](https://github.com/QMUI/QMUI_Android/wiki/%E6%8F%90%E4%BE%9B-Layout-Inspector-%E6%96%87%E4%BB%B6)) ####
且无法生成 Layout Inspector，debug 模式下正常
![image](https://user-images.githubusercontent.com/34165598/72323304-5b921d80-36e3-11ea-94cb-e508117262fd.png)
![image](https://user-images.githubusercontent.com/34165598/72323375-85e3db00-36e3-11ea-95aa-9e7e7709297f.png)

#### 异常日志（堆栈） ####
无错误提醒

**Comment by LLXBH** [comment]
这是添加的混淆代码
![image](https://user-images.githubusercontent.com/34165598/72323415-a7dd5d80-36e3-11ea-9e91-3c707197304c.png)

**Comment by cgspine** [comment]
我在 Demo里加上混淆，并不会出现这种情况？ 你的这个项目只是引入了 QMUI  ？

**Comment by LLXBH** [comment]
> 我在Demo里加上纠正，并不会出现这种情况？你的这个项目只是约会了QMUI？

嗯，之前我的导入时这样的
![image](https://user-images.githubusercontent.com/34165598/72593358-ba53d300-393f-11ea-8587-2e0db2afae20.png)

后来我尝试删除了 build 文件夹和gradle下载的jar包，重新运行后就没有尝试过了，
有点奇怪😂
