### ISSUE TITLE
开启SKIN后，如何定义不同样式的topbar

### ISSUE THREAD

**Issue by hjywyj** [Tencent/QMUI_Android#822]
UI的设计，A页面topbar是白底黑字黑箭头的，B页面是蓝底白字白箭头的，如何单独设置topbar的样式？除了重写followSkin让他返回false

**Comment by cgspine** [comment]
topBar 的背景、分隔线一样是通过 QMUISkinHelper.setSkinValue 设置的， 每个button/imageButton 会返回相应的view，同样是通过 QMUISkinHelper.setSkinValue 设置tintColor、颜色

**Comment by hjywyj** [comment]
> topBar 的背景、分隔线一样是通过 QMUISkinHelper.setSkinValue 设置的， 每个button/imageButton 会返回相应的view，同样是通过 QMUISkinHelper.setSkinValue 设置tintColor、颜色

谢谢，但我没找到设置这几个的方法qmui_topbar_title_color，qmui_topbar_subtitle_color

**Comment by cgspine** [comment]
setTitle、setSubTitle 都会返回相应的 View 的
