### ISSUE TITLE
QMUITopBar设置渐变背景报错?

### ISSUE THREAD

**Issue by ysj40540** [Tencent/QMUI_Android#826]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 异常日志（堆栈） ####

QMUITopBar如何设置渐变背景  或者  图片为背景呢 我看是集成relativelayout为啥不能设置图片为背景呢 只能color

**Comment by Theoneee** [comment]
`    Drawable bgDrawable;
        try {
            bgDrawable = QMUIResHelper.getAttrDrawable(context, R.attr.qmui_topbar_bg_drawable);
        } catch (Exception e) {
            bgDrawable = null;
        }
        isNoBackground = null == bgDrawable;
        if (isNoBackground) {
            setBackgroundDividerEnabled(hasSeparator);
        } else {
            setBackground(bgDrawable);
        }
`

我是这样做的。

**Comment by cgspine** [comment]
1.x 版本不行，因为分割线也是通过背景来做的

**Comment by ysj40540** [comment]
> 1.x 版本不行，因为分割线也是通过背景来做的

那请问 有什么方法吗？

**Comment by cgspine** [comment]
直接用java代码调用 setBackground 设置背景， 不过这样就不能用分割线相关的方法了。
