### ISSUE TITLE
BottomSheetGrid 显示宽度没有占满屏幕

### ISSUE THREAD

**Issue by yetuweiba** [Tencent/QMUI_Android#831]
### 运行环境 ###

- [x] 设备型号:`华为 FDR-A01w`
- [x] 设备系统版本：如 `Android 5.1.1`
- [x] Gradle 版本：如 `5.6.1`
- [x] QMUI Android 版本：`2.0.0-alpha03`

### 具体问题描述 ###
BottomSheetGrid 在平板上宽度没有占满屏幕,请问宽度如何像先前版本占满屏幕?
#### 问题截图 ####
![2020-02-04-14-57-36](https://user-images.githubusercontent.com/2633167/73721265-d5577d00-475e-11ea-8bca-491f7a9014ae.png)

**Comment by cgspine** [comment]
theme 里通过 qmui_bottom_sheet_max_width 控制的，目前没支持 match_patent， 所以你可以填一个足够大的值。

**Comment by yetuweiba** [comment]
ok
