### ISSUE TITLE
dialog的setActionDivider(1,R.color.blue,0,0)第2个参数的颜色不起作用，还是默认的颜色

### ISSUE THREAD

**Issue by fuhaodev** [Tencent/QMUI_Android#837]
### 运行环境 ###

- [x] 设备型号：小米6
- [x] 设备系统版本：Android 9.0
- [x] Gradle 版本：4.6
- [x] QMUI Android 版本：2.0.0-alpha03

### 具体问题描述 ###
两个action按钮之间的分割线只能通过这个方法设置吧，请问是否有xml配置，这个方法不管怎么更改颜色都不起作用

**Comment by fuhaodev** [comment]
两个action按钮之间的分割线只能通过这个方法设置吧，请问是否有xml配置，这个方法不管怎么更改颜色都不起作用

**Comment by cgspine** [comment]
2.0 版本要求第二个参数传递 attr，而不是颜色， 2.0 版本为了支持 Dark Mode ，颜色多使用 attr。 我改下命名，加一个直接传颜色的方法。不过你这里还是默认颜色有点奇怪。目前没有xml设置，我可以开一个方法，直接设置分割线的宽度信息，颜色走theme里的设置。

**Comment by fuhaodev** [comment]
> 2.0 版本要求第二个参数传递 attr，而不是颜色， 2.0 版本为了支持 Dark Mode ，颜色多使用 attr。 我改下命名，加一个直接传颜色的方法。不过你这里还是默认颜色有点奇怪。目前没有xml设置，我可以开一个方法，直接设置分割线的宽度信息，颜色走theme里的设置。

嗯，确实是用的attr用错了，多谢指点，默认样色是我在style里面加了qmui_skin_support_dialog_action_divider_color
