### ISSUE TITLE
Demo中按返回键.重新打开又从launcher启动

### ISSUE THREAD

**Issue by zanderzhg** [Tencent/QMUI_Android#839]
### 运行环境 ###

- [x] 设备型号：如：`HUAWEI ALP-AL00`
- [x] 设备系统版本：如 `Android 8.0`
- [x] Gradle 版本：如 `3.5.2`
- [x] QMUI Android 版本：`2.0.0-alpha03`

### 具体问题描述 ###
按返回键后重新发开,又会从launcher页启动.
请问这个怎么处理
onCreate添加也没用
```kotlin
if (intent.flags and Intent.FLAG_ACTIVITY_BROUGHT_TO_FRONT != 0) {
            finish()         
            return
        }
```

**Comment by zanderzhg** [comment]
可以直接到返回前的页面吗

**Comment by cgspine** [comment]
从主页按返回？那就是杀掉app了？ 再打开从launcher 启动正常吧。 如果从其它界面返回，不会出现launcher 界面呀
