### ISSUE TITLE
QMUITabSegment怎么禁止点击事件？

### ISSUE THREAD

**Issue by chenyinchao** [Tencent/QMUI_Android#842]
### 运行环境 ###

- [x] 设备型号：如：`荣耀 V10`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `3.5.0`
- [x] QMUI Android 版本：` v2.0.0-alpha02`

### 具体问题描述 ###
QMUITabSegment怎么禁止点击事件

**Comment by cgspine** [comment]
为何会有这种需求？没有考虑过这种使用
重写 QMUITabSegment.createTabAdapter()， 返回一个 QMUITabAdapter 的子类， 在 onBindTab 里将 View disabe 掉，可以做到。

**Comment by chenyinchao** [comment]
我重写了QMUITabSegment的selectTab方法，if (fromTabClick == true)，就return了
