### ISSUE TITLE
QMUI 1.4.5的QMUILayout在Recyclerview里面使用不能设置圆角和阴影这是为什么

### ISSUE THREAD

**Issue by threedeer** [Tencent/QMUI_Android#843]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `3.0.1`
- [x] QMUI Android 版本：`1.4.5`

**Comment by cgspine** [comment]
有例子吗？给一份 Layout Inspector ?

**Comment by threedeer** [comment]
我是在recyclerview里面添加的
当我把 android:elevation="1dp"加上的时候，可以出现灰色的阴影和圆角，但不是我设置的颜色。

另外，我想问下能实现内外发光的样式吗？

多谢回答

**Comment by threedeer** [comment]
Layout Inspector  怎么给你  我拖进来说不能识别文件

**Comment by cgspine** [comment]
阴影颜色设置只支持 Android P 以上。 目前效果只能做到这样，如果要其它特效，还是只能依靠 9png。 LI 打包成zip就可以上传了。

**Comment by threedeer** [comment]
[LI.zip](https://github.com/Tencent/QMUI_Android/files/4304125/LI.zip)
那应该是安卓版本的原因了

谢谢
