### ISSUE TITLE
升级04全报错了

### ISSUE THREAD

**Issue by pandans** [Tencent/QMUI_Android#846]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

#### 异常日志（堆栈） ####

 android.view.InflateException: Binary XML file line #23 in :layout/qmui_group_list_section_layout: Binary XML file line #23 i

qmui_group_list_section_layout: Error inflating class android.widget.TextView

**Comment by cgspine** [comment]
给一下详情堆栈？

**Comment by pandans** [comment]
已解决，我自己入口inflate 传错 context了。找了好半天
