### ISSUE TITLE
MessageDialogBuilder在Fragment中使用的时候背景变暗了,但是弹窗不显示

### ISSUE THREAD

**Issue by clbDream** [Tencent/QMUI_Android#848]
### 运行环境 ###

- [x] 设备型号：如：小米Note3
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `3.5.3
- [x] QMUI Android 版本：2.0.0-alpha05

### 具体问题描述 ###
只显示灰色背景,不显示弹窗
` btn_login_out.setOnClickListener {
            MessageDialogBuilder(activity)
                .setTitle("退出登录")
                .setMessage("确定要退出吗？")
                .addAction(
                    "取消"
                ) { dialog, _ -> dialog.dismiss() }
                .addAction(
                    "确定"
                ) { dialog, _ ->
                    dialog.dismiss()
                    startActivity(Intent(context, LoginActivity::class.java))
                    activity?.finish()
                }
                .show()

        }`

**Comment by cgspine** [comment]
通过 Layout Inspector 可以获取到布局吗？

**Comment by clbDream** [comment]
我没有在布局文件中调用,我是点击退出登录按钮的时候调用的上面的代码
