### ISSUE TITLE
【求教】QMUIContinuousNestedScrollLayout使用时，沉浸模式时，悬浮的HeaderView会进入非安全区

### ISSUE THREAD

**Issue by jdwang-Shuke** [Tencent/QMUI_Android#857]
### 运行环境 ###

- [x] 设备型号：如：`XiaoMi 8`
- [x] 设备系统版本：如 `Android 10.0`
- [x] Gradle 版本：如 `3.6.1`
- [x] QMUI Android 版本：`2.0.0-alpha05`

### 具体问题描述 ###
QMUIContinuousNestedScrollLayout使用时，沉浸模式时，悬浮的HeaderView会进入非安全区；
1.如果getHeaderHeightLayoutParam返回ViewGroup.LayoutParams.WRAP_CONTENT；这样就会导致悬浮的HeaderView会进入非安全区；
2.如果getHeaderHeightLayoutParam返回getHeaderStickyHeight，就会有一个灰色的预留区域去不掉,这个区域的高度=状态栏高度+title高度

#### 实例项目地址 ####
https://github.com/jdwang-Shuke/HelloQmui.git

**Comment by cgspine** [comment]
QMUIContinuousNestedBottomAreaBehavior 有 setTopInset 方法，来处理这种偏移。
除外，QMUIContinuousNestedTopAreaBehavior 里有个Bug，导致顶部有多余的灰色区域

已经在你的仓库里fix，可以查看提交

**Comment by cgspine** [comment]
QMUIContinuousNestedBottomAreaBehavior 有 setTopInset 方法，来处理这种偏移。
除外，QMUIContinuousNestedTopDelegatedLayout 里有个Bug，导致顶部有多余的灰色区域

已经在你的仓库里fix，可以查看提交

**Comment by jdwang-Shuke** [comment]
感恩，多谢大神~

**Comment by jdwang-Shuke** [comment]
> QMUIContinuousNestedBottomAreaBehavior 有 setTopInset 方法，来处理这种偏移。
> 除外，QMUIContinuousNestedTopDelegatedLayout 里有个Bug，导致顶部有多余的灰色区域
> 
> 已经在你的仓库里fix，可以查看提交

感恩，多谢大神~
