### ISSUE TITLE
QMUIWindowInsetLayout 嵌套 QMUITopBarLayout 时在部分手机上显示不全 如下图

### ISSUE THREAD

**Issue by hanyulang** [Tencent/QMUI_Android#867]
### 运行环境 ###

- [x] 设备型号：如：`华为 nova 6 和 华为 nova 5i Pro`
- [x] 设备系统版本：如 `Android 9.0`
- [x] Gradle 版本：如 `5.4.1`
- [x] QMUI Android 版本：`1.4.0`

### 具体问题描述 ###
QMUIWindowInsetLayout 嵌套 QMUITopBarLayout 时在部分手机上显示不全
<img width="863" alt="QQ20200325-161014@2x" src="https://user-images.githubusercontent.com/13556989/77515246-25c39f00-6eb3-11ea-8606-22cf86fe3496.png">

#### 问题截图 ####
![7862E0A0-B9CE-4666-BBA3-6A9F5583D857](https://user-images.githubusercontent.com/13556989/77515122-f3b23d00-6eb2-11ea-9079-d9af16dfd49c.png)

**Comment by cgspine** [comment]
你的这个是CoordinatorLayout 盖住了 TopBarLayout 吧，可以将 TopBarLayout 放下面

**Comment by hanyulang** [comment]
解决了， 非常感谢，我脑子短路了！
