### ISSUE TITLE
请教下，没有TopBar 沉浸式的话，内容会到系统状态栏，怎么解决？

### ISSUE THREAD

**Issue by bastYYJ** [Tencent/QMUI_Android#868]
viewpage+fragment+底部导航栏 ，所以没有TopBar，页面滑动的话内容就会和状态栏重叠

**Comment by cgspine** [comment]
给 view 设置 fitSystemWindows = true

**Comment by zs1973** [comment]
哎 我设置了之后并没起作用哎  话说 我是 HomeActivity->HomeFragment->tab1+tab2+tab3这种   我在homeFragment的布局中设置了fitwindowsystem=true 没起作用

**Comment by zs1973** [comment]
> 给 view 设置 fitSystemWindows = true

哎 我设置了之后并没起作用哎  话说 我是 HomeActivity->HomeFragment->tab1+tab2+tab3这种   我在homeFragment的布局中设置了fitwindowsystem=true 没起作用
