### ISSUE TITLE
QMUITopBarLayout 设置背景无效

### ISSUE THREAD

**Issue by arjun2030** [Tencent/QMUI_Android#871]
### 运行环境 ###

- [x] 设备型号：如：`小米8`
- [x] 设备系统版本：如 `Android 10.0`
- [x] Gradle 版本：如 `5.6.4`
- [x] QMUI Android 版本：`2.0.0-alpha04`

### 具体问题描述 ###
在AppTheme 中配置qmui_skin_support_topbar_bg QMUITopBarLayout的背景色，然后在代码中设置背景颜色后无效。

QMUITopBarLayout mQMUITopBar= findViewById(R.id.topBar);
mQMUITopBar.setBackgroundColor(ContextCompat.getColor(this,R.color.app_color_theme_4));

布局代码：
<?xml version="1.0" encoding="utf-8"?>
<com.qmuiteam.qmui.widget.QMUIWindowInsetLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="?attr/app_common_background"
    tools:context=".SecondActivtiy">
    <com.qmuiteam.qmui.widget.QMUITopBarLayout
        android:id="@+id/topBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true">
    </com.qmuiteam.qmui.widget.QMUITopBarLayout>
</com.qmuiteam.qmui.widget.QMUIWindowInsetLayout>

**Comment by cgspine** [comment]
默认换肤是开启的，在 QMUIActvitiy.onCreate()  中通过 QMUIActvitiy.setSkinManager(null) 禁用

**Comment by cgspine** [comment]
可以升级到 2.0.0-alpha07， 我默认禁止了 skin
