### ISSUE TITLE
QMUIRoundButton组件的qmui_backgroundColor属性设置失效

### ISSUE THREAD

**Issue by lynkzyc** [Tencent/QMUI_Android#874]
### 运行环境 ###

- [x] 设备型号：如：`小米6`
- [x] 设备系统版本： `Android 9.0`
- [x] Gradle 版本：如 `3.6.1`
- [x] QMUI Android 版本：`2.0.0-alpha04`

### 具体问题描述 ###

我想要一个蓝色实心的QMUIRoundButton，可是设置qmui_backgroundColor属性无效，不知道是哪出错了，希望大牛指点，代码如下：

>  <com.qmuiteam.qmui.widget.roundwidget.QMUIRoundButton
            android:id="@+id/alpha_button"
            android:layout_width="168dp"
            android:layout_height="36dp"
            android:clickable="true"
            android:gravity="center"
            android:text="立即认证"
            android:textColor="#ffffff"
            app:qmui_backgroundColor="@color/s_round_btn_color"
            android:layout_marginTop="10dp"
            />

s_round_btn_color.xml如下：

`<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="@color/home_register_btn_bg_pressed" android:state_enabled="false" />
    <item android:color="@color/home_register_btn_bg_pressed" android:state_pressed="true" />
    <item android:color="@color/home_register_btn_bg" />
</selector>`

application中配置的主题引用的如下：
`<style name="QMUIAppTheme" parent="QMUI.Compat.NoActionBar"/>`

#### 问题截图 ####

想要的效果：
![image](https://user-images.githubusercontent.com/3033782/78019847-ec8fa100-7382-11ea-8fa1-6a7e39cc1b57.png)
实际运行效果：
![image](https://user-images.githubusercontent.com/3033782/78019877-fc0eea00-7382-11ea-8400-490dad66787b.png)

**Comment by cgspine** [comment]
禁用掉skin应该就好， QMUIActivity.setSkinManager(null)。 我框架默认禁用吧

**Comment by cgspine** [comment]
可以升级到 2.0.0-alpha07， 我默认禁止了 skin

**Comment by ckrgithub** [comment]
@lynkzyc 你好，我也遇到同样问题，你解决了么？
