### ISSUE TITLE
com.qmuiteam.qmui.widget.dialog.QMUIBottomSheet 在onCreateContentView方法中有个bug

### ISSUE THREAD

**Issue by happystar96** [Tencent/QMUI_Android#877]
### 具体问题描述 ###

com.qmuiteam.qmui.widget.dialog.QMUIBottomSheet 

在onCreateContentView方法中这个判断有问题  
if (mContentFooterViews != null && mContentHeaderViews.size() > 0) {
后面的.size  应该是mContentFooterViews 这个，要不添加底会一直报null

**Comment by cgspine** [comment]
可以升级到 2.0.0-alpha07
