### ISSUE TITLE
【求教】QMUIContinuousNestedScrollLayout 里的Webview的高度你们是怎么获得的？

### ISSUE THREAD

**Issue by spysoos** [Tencent/QMUI_Android#879]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###

QMUIContinuousNestedScrollLayout 里的Webview的高度你们是怎么获得的？比如Webview做为TopVieW，RecyclerView做为bottomView,我发现Webview是可以根据加载过程调节自身的高度的。RecyclerView也会很配合的往下滑动。我看了源码没发现实现的地方，难道是用js来不停的获取webview里content的高度吗？

**Comment by cgspine** [comment]
自身的高度获取就是走正常的measure、layout后获取的。 RecycerView 自动往下移动是用 CoordinatorLayout 的 Behavior 做的，可以看 QMUIContinuousNestedBottomAreaBehavior，它的位置依赖于 topView

**Comment by spysoos** [comment]
3Q

**Comment by xiexiang89** [comment]
x5webview滑动不流畅
