### ISSUE TITLE
QMUIDialog 不显示

### ISSUE THREAD

**Issue by 8023-Android** [Tencent/QMUI_Android#886]
new QMUIDialog.MessageDialogBuilder(mContext).setMessage("消息").setTitle("标题").create().show();  

完全不显示
但是第一次返回不会退出Activity感觉像是关闭了Dialog
第二次返回才退出Activity

**Comment by Theoneee** [comment]
当前界面的Theme继承了QMUI的Theme吗？

**Comment by 8023-Android** [comment]
<style name="AppTheme" parent="QMUI.Compat">
        
        <item name="colorPrimary">@color/themeColor</item>
        <item name="colorPrimaryDark">@color/themeColor</item>
        <item name="colorAccent">@color/themeColor</item>
    </style>

**Comment by 8023-Android** [comment]
可以了，values 用来QMUI的Theme  values-v19没用
