### ISSUE TITLE
QMUIContinuousNestedTopWebView设置padding和margin无效

### ISSUE THREAD

**Issue by victorfan336** [Tencent/QMUI_Android#887]
### 运行环境 ###

- [x] 设备型号：华为PTC10
- [x] 设备系统版本：Android 10.
- [x] Gradle 版本：3.6.2
- [x] QMUI Android 版本：2.0.0-alpha07
使用场景：类似于Demo中的QDContinuousNestedScroll5Fragment，mTopDelegateLayout.setDelegateView(mTopWebView); 使用QMUIContinuousNestedTopDelegateLayout有设置头部和尾部，中间是QMUIContinuousNestedTopWebView，但是我只想设置QMUIContinuousNestedTopWebView的margin或者padding值。
但是，QMUIContinuousNestedTopWebView通过setPadding或设置margin都没有效果，还是跟没有设置一样。我试过在其他界面使用QMUIWebView，然后设置marginStart是有效的，难道是我使用姿势不对吗？但是demo中QDContinuousNestedScroll5Fragment里，
mTopDelegateLayout.setDelegateView(mTopWebView);
后获取QMUIContinuousNestedTopWebView的layoutParams，然后设置marginStart,在将layoutParams赋值给QMUIContinuousNestedTopWebView，确实是没有效果的！
请问使用mTopDelegateLayout.setDelegateView(QMUIContinuousNestedTopWebView);后，怎么设置QMUIContinuousNestedTopWebView的边距呢？谢谢
@hzlzh @MoLice @chanthuang @kayo5994 @kirozhao

**Comment by victorfan336** [comment]
我用demo是过也是不行

**Comment by victorfan336** [comment]
希望能够在QMUIContinuousNestedTopWebView的onLayout中把margin加上吧，另外可以考虑支持在mTopDelegateLayout.setDelegateView方法中可以添加参数LayoutParams。谢谢。
我最终还是通过css样式添加的padding。

**Comment by cgspine** [comment]
可以通过 QMUIContinuousNestedTopDelegateLayout 设置 HeaderView 为 Space 之类的来实现间距。因为添加margin的支持会增加很多很多实现的复杂度， 事件传递、滚动考虑因素会变复杂。
