### ISSUE TITLE
arch的2.0.0-alpha07版本无法从jcenter仓库加载

### ISSUE THREAD

**Issue by kbxwn** [Tencent/QMUI_Android#889]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `3.5.2`
- [x] QMUI Android 版本：`2.0.0-alpha07`
- [x] arch Android 版本：`2.0.0-alpha07`

### 具体问题描述 ###
在app/build.gradle配置
implementation 'com.qmuiteam:qmui:2.0.0-alpha07'
implementation "com.qmuiteam:arch:2.0.0-alpha07"
再进行同步时报错
Failed to resolve: com.qmuiteam:arch:2.0.0-alpha07
而改为
implementation "com.qmuiteam:arch:2.0.0-alpha06"则同步通过没有问题

请问下com.qmuiteam:arch:2.0.0-alpha07版本是否已上传到jcenter仓库了呢

**Comment by cdcdec** [comment]
ERROR: Failed to resolve: com.qmuiteam:arch:2.0.0-alpha07 我的也是呀

**Comment by XD-Z** [comment]
我的也是，不知道为啥不行

**Comment by superit** [comment]
好好研究一下，你就明白了。 251648487 邮箱：251648487@qq.com 签名由 网易邮箱大师 定制 在2020年04月20日 14:56，Dogal 写道： 我的也是，不知道为啥不行 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by tuoxiebushuijiao** [comment]
我的也是一样

**Comment by cgspine** [comment]
2.0.0-alpha06 可以正常获取吗？

**Comment by LLXBH** [comment]
> 2.0.0-alpha06 可以正常获取吗？

可以正常获取，一样是7不行

**Comment by hanqingkai** [comment]
Resource missing  我的07也找不到资源

**Comment by cgspine** [comment]
可以用 2.0.0-alpha06 吧， 两个版本是一样的。 估计上传由于翻墙因素出了问题。但是我看 bintray 上是有包的，又无法重传。 估计明天会出 2.0.0-alpha08 版本

**Comment by cgspine** [comment]
可升级到  2.0.0-alpha08 版本

**Comment by kbxwn** [comment]
感谢关注
