### ISSUE TITLE
集成阿里百川sdk,QMUI.Compat.NoActionBar失效

### ISSUE THREAD

**Issue by wang2793312458** [Tencent/QMUI_Android#893]
### 运行环境 ###

- [x] 设备型号：如：`红米3`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `3.6.2`
- [x] QMUI Android 版本：`2.0.0-alpha07`

### 具体问题描述 ###
      //支付宝（可选）
    implementation 'com.alipay.android.app.cashier:standardcashier-single:15.6.5@aar'
    compileOnly 'com.alipay.mobile.android.securitysdk:apsecuritysdk-all:3.3.0'
    //登陆
    implementation 'com.ali.auth.sdk:alibabauth_core:2.0.0.6@aar'
    implementation 'com.ali.auth.sdk:alibabauth_ui:2.0.0.6@aar'
    implementation 'com.ali.auth.sdk:alibabauth_ext:2.0.0.6@aar'
    //安全组件
    implementation 'com.taobao.android:securityguardaar3:5.4.171@aar'
    implementation 'com.taobao.android:securitybodyaar3:5.4.99@aar'
    implementation 'com.taobao.android:avmpaar3:5.4.36@aar'
    implementation 'com.taobao.android:sgmiddletieraar3:5.4.9@aar'
    //Mtop
    implementation 'com.taobao.android:mtopsdk_allinone_open:3.1.2.5@jar'
    //applink
    implementation 'com.alibaba.sdk.android:alibc_link_partner:4.1.15@aar'
    //ut
    implementation 'com.taobao.android:utdid4all:1.5.2'
    implementation 'com.alibaba.mtl:app-monitor-sdk:2.6.4.5_for_bc'
    // 电商基础组件
    implementation 'com.alibaba.sdk.android:AlibcTradeCommon:4.0.0.8@aar'
    implementation 'com.alibaba.sdk.android:AlibcTradeBiz:4.0.0.8@aar'
    implementation 'com.alibaba.sdk.android:nb_trade:4.0.0.8@aar'
加入后，NoActionBar失效，注释掉上面的阿里sdk代码NoActionBar就会生效

**Comment by AreYReady** [comment]
谁知道怎么处理。我也发现同样的问题。使用自带的Theme.AppCompat.NoActionBar 不会失效。
