### ISSUE TITLE
QMUITabBuilder.setColor无效

### ISSUE THREAD

**Issue by kfperfect** [Tencent/QMUI_Android#894]
### 运行环境 ###

- [x] 设备型号：如：`乐视1s`
- [x] 设备系统版本：如 `Android 6.0`
- [x] Gradle 版本：如 `3.6.2`
- [x] QMUI Android 版本：`2.0.0-alpha07`

### 具体问题描述 ###
使用QMUITabSegment时，使用tabSegment.tabBuilder().setNormalColor(Color.BLACK).setSelectColor(Color.BLACK)无效，tab文字及indicator依然显示默认的蓝色，使用setColorAttr同样无效

**Comment by cgspine** [comment]
我测试是没有问题的，给下完整的使用代码？

**Comment by kfperfect** [comment]
感谢回复，以下是代码片段，请参考

**Comment by kfperfect** [comment]
感谢回复，以下是代码片段，请参考：
layout文件中使用：
<com.qmuiteam.qmui.widget.tab.QMUITabSegment
        android:id="@+id/tabSegment"
        android:layout_width="0dp"
        android:layout_height="@dimen/normal_90dp"
        android:background="@color/colorPrimary"
        android:paddingStart="0dp"
        android:paddingEnd="@dimen/normal_100dp"
        app:layout_constraintHorizontal_weight="1"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toLeftOf="@id/searchIcon"
        app:layout_constraintTop_toTopOf="parent"
        app:qmui_tab_has_indicator="true"
        app:qmui_tab_indicator_height="@dimen/normal_2dp"
        app:qmui_tab_indicator_with_follow_content="false"
        app:qmui_tab_mode="fixed"
        app:qmui_tab_normal_text_size="@dimen/normal_30dp"
        app:qmui_tab_selected_text_size="@dimen/normal_36dp"
        app:qmui_tab_space="@dimen/normal_80dp" />

在Fragment中使用：
val tabBuilder = tabSegment.tabBuilder().setNormalColor(Color.BLACK).setSelectColor(Color.BLACK)
        tabSegment.addTab(tabBuilder.setText(getString(R.string.recommand)).build(context))
        tabSegment.addTab(tabBuilder.setText(getString(R.string.latest)).build(context))
        tabSegment.addTab(tabBuilder.setText(getString(R.string.most_populater)).build(context))
        tabSegment.setupWithViewPager(homeViewPager)

**Comment by cgspine** [comment]
tabSegment.notifyDataChanged();
tabSegment.setupWithViewPager(homeViewPager, false)。

setupWithViewPager 第二个参数传false，不然会去 PageAdapter 里取标题生成 tab 了。

**Comment by kfperfect** [comment]
好的，我试一下，稍后反馈，非常感谢！

**Comment by kfperfect** [comment]
tabSegment.setupWithViewPager(homeViewPager, false)

**Comment by kfperfect** [comment]
tabSegment.setupWithViewPager(homeViewPager, false)
果然是这个问题，直接改了这一行就好了，再次感谢！
