### ISSUE TITLE
QMUIFragmentActivity.intentOf后无法跳转fragment

### ISSUE THREAD

**Issue by yongyf** [Tencent/QMUI_Android#897]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`v2.0.0-alpha07`

### 具体问题描述 ###
QMUIFragmentActivity.intentOf获取intent  ,startactivity无法跳到指定fragment

Can not find ID for " + fragmentName +
                    "; You must add annotation MayFirstFragment which include " + targetActivity.getName() +
                    " in " + fragmentName + " ."

**Comment by cgspine** [comment]
在 Activity 需要加 @FirstFragments 注解。可以看下 http://blog.cgsdream.org/2019/12/21/qmui-gank-03/

**Comment by yongyf** [comment]
FirstFragments已经添加 但是 但是不能生成xx_FirstFragmentFinder

**Comment by cgspine** [comment]
没有引入arch-compiler？

**Comment by yongyf** [comment]
谢谢解决了，没有引入arch-compiler
