### ISSUE TITLE
多层fragment侧滑返回上级fragment会压当前页面。

### ISSUE THREAD

**Issue by yongyf** [Tencent/QMUI_Android#899]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`2.0.0-alpha07`

### 具体问题描述 ###
fragment侧滑返回上级fragment会压当前fragment，可以修改吗

**Comment by cgspine** [comment]
你是指上层fragment拦截了手势返回事件？ 下个版本会支持多层嵌套

**Comment by zxxcos** [comment]
不是拦截了手势返回事件，而是多层嵌套的时候，侧滑Fragment会出现显示问题，当前的Fragment被之前的Fragment压在下面了，应该是SwipebackLayout造成的bug

**Comment by cgspine** [comment]
可以升级到 2.0.0-alpha09 ? 之前这个是自己处理的，alpha08 后替换成了官方的 FragmentContainerView，应该不会有这种问题了。

**Comment by zxxcos** [comment]
QMUIFragment，2.0.0-alpha09 没有这个问题了。
