### ISSUE TITLE
QMUIWindowInsetLayout在弹出软键盘的时候异常

### ISSUE THREAD

**Issue by lhj1079947827** [Tencent/QMUI_Android#902]
### 运行环境 ###

- [x] 设备型号：如：`KIW-TLOOH`
- [x] 设备系统版本：如 `Android 6.0.1`
- [x] Gradle 版本：如 `5.6.4`
- [x] QMUI Android 版本：`2.0.0-alpha07`

### 具体问题描述 ###
QMUIWindowInsetLayout包裹的QMUITopBarLayout在弹出软键盘的时候出现异常
#### 问题截图 ####
[
![image](https://user-images.githubusercontent.com/20966610/80349949-97bc4900-88a2-11ea-8e0a-8beaa00aafb7.png)
](url)
[
![image](https://user-images.githubusercontent.com/20966610/80349983-a60a6500-88a2-11ea-8cca-6143f369e2cb.png)
](url)

**Comment by lhj1079947827** [comment]
出了在这个测试机上出现上面问题，其他的机型正常.

**Comment by lhj1079947827** [comment]
[
![image](https://user-images.githubusercontent.com/20966610/80552692-02cc6380-89fa-11ea-84f8-1041c8b6eb7e.png)
](url)

上面的我是参照你的QMUIWindowInsetLayout来自己自定义的一个。

**Comment by shangxinlu034** [comment]
也有同样问题

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/81258922-59284a80-9069-11ea-8997-0973d3b198cc.png)
这里不支持自定义布局的。因为QMUIWindowInsetHelper 里有特殊处理，建议用 QMUIWindowInsetLayout2，它是基于 ConstraintLayout 的。

**Comment by lhj1079947827** [comment]
难受，我不怎么会这个控价...

**Comment by lhj1079947827** [comment]
你好我现在把布局改为了QMUIWindowInsetLayout2也是出现了上面图片的情况。在7.0的系统上出现，其他系统没有出现

**Comment by cgspine** [comment]
你也可以 copy 一份 QMUIWindowInsetHelper 来适配 RelativeLayout。你的topBarLayout约束是怎样写的？没有topToTop = parent ?

**Comment by lhj1079947827** [comment]
有

**Comment by lhj1079947827** [comment]
qmuitop我设置了 代码如下
`<?xml version="1.0" encoding="utf-8"?>
<com.qmuiteam.qmui.widget.QMUIWindowInsetLayout2 xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:background="@color/white"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <com.qmuiteam.qmui.widget.QMUITopBarLayout
        android:id="@+id/qmuitop"
        android:fitsSystemWindows="true"
        style="@style/MyTopBarStyle"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintBottom_toTopOf="@id/mSwipeRefresh"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
    <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
        android:id="@+id/mSwipeRefresh"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@id/qmuitop"
        app:layout_constraintBottom_toTopOf="@id/linear_bottom"
        android:layout_marginLeft="@dimen/dp_12"
        android:layout_marginRight="@dimen/dp_12"
        android:layout_below="@id/qmuitop"
        android:layout_above="@id/linear_bottom"
        android:layout_width="match_parent"
        android:layout_height="0dp">
        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/mRecyclerDiscussDetail"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
    </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>

    <LinearLayout
        android:id="@+id/linear_bottom"
        android:orientation="horizontal"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toBottomOf="@id/mSwipeRefresh"
        android:layout_alignParentBottom="true"
        android:background="@drawable/view_underline"
        android:gravity="center_vertical"
        android:layout_width="match_parent"
        android:layout_height="44dp">
        <EditText
            android:id="@+id/edit_content"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="34dp"
            android:layout_marginLeft="@dimen/dp_22"
            android:background="@drawable/shape_round_1"
            android:paddingLeft="@dimen/dp_10"
            android:hint="@string/text_207"
            android:textColorHint="#c1c1c1"
            android:textColor="@color/color_0C0C0C"
            android:textSize="@dimen/sp_15"
            />

        <TextView
            android:id="@+id/tv_send"
            android:layout_width="50dp"
            android:layout_height="match_parent"
            android:layout_marginLeft="@dimen/dp_10"
            android:gravity="center"
            android:text="@string/text_150"
            android:textColor="@color/color_999999"
            android:textSize="@dimen/sp_17"
            />
    </LinearLayout>

</com.qmuiteam.qmui.widget.QMUIWindowInsetLayout2>`

**Comment by cgspine** [comment]
![image](https://user-images.githubusercontent.com/7828876/81371356-33af4580-912a-11ea-984a-9e033029a59b.png)
断点下这里 QMUIWindowInsetHelper 的这里？ 7.0 的什么手机？

**Comment by cgspine** [comment]
你的 MyTopBarStyle height 不是 wrap_content ? 应该设成wrap_content, 没必要 Bottom_toTopOf = "@id/mSwipeRefresh"。 你这里不是做 chain 约束。

**Comment by lhj1079947827** [comment]
华为荣耀KIW-TLOOH 手机

**Comment by lhj1079947827** [comment]
你可以用一下模拟器7.1.1系统也会复现这种情况。

**Comment by lhj1079947827** [comment]
你好你把我这个代码复制过去就会复现了，java文件什么也不做，直接运行就出现了
`<?xml version="1.0" encoding="utf-8"?>
<com.qmuiteam.qmui.widget.QMUIWindowInsetLayout2 xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.qmuiteam.qmui.widget.QMUITopBarLayout
        android:id="@+id/qmuitop"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true"
        android:background="#00ff00"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
        android:id="@+id/mSwipeRefresh"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:layout_constraintBottom_toTopOf="@id/linear_bottom"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@id/qmuitop">

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/mRecyclerDiscussDetail"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>

    <LinearLayout
        android:id="@+id/linear_bottom"
        android:layout_width="match_parent"
        android:layout_height="44dp"
        android:layout_alignParentBottom="true"
        android:gravity="center_vertical"
        android:orientation="horizontal"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@id/mSwipeRefresh">

        <EditText
            android:id="@+id/edit_content"
            android:layout_width="0dp"
            android:background="@color/qmui_config_color_white"
            android:hint="请输入内容"
            android:layout_height="34dp"
            android:layout_weight="1"
            android:textColorHint="#c1c1c1" />

        <TextView
            android:id="@+id/tv_send"
            android:text="发布"
            android:layout_width="50dp"
            android:layout_height="match_parent"
            android:gravity="center" />
    </LinearLayout>

</com.qmuiteam.qmui.widget.QMUIWindowInsetLayout2>`

**Comment by cgspine** [comment]
我用模拟器，设置成上面的代码，好像一切正常？

**Comment by lhj1079947827** [comment]
你用的什么系统是7.1.1一下的系统吗？我这里是在7.0系统一下才会复现，如果7.0以上是正常的

**Comment by lhj1079947827** [comment]
9.0系统
[
![image](https://user-images.githubusercontent.com/20966610/81390922-d8dc1500-914e-11ea-8ffb-a35a0bcdf06f.png)
](url)
6.0.0系统
[
![image](https://user-images.githubusercontent.com/20966610/81391017-00cb7880-914f-11ea-8f1e-5faa7ac306da.png)
](url)

**Comment by cgspine** [comment]
找到原因了。因为升级了 appcompat 而导致的，新版本的 appcompat 包处理 windowInset 存在bug。 我之前测试是用了 QMUIActivity，被 SwipeBackLayout 保护了。 可升级到 2.0.0-alpha09 版本

**Comment by lhj1079947827** [comment]
谢谢了

**Comment by lhj1079947827** [comment]
这个问题怎么又会复现出来了
