### ISSUE TITLE
QMUITabSegment能否在自定义属性中增加正常字体颜色和选中字体颜色属性，如果获取的文案是viepager中的，字体颜色设置不起效

### ISSUE THREAD

**Issue by lhj1079947827** [Tencent/QMUI_Android#920]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
需求能否在自定义属性中增加正常字体颜色和选中字体颜色属性，每次都是要去java中设置有点麻烦。为什么给QMUITabSegment设置文案是从viewpager里获取那么设置颜色不起作用。必须要去生成TabBuild来设置颜色吗？
#### 问题截图 ####
[
![image](https://user-images.githubusercontent.com/20966610/81522024-a4996c00-937b-11ea-8f41-218b501892d5.png)
](url)

[
![image](https://user-images.githubusercontent.com/20966610/81522738-25f1fe00-937e-11ea-9916-75446acd574b.png)
](url)
还是默认颜色我设置我设置的颜色没有起作用。
`qmuiTab.tabBuilder()
            .setColorAttr(ContextCompat.getColor(this@CourseDetailActivity, R.color.color_CCCCCC),ContextCompat.getColor(this@CourseDetailActivity, R.color.color_222222))
            .build(this@CourseDetailActivity)`

**Comment by cgspine** [comment]
用 updateParentTabBuilder 更新默认设置。 tabBuilder() 是重新copy了一份默认的设置。 我补一下xml的默认颜色设置

**Comment by cgspine** [comment]
我想起为何这里没有xml 设置了，因为没找到传 attr 来支持换肤的方案。不过可以在全局 theme 里设置 qmui_skin_support_tab_normal_color 和 qmui_skin_support_tab_selected_color 来支持默认配置。

**Comment by lhj1079947827** [comment]
好吧，谢谢了
