### ISSUE TITLE
能否把QMUITabIndicator颜色开放出来，由我们控制颜色，因为这个颜色不一定和QMUITabSegment选中的字体颜色一致

### ISSUE THREAD

**Issue by lhj1079947827** [Tencent/QMUI_Android#921]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
能否把QMUITabIndicator颜色开发出来，由我们控制颜色，因为这个颜色不一定和QMUITabSegment选中的字体颜色一致

**Comment by cgspine** [comment]
setIndicator()， 传递自己实现的 QMUITabIndicator ？ 如果颜色固定，构造器可以传 fixedColorAttr 来制定一个 color attr。（因为换肤，QMUI 大多数都是穿 attr 了）。  如果颜色需要根据位置信息变化，可以通过重写 updateInfo 和 draw 来得到位置信息。

**Comment by lhj1079947827** [comment]
谢谢了，我懂了怎么弄了，看你的说明和源码

**Comment by lhj1079947827** [comment]
自己自定义了一个color attribute（ course_detail_indictor_color）我以为在color中赋值默认颜色就可以实现QMUITabIndicator颜色了呢，看了源码才知道 这个属性必须要放在style AppTheme中才能生效。希望还是尽快出一个详细文档。
