### ISSUE TITLE
QMUIPopups.listPopup只有顶部有弧度，底部没有弧度

### ISSUE THREAD

**Issue by youarenowhere** [Tencent/QMUI_Android#928]
### 运行环境 ###

- [x] 设备型号：如：`Redmi note3`
- [x] 设备系统版本：如 `Android 6.0`
- [x] Gradle 版本：如 `3.6.0`
- [x] QMUI Android 版本：`2.0.0-alpha08`

### 具体问题描述 ###
QMUIPopups.listPopup只有顶部有弧度，底部没有弧度
而且顶部弧线外层有白色背景，不是透明底色

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/16035966/82013332-aaa98880-96ac-11ea-95e3-602edbdfa8d4.png)

**Comment by cgspine** [comment]
QMUI Demo 里表现也是错的？ 看看 QMUIDemo 里面的 QMUILayout 是否可以正常显示圆角？

**Comment by youarenowhere** [comment]
> QMUI Demo 里表现也是错的？ 看看 QMUIDemo 里面的 QMUILayout 是否可以正常显示圆角？

Demo里是正常的。是我写的有问题么？
`       String[] array = new String[]{
                "Item 1",
                "Item 2",
                "Item 3",
                "Item 4",
                "Item 5",
        };
        ArrayAdapter adapter = new ArrayAdapter<>(context, android.R.layout.simple_list_item_1, new ArrayList<>(Arrays.asList(array)));
        int width = AutoSizeUtils.dp2px(context, 120);
        
        QMUIPopup qmuiPopup = QMUIPopups
                .listPopup(context, width, width * 2, adapter, null)
                .animStyle(QMUIPopup.ANIM_GROW_FROM_CENTER).shadowElevation(10, 1)
                .radius(30);

        qmuiPopup.show(v);`

**Comment by cgspine** [comment]
AutoSizeUtils.dp2px 是怎么计算的？ 感觉像是高度是屏幕放不下，被裁剪了。

**Comment by youarenowhere** [comment]
> AutoSizeUtils.dp2px 是怎么计算的？ 感觉像是高度是屏幕放不下，被裁剪了。
这块是把dp转为了px
` public static int dp2px(Context context, float value) {
        return (int) (TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, value, context.getResources().getDisplayMetrics()) + 0.5f);
    }`

**Comment by youarenowhere** [comment]
> AutoSizeUtils.dp2px 是怎么计算的？ 感觉像是高度是屏幕放不下，被裁剪了。

找到原因了。

**Comment by cgspine** [comment]
哦， 默认应该是开的， QMUI 用了 OutlineProvider，应该是依赖它
