### ISSUE TITLE
使用BottomListSheetBuilder时发生BadTokenException

### ISSUE THREAD

**Issue by 504254103** [Tencent/QMUI_Android#933]
### 运行环境 ###

- [x] 设备型号：如：`华为 mate 30`
- [x] 设备系统版本：如 `Android 10.0`
- [x] Gradle 版本：如 `3.5.2`
- [x] QMUI Android 版本：`2.0`

### 具体问题描述 ###
使用QMUIBottomSheet.BottomListSheetBuilder.show()时发生android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?崩溃

#### 问题截图 ####
new QMUIBottomSheet.BottomListSheetBuilder(getApplication())
                            .setGravityCenter(true)
                            .setSkinManager(QMUISkinManager.defaultInstance(MyApplication.getContext()))
                            .setTitle(null)
                            .setAddCancelBtn(true)
                            .setAllowDrag(true)
                            .setNeedRightMark(false)
                            .setOnSheetItemClickListener(new QMUIBottomSheet.BottomListSheetBuilder.OnSheetItemClickListener() {
                                @Override
                                public void onClick(QMUIBottomSheet dialog, View itemView, int position, String tag) {
                                    dialog.dismiss();
                                    if (0 == position) {
                                        initPermission(PMS_CAMERA);
                                    } else if (1 == position) {
                                        initPermission(PMS_READ_SD);
                                    }
                                }
                            }).addItem("拍照")
                            .addItem("选取相册")
                            .build()
                            .show();
#### 异常日志（堆栈） ####

android.view.ViewRootImpl.setView(ViewRootImpl.java:1016)
android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:447)
android.view.WindowManagerImpl.addView(WindowManagerImpl.java:118)
android.app.Dialog.show(Dialog.java:475)
com.qmuiteam.qmui.widget.dialog.QMUIBottomSheet.show(QMUIBottomSheet.java:204)
androidphone.dit.yczf.act.shop.AddShopActivity$6.onItemClick(AddShopActivity.java:398)
android.widget.AdapterView.performItemClick(AdapterView.java:330)
android.widget.AbsListView.performItemClick(AbsListView.java:1262)
android.widget.AbsListView$PerformClick.run(AbsListView.java:3309)
android.widget.AbsListView$3.run(AbsListView.java:4294)
android.os.Handler.handleCallback(Handler.java:900)
android.os.Handler.dispatchMessage(Handler.java:103)

**Comment by Theoneee** [comment]
```
new QMUIBottomSheet.BottomListSheetBuilder(getApplication())
```

为什么这里要传一个Application？

**Comment by 504254103** [comment]
> ```
> new QMUIBottomSheet.BottomListSheetBuilder(getApplication())
> ```
> 
> 为什么这里要传一个Application？

把getApplication()改成MyApplication.getContext()以后 报错变为layout/qmui_bottom_sheet_list: Error inflating class android.widget.TextView

**Comment by cgspine** [comment]
Dialog 要用 Activity 的 context

**Comment by 504254103** [comment]
用了Activity.this 可以了，但是总觉得哪个地方不对
