### ISSUE TITLE
title 上移的问题

### ISSUE THREAD

**Issue by YangMian** [Tencent/QMUI_Android#934]
### 具体问题描述 ###
标题栏 的 title 文字上移了，不知道怎么回事，请教一下
#### 问题截图 ####
![微信截图_20200526163223](https://user-images.githubusercontent.com/17924072/82878944-d3fccb00-9f6e-11ea-8d93-f6551bb406bb.png)

#### Layout  文件

<?xml version="1.0" encoding="utf-8"?>
<com.qmuiteam.qmui.widget.QMUIWindowInsetLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:background="@color/colorMain"
    android:orientation="vertical">

    <com.qmuiteam.qmui.widget.QMUITopBar
        android:id="@+id/topbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/colorAccent"
        android:fitsSystemWindows="true"
        app:qmui_bottomDividerHeight="0px" />

    <androidx.core.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true"
        android:layout_marginTop="?attr/qmui_topbar_height">

 .............................

    </androidx.core.widget.NestedScrollView>

</com.qmuiteam.qmui.widget.QMUIWindowInsetLayout>

**Comment by fuhaodev** [comment]
用QMUITopbarLayout

**Comment by YangMian** [comment]
昨天已经换了QMUITopbarLayout，问题已解决，这个issues  没关闭是想让同样遇到这个问题的同学注意到，也想知道QMUITopBar的title 为什么这么飘，谢谢您的回复，希望QMUI 越来越棒
