### ISSUE TITLE
QMUI在dialog中不生效

### ISSUE THREAD

**Issue by dongfangmingjia** [Tencent/QMUI_Android#935]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

### 具体问题描述 ###
使用QMUI进行主题切换，当在AlertDialog、BottomSheetDialogFragment中进行主题切换时，view主题没有改变。

**Comment by Theoneee** [comment]
都要用QMUISkinManager进行注册吧。

**Comment by dongfangmingjia** [comment]
需要单独注册
