### ISSUE TITLE
快速创建QMUITipDialog  出现无法关闭的问题

### ISSUE THREAD

**Issue by YangMian** [Tencent/QMUI_Android#936]
### 具体问题描述 ###

当用户快速点击，前一个QMUITipDialog  还没有关闭，如果这时再创建一个QMUITipDialog  的时候，采用定时关闭方式会导致最后一个 QMUITipDialog  没有被dismiss ，  这并不是QMUITipDialog  的问题，是一个应用场景会造成的业务 Bug

#### 代码 ####
当用户快速点击的时候showFailureTip会被调用多次

    @Override
    public void showFailureTip(String s) {//TODO 失败的请求回调

        tipDialog = new QMUITipDialog.Builder(this)
                .setIconType(QMUITipDialog.Builder.ICON_TYPE_FAIL)
                .setTipWord(s)
                .create();

        tipDialog.show();

        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                tipDialog.dismiss();
            }
        }, 1000);//延时1s执行

    }

**Comment by Theoneee** [comment]
是不是要判断下快速点击。或者点击之后给一个Loading弹窗显示。这样就能避免这种问题了把。

**Comment by YangMian** [comment]
最好提供一个可以动态设置提示文本setTipWord(s) 的方法，当tipDialog ！=null 就没必要在重复create()了，也会避免这个问题。

**Comment by cgspine** [comment]
new一个新 QMUITipDialog 时将旧的 dismiss 掉？

**Comment by YangMian** [comment]
谢谢，可行

**Comment by strivecheng** [comment]
> 最好提供一个可以动态设置提示文本setTipWord(s) 的方法，当tipDialog ！=null 就没必要在重复create()了，也会避免这个问题。

我也是没发修改文字，除非重新new，一个页面用一个tipDialog目前不行
