### ISSUE TITLE
QMUIPullLayout  刷新

### ISSUE THREAD

**Issue by gzllSnail** [Tencent/QMUI_Android#945]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `5.6.4`
- [x] QMUI Android 版本：`2.0.0`

### 具体问题描述 ###

QMUIPullLayout 好像只能 包裹 RecyclerView  ，一些复杂布局会有冲突
比如 :首页设定可以下拉刷新 ，首页中的 RecyclerView   可以上下拉动刷新 中间还有其他VIew
     这时候 QMUIPullLayout  就会失去效果   

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/35624362/84349710-7b723280-abea-11ea-8c52-aaed464367c8.png)
![image](https://user-images.githubusercontent.com/35624362/84349833-bd02dd80-abea-11ea-89dc-e72561c285c9.png)

**Comment by cgspine** [comment]
QMUIPullLayout 是基于 nested scrolling 来实现的，所以其 target view 只能是  RecyclerView、NestedScrollView 这些， 或者 target view 实现 NestedScrollingChild3
