### ISSUE TITLE
QMUIBottomSheet设置Title后如何隐藏分割线

### ISSUE THREAD

**Issue by lx8s8** [Tencent/QMUI_Android#954]
### 运行环境 ###

- [x] 设备型号：如：`Yota3`
- [x] 设备系统版本：如 `Android 8.1`
- [x] Gradle 版本：如 `4.0.0`
- [x] QMUI Android 版本：`com.qmuiteam:qmui:2.0.0-alpha10`

### 具体问题描述 ###

QMUIBottomSheet设置Title后如何隐藏分割线
已经通过设置qmui_skin_support_bottom_sheet_separator_color为透明解决问题
但是现在发现我设置qmui_bottom_sheet_title_style的 text 颜色无效

#### 问题截图 ####

<img width="392" alt="WeChat9972baed33591bb9b61daf519e5d0e20" src="https://user-images.githubusercontent.com/2274385/85936464-bafc8680-b92d-11ea-8cc0-b331cddcd823.png">

**Comment by cgspine** [comment]
有设置 skinManager ?

**Comment by lx8s8** [comment]
> 有设置skinManager吗？

设置的默认defaultInstance，就是这个问题
