### ISSUE TITLE
这随意写个Demo就不能用啊 

### ISSUE THREAD

**Issue by kokobebekoko** [Tencent/QMUI_Android#987]
### 运行环境 ###

- [x] 设备型号：如：`华为mate30
- [x] 设备系统版本：如 `Android Q`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：最新版本

### 具体问题描述 ###
android.view.InflateException: Binary XML file line #31 in android:layout/screen_toolbar: Binary XML file line #31 in android:layout/screen_toolbar: Error inflating class
#### 问题截图 ####
![图片](https://user-images.githubusercontent.com/5987097/89629734-ea10fb00-d8d0-11ea-9333-08f9faba60df.png)
![图片](https://user-images.githubusercontent.com/5987097/89629796-ff862500-d8d0-11ea-8cb5-28476f24f761.png)
![图片](https://user-images.githubusercontent.com/5987097/89629831-0d3baa80-d8d1-11ea-9b28-6e597fbbe6ba.png)
![图片](https://user-images.githubusercontent.com/5987097/89629853-162c7c00-d8d1-11ea-8298-5f835f8eca89.png)

**Comment by kokobebekoko** [comment]
不好意思 找到问题了 我appcompat版本太低了

**Comment by ckrgithub** [comment]
@kokobebekoko 你好，你那边是什么原因。我一直找不到问题所在
