### ISSUE TITLE
请教，如何给Dialog的menuItem之间设置分割线

### ISSUE THREAD

**Issue by kingslou** [Tencent/QMUI_Android#994]
### 运行环境 ###

- [x] 设备型号：如：`Nexus 6`
- [x] 设备系统版本：如 `Android 5.0`
- [x] Gradle 版本：如 `2.3.0`
- [x] QMUI Android 版本：`1.x.x`

**Comment by Theoneee** [comment]
![BottomSheet](https://user-images.githubusercontent.com/32156330/91700401-66cd8700-eba8-11ea-8b04-93d4efc021d4.png)
![QMUIBottomSheetListItemDecoration](https://user-images.githubusercontent.com/32156330/91700418-6fbe5880-eba8-11ea-87a5-2a8a31c55447.png)

Theme里改变整个值即可

```
qmui_skin_support_bottom_sheet_separator_color
```

**Comment by kingslou** [comment]
这个是底部菜单栏的 我看了下 QmDialog目前无法实现
